const src=(pages,section)=>({book:"Tajweed Rules of the Qur'an — Part Two",pdf:"tajweed-rules_part-2.pdf",printedPages:pages,pdfPages:pages.map(p=>p+15),chapter:"The Connecting Hamzah (Hamzah Al-Wasl)",section,verification:"book chapter aligned; exceptional meeting forms require qualified-teacher review"});
const ex=(arabic,label,target,rule,why,how,page)=>({arabic,surah:{ar:"مثال من الكتاب",en:label},ayah:"—",targetText:target,triggerLetter:target,previousLetter:"همزة الوصل وسياقها",rule,teacherExplanation:why,readingInstruction:how,commonError:"Pronouncing hamzah al-wasl during connection or choosing its starting vowel by guesswork.",wordBoundary:"start-or-connection",sourcePage:page,verificationStatus:"teacher-review-required"});
const q=(stage,prompt,items,answer)=>({stage,type:"hamzah-wasl-decision",instruction:{en:"Choose the best answer."},prompt,items,acceptedAnswers:[answer],feedbackCorrect:"Correct.",feedbackIncorrect:"Identify word type, start/connection state, and the controlling vowel."});
function make(s){const {id,n,ar,en,pages,defAr,defEn,formula,condition,letters,examples,groups=[],extra=[]}=s;return{
 id,unitId:"part2-unit-06",lessonNumber:`6.${n}`,title:{ar,en},source:src(pages,en),contentOrigin:"book-source-and-instructional-design",level:"Part Two",estimatedMinutes:n===12?55:44,
 prerequisites:["Distinguish noun, verb, and particle.","Identify the third letter of a command or past verb.","Distinguish starting from connected reading."],
 learningOutcomes:[`Define ${en.toLowerCase()}.`,"Identify hamzah al-wasl visually and structurally.","Choose whether it is pronounced or dropped.","Select the correct starting vowel with a reason.","Apply exceptional meetings under teacher supervision."],
 definition:{linguistic:{ar:"همزة الوصل تثبت في الابتداء وتسقط في درج الكلام.",en:"Hamzah al-wasl is pronounced when beginning and omitted during connected reading."},technical:{ar:defAr,en:defEn},studentFriendly:{ar:defAr,en:defEn},memoryFormula:formula},
 keyTerms:[{ar:"همزة الوصل",transliteration:"hamzah al-wasl",en:"connecting hamzah"},{ar:"همزة القطع",transliteration:"hamzah al-qata'",en:"fixed hamzah"},{ar:"الابتداء",transliteration:"al-ibtida'",en:"starting"},{ar:"الوصل",transliteration:"al-wasl",en:"connection"}],
 teacherPreparation:["Prepare start-versus-connect pairs.","Color the word category and controlling letter.","Model the vowel without lengthening it.","Reserve exceptional double-hamzah forms for teacher-led recitation."],
 openingReview:[{minutes:2,teacherPrompt:"Are we starting or connecting?"},{minutes:2,teacherPrompt:"Is the word a verb, noun, or أل article?"}],
 conceptExplanation:[{audience:"student",text:defEn},{audience:"teacher",text:"Always decide pronunciation first, then starting vowel, then any exceptional hamzah meeting."}],
 lessonPath:[{step:1,title:"Locate",text:"Find hamzah al-wasl."},{step:2,title:"Context",text:"Decide start or connection."},{step:3,title:"Classify",text:"Name verb, noun, or article."},{step:4,title:"Choose vowel",text:"Apply fathah, dammah, or kasrah rule."},{step:5,title:"Recite",text:"Start or connect without adding length."}],
 visualExplanation:[{type:"rule-equation",display:formula,teacherUse:"Reveal hamzah, context, category, controller, then vowel."}],ruleSummary:{condition,result:defEn,location:"At the beginning of selected verbs, nouns, and the definite article.",letters},
 letterGroups:groups.length?groups:[{name:{ar,en},letters}],quranExamples:examples,
 guidedPractice:[{sequence:1,teacherAction:"Read the phrase in connection.",studentAction:"Identify the omitted hamzah.",feedback:"Do not choose a vowel until start is requested."},{sequence:2,teacherAction:"Ask the learner to begin.",studentAction:"Classify and choose the vowel.",feedback:"Require a full reason."}],
 oralPractice:[{cycle:["find","start/connect","word type","controller","recite"],examplesRequired:examples.length,teacherObservation:["correct omission","correct starting vowel","no added madd","correct exceptional form"]}],
 interactiveActivities:[q("1 · Core","When is hamzah al-wasl pronounced?",["When beginning","Always in connection","Never"],"When beginning"),q("2 · Connection","What happens during connected reading?",["Hamzah al-wasl is omitted","It becomes a long madd","Every preceding vowel is removed"],"Hamzah al-wasl is omitted"),q("3 · Trigger","What controls this lesson?",[condition,"English translation","Word length"],condition),q("4 · Order","What comes before choosing the vowel?",["Identify word type and context","Guess from sound","Read the next verse"],"Identify word type and context"),q("5 · Mastery","What confirms correct application?",["Teacher-observed start and connection","Visual quiz alone","Fast reading"],"Teacher-observed start and connection"),...extra],
 commonMistakes:["Pronouncing hamzah al-wasl in connection.","Using dammah whenever any later letter has dammah.","Lengthening the starting vowel.","Treating hamzah al-qata like hamzah al-wasl."],correctionTechniques:["Read connection first, then restart.","Box the controlling third letter.","Contrast fixed and incidental vowels.","Use a start/connect toggle card."],
 knowledgeChecks:[{type:"decision",prompt:"Decide ten start/connect examples.",success:"Eight correct with reason."},{type:"recitation",prompt:"Recite mixed examples.",success:"Two teacher-approved attempts."}],
 teacherQuestions:["Start or connect?","What word type?","Which letter controls the vowel?","Is another hamzah meeting it?"],studentTasks:["Mark hamzah.","Classify word.","Choose and justify vowel.","Recite both contexts."],
 liveClassFlow:[{minutes:5,phase:"Review",display:"Word type"},{minutes:8,phase:"Definition",display:formula},{minutes:12,phase:"Decision tree",display:"Start / connect"},{minutes:10,phase:"Examples",display:"Controller"},{minutes:8,phase:"Recitation",display:"Teacher listening"},{minutes:3,phase:"Exit",display:"Vowel and reason"}],
 independentPractice:["Prepare five start/connect pairs."],homework:["Write category, controller, and starting vowel for six words."],exitTicket:["State start/connect.","Choose vowel.","Recite."],masteryCriteria:["Recognizes wasl.","Drops it in connection.","Chooses vowel correctly.","Handles taught exceptions.","Passes two attempts."],
 teacherNotes:["Do not generalize exceptional double-hamzah forms.","Keep grammar analysis limited to the decision."],sourceNotes:[`Uses printed pages ${pages.join(", ")}.`],verificationStatus:"source-aligned; qualified-teacher recitation review required"}}
const specs=[
 {id:"tajweed-p2-u06-l01-wasl-qata",n:1,ar:"همزة الوصل وهمزة القطع",en:"Hamzah al-wasl and hamzah al-qata",pages:[49,50],defAr:"همزة الوصل تثبت ابتداء وتسقط وصلًا، أما همزة القطع فتثبت ابتداء ووصلًا وتظهر عليها علامة الهمزة.",defEn:"Hamzah al-wasl is heard only when starting, whereas hamzah al-qata remains pronounced in both starting and connection.",formula:"وصل: ٱ تسقط / أ إ تبقى | ابتداء: كلتاهما تنطق",condition:"Whether the hamzah is wasl or qata and whether reading starts or connects",letters:["ٱ","أ","إ"],groups:[{name:{ar:"وصل",en:"Wasl"},letters:["ٱ"]},{name:{ar:"قطع",en:"Qata"},letters:["أ","إ","ؤ","ئ"]}],examples:[ex("وَٱلْحَمْدُ","Wasl in connection","ٱلْ","همزة وصل","The preceding waw connects directly to lam.","Omit the hamzah sound.",49),ex("وَأَنزَلَ","Qata in connection","أَ","همزة قطع","The written hamzah remains fixed.","Pronounce it after waw.",50)]},
 {id:"tajweed-p2-u06-l02-verbs",n:2,ar:"همزة الوصل في الأفعال",en:"Hamzah al-wasl in verbs",pages:[51,52,53,54,55,56,57],defAr:"تأتي همزة الوصل في أمر الفعل الثلاثي وفي ماضي وأمر ومصدر الخماسي والسداسي، وتسقط في الوصل وتتحرك عند الابتداء بحسب القاعدة.",defEn:"Hamzah al-wasl occurs in the command of selected triliteral verbs and in past, command, and verbal-noun forms of five- and six-letter patterns; it drops in connection and takes a rule-based starting vowel.",formula:"صيغة فعل فيها ٱ + ابتداء → افحص الحرف الثالث",condition:"A verb form containing hamzah al-wasl",letters:["ٱفْعَل","ٱنْفَعَل","ٱسْتَفْعَل"],examples:[ex("ٱهْدِنَا","Triliteral command","ٱهْ","وصل في فعل","Command begins with wasl.","Start with kasrah.",51),ex("ٱسْتَغْفَرَ","Six-letter past","ٱسْ","وصل في فعل","The augmented past begins with wasl.","Use the taught starting rule.",54)]},
 {id:"tajweed-p2-u06-l03-verb-vowels",n:3,ar:"حركات البدء في الأفعال",en:"Starting vowels in verbs",pages:[52,53,54,55,56,57],defAr:"يبدأ بضم همزة الوصل إذا كان الحرف الثالث مضمومًا ضمًا أصليًا، ويبدأ بالكسر إذا كان الثالث مفتوحًا أو مكسورًا أو كانت ضمته عارضة.",defEn:"Begin hamzah al-wasl with dammah when the verb's third letter has an original dammah; begin with kasrah when it has fathah, kasrah, or an incidental dammah.",formula:"ثالث الفعل: ضم أصلي → اُ | فتح/كسر/ضم عارض → اِ",condition:"The original vowel of the verb's third letter",letters:["اُ","اِ"],groups:[{name:{ar:"ضم",en:"Start u"},letters:["ثالثه ضم أصلي"]},{name:{ar:"كسر",en:"Start i"},letters:["ثالثه فتح/كسر/ضم عارض"]}],examples:[ex("ٱدْخُلُوا","Original third-letter dammah","خُ","ابتداء بالضم","Kha has original dammah.","Begin اُدْخُلُوا.",53),ex("ٱضْرِبْ","Third-letter kasrah","رِ","ابتداء بالكسر","Ra has kasrah.","Begin اِضْرِبْ.",53),ex("ٱمْشُوا","Incidental dammah context","شُ","ابتداء بالكسر","The apparent dammah is not the controlling original case.","Use the taught kasrah start.",56)],extra:[q("6 · Apply","Original dammah on the third letter gives:",["Dammah start","Fathah start","Always kasrah"],"Dammah start"),q("6 · Apply","Third-letter fathah gives:",["Kasrah start","Dammah start","No hamzah"],"Kasrah start")]},
 {id:"tajweed-p2-u06-l04-nouns",n:4,ar:"همزة الوصل في الأسماء",en:"Hamzah al-wasl in nouns",pages:[58,59,60,61,62],defAr:"تأتي همزة الوصل في أل التعريف وفي أسماء سماعية مخصوصة، ويبدأ بها في الأسماء السماعية بالكسر.",defEn:"Hamzah al-wasl occurs in the definite article and in specific transmitted nouns; the special nouns begin with kasrah.",formula:"اسم سماعي بهمزة وصل → ابتداء بالكسر",condition:"A recognized noun carrying hamzah al-wasl",letters:["ٱسْم","ٱبْن","ٱمْرُؤ"],examples:[ex("ٱسْمُ","Special noun","ٱسْ","وصل في اسم","Ism is a transmitted wasl noun.","Begin with kasrah.",58),ex("ٱبْنُ","Son","ٱبْ","وصل في اسم","Ibn belongs to the taught list.","Begin with kasrah.",59)]},
 {id:"tajweed-p2-u06-l05-seven-nouns",n:5,ar:"الأسماء السبعة السماعية",en:"The seven special nouns",pages:[58,59,60,61,62],defAr:"يحفظ الطالب الأسماء السماعية الواردة في القرآن وصيغها: اسم، ابن، ابنة، امرؤ، امرأة، اثنان، اثنتان، ويبدأ بهمزة وصلها مكسورة.",defEn:"The learner memorizes the Qur'anic transmitted noun forms ism, ibn, ibnah, imru', imra'ah, ithnan, and ithnatan; their hamzah al-wasl begins with kasrah.",formula:"اسم ابن ابنة امرؤ امرأة اثنان اثنتان → اِ",condition:"One of the seven transmitted noun families",letters:["ٱسْم","ٱبْن","ٱبْنَة","ٱمْرُؤ","ٱمْرَأَة","ٱثْنَان","ٱثْنَتَان"],examples:[ex("ٱمْرَأَةُ","Woman","ٱمْ","اسم سماعي","The noun is in the taught list.","Begin with kasrah.",60),ex("ٱثْنَانِ","Two","ٱثْ","اسم سماعي","The dual-number noun is transmitted with wasl.","Begin with kasrah.",61),ex("ٱبْنَتَ","Daughter","ٱبْ","اسم سماعي","The feminine family form belongs to the list.","Use kasrah when starting.",62)]},
 {id:"tajweed-p2-u06-l06-particles",n:6,ar:"همزة الوصل في الحروف",en:"Hamzah al-wasl in particles",pages:[63],defAr:"موضع همزة الوصل القياسي في الحروف هو أل التعريف، ويبدأ بها بالفتح وتسقط عند وصلها بما قبلها.",defEn:"The regular particle containing hamzah al-wasl is the definite article أل; it begins with fathah and its hamzah drops in connection.",formula:"أل + ابتداء = أَلْ | وصل = سقوط الهمزة",condition:"Hamzah al-wasl in the definite article أل",letters:["ٱلْ"],examples:[ex("ٱلْحَمْدُ","Starting the article","ٱلْ","ابتداء بالفتح","The definite article starts with fathah.","Say أَلْحَمْدُ without lengthening.",63),ex("وَٱلْعَصْرِ","Connecting to the article","وَٱلْ","سقوط في الوصل","Waw connects directly to lam.","Do not pronounce a separate hamzah.",63)]},
 {id:"tajweed-p2-u06-l07-chart",n:7,ar:"جدول اختيار حركة البدء",en:"Starting-vowel decision chart",pages:[64],defAr:"يبدأ بأل بالفتح، وبالأسماء السماعية بالكسر، وفي الأفعال ينظر إلى ضمة الحرف الثالث الأصلية؛ فإن وجدت ضم وإلا كسر.",defEn:"Start أل with fathah, special nouns with kasrah, and verbs with dammah only for an original third-letter dammah; otherwise use kasrah.",formula:"أل→أَ | اسم سماعي→إِ | فعل: ثالثه ضم أصلي→اُ وإلا→اِ",condition:"Word category first, then the verb's original third-letter vowel",letters:["أَ","إِ","اُ","اِ"],examples:[ex("ٱلْفَلَقِ","Article","ٱلْ","فتح","أل controls the decision.","Start أَلْ.",64),ex("ٱسْم","Noun","ٱسْ","كسر","Special noun controls the decision.","Start إِسْم.",64),ex("ٱدْخُلْ","Verb","خُ","ضم","Original third-letter dammah controls.","Start اُدْخُلْ.",64)],extra:[q("6 · Chart","How does أل begin?",["With fathah","With dammah","With kasrah"],"With fathah"),q("6 · Chart","How do special nouns begin?",["With kasrah","With fathah","With sukoon"],"With kasrah")]},
 {id:"tajweed-p2-u06-l08-meeting",n:8,ar:"التقاء همزة الوصل وهمزة القطع",en:"Meeting of hamzah al-wasl and hamzah al-qata",pages:[65,66,67,68,69],defAr:"إذا اجتمعت همزة الوصل وهمزة القطع في كلمة أو دخلت همزة الاستفهام، تتغير صورة الأداء بحسب الترتيب ونوع الكلمة، وتطبق الأوجه المنقولة دون قياس عام.",defEn:"When hamzah al-wasl meets hamzah al-qata within a word or after question hamzah, performance depends on order and word type; only the transmitted forms are applied.",formula:"همزتان مجتمعتان → حدد الترتيب والنوع → طبق الوجه المنقول",condition:"Hamzah al-wasl and fixed or question hamzah meet in one word",letters:["ٱ + ء","أَ + ٱ"],examples:[ex("ٱؤْتُمِنَ","Wasl before qata","ٱؤْ","اجتماع همزتين","The starting form requires the taught transformation.","Recite only after teacher modeling.",65),ex("ءَآللَّهُ","Question before article","ءَآل","استفهام مع الوصل","Question hamzah meets the article's wasl hamzah.","Use the transmitted form.",68)]},
 {id:"tajweed-p2-u06-l09-wasl-before-qata",n:9,ar:"همزة الوصل قبل همزة القطع",en:"Hamzah al-wasl before hamzah al-qata",pages:[65,66],defAr:"عند الابتداء بكلمة اجتمعت فيها همزة الوصل قبل همزة القطع يراعى أصل حركة همزة القطع والتحويل المنقول لتجنب اجتماع الهمزتين الثقيل.",defEn:"When beginning a word where hamzah al-wasl precedes hamzah al-qata, the fixed hamzah's original vowel and the transmitted transformation are observed to avoid a difficult double hamzah.",formula:"ابتداء: ٱ قبل ء → راع الحركة الأصلية والتحويل المنقول",condition:"Beginning a word with hamzah al-wasl immediately before hamzah al-qata",letters:["ٱؤ","ٱئ"],examples:[ex("ٱؤْتُمِنَ","Entrusted","ٱؤْ","وصل قبل قطع","The two hamzahs meet only when beginning.","Use the book's taught transformed start.",65),ex("ٱئْتُونِي","Bring to me","ٱئْ","وصل قبل قطع","The fixed hamzah has an original vowel context.","Follow the teacher-modeled starting form.",66)]},
 {id:"tajweed-p2-u06-l10-question-verbs",n:10,ar:"همزة الاستفهام قبل همزة الوصل في الأفعال",en:"Question hamzah before hamzah al-wasl in verbs",pages:[67,68],defAr:"إذا دخلت همزة الاستفهام على فعل مبدوء بهمزة وصل حذفت همزة الوصل لفظًا وخطًا في الأداء، وبقيت همزة الاستفهام مفتوحة ثم الحرف الساكن التالي.",defEn:"When question hamzah enters a verb beginning with hamzah al-wasl, the wasl hamzah is omitted and the open question hamzah remains before the following consonant.",formula:"أَ الاستفهام + ٱ فعل → حذف همزة الوصل",condition:"Question hamzah precedes hamzah al-wasl in a verb",letters:["أَ + ٱفعل"],examples:[ex("أَصْطَفَى","Did he choose?","أَصْ","استفهام قبل فعل","The verb's wasl hamzah is omitted after question hamzah.","Read open question hamzah directly into sad.",67),ex("أَتَّخَذْتُمْ","Did you take?","أَتَّ","استفهام قبل فعل","The connection removes the verb's wasl hamzah.","Preserve the following strengthened letter.",68)]},
 {id:"tajweed-p2-u06-l11-question-nouns",n:11,ar:"همزة الاستفهام قبل همزة الوصل في الأسماء",en:"Question hamzah before hamzah al-wasl in nouns",pages:[68,69],defAr:"إذا دخلت همزة الاستفهام على أل في الكلمات القرآنية المخصوصة لا تحذف همزة الوصل لئلا يلتبس الاستفهام بالخبر، بل تطبق أوجه المد أو التسهيل المنقولة.",defEn:"When question hamzah precedes أل in specified Qur'anic nouns, the wasl hamzah is retained in a transmitted transformed form so the question is not confused with a statement; taught madd or facilitation faces apply.",formula:"أَ الاستفهام + أل في المواضع الخاصة → مد/تسهيل منقول",condition:"Question hamzah precedes the definite article in a specified Qur'anic noun",letters:["ءَآلذَّكَرَيْنِ","ءَآللَّهُ","ءَآلْـَٰٔنَ"],examples:[ex("ءَآلذَّكَرَيْنِ","The two males?","ءَآل","استفهام مع أل","The transformed form preserves the question distinction.","Apply the teacher-selected transmitted face.",68),ex("ءَآللَّهُ","Is it Allah?","ءَآل","استفهام مع أل","The question must remain distinct from a statement.","Use madd or facilitation as taught.",69),ex("ءَآلْـَٰٔنَ","Now?","ءَآلْ","استفهام مع أل","This is a specified Qur'anic form.","Do not improvise the double-hamzah sound.",69)]},
 {id:"tajweed-p2-u06-l12-review",n:12,ar:"المراجعة الشاملة لهمزة الوصل",en:"Connecting hamzah cumulative review",pages:[49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69],defAr:"تجمع المراجعة التمييز بين الوصل والقطع، وحالة الابتداء والوصل، ونوع الكلمة، وحركة البدء، ثم صور اجتماع الهمزتين.",defEn:"The final review combines wasl/qata recognition, start/connection state, word category, starting vowel, and exceptional double-hamzah forms.",formula:"نوع الهمزة → ابتداء/وصل → نوع الكلمة → الحركة → اجتماع الهمزتين",condition:"All Part Two hamzah al-wasl contexts",letters:["ٱ","أ","إ","أل","أَ+ٱ"],examples:[ex("وَٱلْحَمْدُ","Connection","وَٱلْ","سقوط الوصل","Wasl drops after waw.","Connect directly.",69),ex("ٱدْخُلُوا","Verb start","خُ","بدء بالضم","Third-letter dammah is original.","Begin with dammah.",69),ex("ٱسْم","Noun start","ٱسْ","بدء بالكسر","Special noun.","Begin with kasrah.",69),ex("ءَآللَّهُ","Question form","ءَآل","وجه منقول","Question hamzah meets أل.","Use teacher-approved form.",69)],extra:[q("6 · Mixed","Wasl in connection is:",["Omitted","Always stressed","Lengthened"],"Omitted"),q("6 · Mixed","أل begins with:",["Fathah","Kasrah","Dammah"],"Fathah"),q("6 · Mixed","A verb with original third-letter dammah begins with:",["Dammah","Fathah","Sukoon"],"Dammah"),q("6 · Mixed","Exceptional double hamzah forms require:",["The transmitted taught face","Guessing","One universal deletion"],"The transmitted taught face")]},
];
export const part2Unit06Lessons=specs.map(make);
