const src = (pages, section) => ({
  book:"Tajweed Rules of the Qur'an — Part Two", pdf:"tajweed-rules_part-2.pdf",
  printedPages:pages, pdfPages:pages.map(p=>p+15), chapter:"A Brief Introduction to Grammar Terms", section,
  verification:"book chapter aligned; grammar is taught only as needed for hamzah al-wasl decisions",
});
const ex=(arabic,label,target,rule,why,how,page)=>({arabic,surah:{ar:"مثال تعليمي",en:label},ayah:"—",targetText:target,triggerLetter:target,previousLetter:"الكلمة المستهدفة",rule,teacherExplanation:why,readingInstruction:how,commonError:"Using translation alone instead of the word's Arabic form.",wordBoundary:"grammar-context",sourcePage:page,verificationStatus:"teacher-review-required"});
const q=(stage,prompt,items,answer)=>({stage,type:"grammar-decision",instruction:{en:"Choose the best answer."},prompt,items,acceptedAnswers:[answer],feedbackCorrect:"Correct.",feedbackIncorrect:"Check the word form and its grammatical sign."});
function make(s){
  const {id,n,ar,en,pages,defAr,defEn,formula,condition,terms,examples,extra=[]}=s;
  return {id,unitId:"part2-unit-05",lessonNumber:`5.${n}`,title:{ar,en},source:src(pages,en),contentOrigin:"book-source-and-instructional-design",level:"Part Two",estimatedMinutes:n===8?50:38,
    prerequisites:["Recognize Arabic vowel marks.","Read a short Arabic word.","Understand that grammar terms support recitation decisions."],
    learningOutcomes:[`Define ${en.toLowerCase()}.`,"Recognize the form in a Qur'anic word.","Use its sign in a later hamzah al-wasl decision.","Avoid confusing grammatical meaning with Tajweed sound.","Complete a mixed identification check."],
    definition:{linguistic:{ar:"تنقسم الكلمة العربية إلى اسم وفعل وحرف.",en:"Arabic words are classified as noun, verb, or particle."},technical:{ar:defAr,en:defEn},studentFriendly:{ar:defAr,en:defEn},memoryFormula:formula},
    keyTerms:terms.map(([a,t,e])=>({ar:a,transliteration:t,en:e})),teacherPreparation:["Prepare color-coded noun, verb, and particle cards.","Show the relevant sign, not full grammar analysis.","Connect every term to a future starting-vowel decision.","Use Qur'anic examples from the chapter."],
    openingReview:[{minutes:2,teacherPrompt:"Is this word a noun, verb, or particle?"},{minutes:2,teacherPrompt:"Which visible sign supports your answer?"}],
    conceptExplanation:[{audience:"student",text:defEn},{audience:"teacher",text:"Keep grammar functional: enough to select the correct hamzah al-wasl starting vowel."}],
    lessonPath:[{step:1,title:"Read",text:"Read the word and its vowels."},{step:2,title:"Find sign",text:"Locate tense, prefix, ending, or particle clue."},{step:3,title:"Classify",text:"Name noun, verb, or particle."},{step:4,title:"Explain",text:"State the evidence."},{step:5,title:"Connect",text:"Use the classification in recitation."}],
    visualExplanation:[{type:"rule-equation",display:formula,teacherUse:"Reveal word, sign, category, then recitation use."}],ruleSummary:{condition,result:defEn,location:"Arabic word structure needed for Part Two recitation rules.",letters:terms.map(x=>x[0])},
    letterGroups:[{name:{ar,en},letters:terms.map(x=>x[0])}],quranExamples:examples,
    guidedPractice:[{sequence:1,teacherAction:"Reveal one word.",studentAction:"Mark its sign and classify.",feedback:"Require evidence."},{sequence:2,teacherAction:"Ask how classification affects starting.",studentAction:"Connect grammar to recitation.",feedback:"Do not expand beyond the needed rule."}],
    oralPractice:[{cycle:["read","find sign","classify","explain","apply"],examplesRequired:examples.length,teacherObservation:["correct category","correct evidence","correct vowel reading"]}],
    interactiveActivities:[q("1 · Category","Arabic words divide into:",["Noun, verb, and particle","Heavy, light, and madd","Only nouns"],"Noun, verb, and particle"),q("2 · Trigger","What controls this lesson?",[condition,"English word order","Page color"],condition),q("3 · Evidence","How should classification be justified?",["By an Arabic form or sign","By guessing","By translation only"],"By an Arabic form or sign"),q("4 · Purpose","Why learn these terms here?",["To support hamzah al-wasl decisions","To replace Tajweed","To parse every verse fully"],"To support hamzah al-wasl decisions"),q("5 · Mastery","What confirms understanding?",["Correct mixed classification with evidence","Memorizing the title","Fast reading"],"Correct mixed classification with evidence"),...extra],
    commonMistakes:["Classifying from translation only.","Treating every prefixed word as a verb.","Confusing a command with present tense.","Learning unnecessary grammar detail."],correctionTechniques:["Circle the sign.","Contrast two forms of one root.","Use a noun/verb/particle sorting board.","Return immediately to the recitation consequence."],
    knowledgeChecks:[{type:"recognition",prompt:"Classify ten words.",success:"Eight correct with evidence."}],teacherQuestions:["What kind of word?","What is the sign?","Which form or tense?","How will this matter when starting?"],
    studentTasks:["Mark the sign.","Sort the word.","Explain the recitation use."],liveClassFlow:[{minutes:5,phase:"Review",display:"Noun / verb / particle"},{minutes:8,phase:"Definition",display:formula},{minutes:10,phase:"Sorting",display:"Word cards"},{minutes:10,phase:"Application",display:"Starting decisions"},{minutes:5,phase:"Exit",display:"Category and evidence"}],
    independentPractice:["Sort twelve teacher-approved words."],homework:["Prepare six words with category and evidence."],exitTicket:["Classify one word.","Name its sign.","Explain why it matters."],masteryCriteria:["Names the category.","Finds evidence.","Reads the word correctly.","Connects it to hamzah al-wasl."],
    teacherNotes:["This is functional grammar, not a complete grammar course."],sourceNotes:[`Uses printed pages ${pages.join(", ")}.`],verificationStatus:"source-aligned; teacher review required"};
}
const T={base:[["اسم","ism","noun"],["فعل","fi'l","verb"],["حرف","harf","particle"]]};
const specs=[
 {id:"tajweed-p2-u05-l01-purpose",n:1,ar:"أهمية مصطلحات النحو للتجويد",en:"Why grammar terms matter in Tajweed",pages:[43],defAr:"تساعد معرفة الاسم والفعل والحرف وزمن الفعل على اختيار حركة البدء بهمزة الوصل.",defEn:"Basic noun, verb, and particle recognition is needed to choose the correct starting vowel for hamzah al-wasl.",formula:"نوع الكلمة وصيغة الفعل → حركة البدء الصحيحة",condition:"The word category or verb form needed by a recitation rule",terms:T.base,examples:[ex("ٱهْدِنَا","Command form","ٱهْدِ","فعل أمر","The form guides the starting vowel.","Identify before starting.",43),ex("ٱسْم","Noun","ٱسْم","اسم","This belongs to a taught noun group.","Start according to the noun rule.",43)]},
 {id:"tajweed-p2-u05-l02-past",n:2,ar:"الفعل الماضي",en:"Past-tense verbs",pages:[44],defAr:"الفعل الماضي يدل على حدث وقع قبل زمن الكلام، وتظهر عليه علامات مثل تاء التأنيث الساكنة أو تاء الفاعل.",defEn:"A past-tense verb indicates a completed action and can accept signs such as feminine ta or subject ta.",formula:"حدث مضى + علامة ماضٍ = فعل ماضٍ",condition:"A completed-action form or a recognized past-tense sign",terms:[["فعل ماضٍ","fi'l madi","past verb"],["تاء التأنيث","ta at-ta'nith","feminine ta"],["تاء الفاعل","ta al-fa'il","subject ta"]],examples:[ex("قَالَ","He said","قَالَ","ماضٍ","The form reports a completed act.","Read its written vowels.",44),ex("قَالَتْ","She said","تْ","ماضٍ","Feminine sakin ta marks past tense.","Keep final ta sakin.",44)]},
 {id:"tajweed-p2-u05-l03-present",n:3,ar:"الفعل المضارع",en:"Present-tense verbs",pages:[45],defAr:"الفعل المضارع يدل على الحال أو الاستقبال، ويبدأ غالبًا بأحد أحرف نأتي: ن، أ، ت، ي.",defEn:"A present-tense verb indicates current or future action and commonly begins with one of ن أ ت ي.",formula:"ن أ ت ي في أول صيغة الفعل → مضارع غالبًا",condition:"A verb form beginning with a present-tense prefix and indicating current/future action",terms:[["مضارع","mudari'","present verb"],["نأتي","na'ti","prefix mnemonic"],["حرف المضارعة","harf al-mudara'ah","present prefix"]],examples:[ex("يَعْلَمُ","He knows","يَ","مضارع","Ya is the present prefix.","Do not classify from ya alone; confirm the form.",45),ex("نَعْبُدُ","We worship","نَ","مضارع","Nun marks first-person plural present.","Read the short vowel accurately.",45)]},
 {id:"tajweed-p2-u05-l04-command",n:4,ar:"فعل الأمر",en:"Command verbs",pages:[46],defAr:"فعل الأمر يطلب حدوث الفعل، ويؤخذ غالبًا من المضارع بعد حذف حرف المضارعة، وقد يبدأ بهمزة وصل.",defEn:"A command verb requests an action, often derived from the present form after removing its prefix, and may begin with hamzah al-wasl.",formula:"مضارع → حذف حرف المضارعة → صيغة أمر",condition:"A form requesting an action, often beginning with hamzah al-wasl",terms:[["أمر","amr","command"],["اِفْعَل","if'al","command pattern"],["همزة الوصل","hamzah al-wasl","connecting hamzah"]],examples:[ex("ٱقْرَأْ","Read!","ٱقْرَأْ","أمر","The word requests an action.","Start with the taught kasrah.",46),ex("ٱدْخُلُوا","Enter!","ٱدْخُلُوا","أمر","The command's third letter helps choose the starting vowel.","Inspect the original vowel.",46)]},
 {id:"tajweed-p2-u05-l05-verb-structure",n:5,ar:"البنية الأساسية للأفعال",en:"Essential structure of verbs",pages:[46,47],defAr:"تمييز الحروف الأصلية والزوائد وصيغة الماضي والمضارع والأمر يساعد على معرفة الحرف الثالث وحركته الأصلية عند البدء.",defEn:"Recognizing root structure, additions, and tense forms helps identify the relevant third letter and its original vowel when beginning a verb.",formula:"الصيغة + الحروف الأصلية + حركة الثالث → قرار البدء",condition:"The original verb structure and the vowel of its relevant third letter",terms:[["جذر","jذر","root"],["أصلي","asli","original"],["زائد","za'id","additional"]],examples:[ex("يَدْخُلُ → ٱدْخُلْ","Present to command","خُ","بنية الفعل","The dammah is original in the relevant form.","Use it for the starting decision.",47),ex("يَضْرِبُ → ٱضْرِبْ","Present to command","رِ","بنية الفعل","Kasrah guides the command start.","Begin with kasrah.",47)]},
 {id:"tajweed-p2-u05-l06-nouns",n:6,ar:"الأسماء وعلاماتها",en:"Nouns and their signs",pages:[47,48],defAr:"الاسم يدل على معنى غير مقترن بزمن، ومن علاماته الجر والتنوين ودخول أل والنداء.",defEn:"A noun carries meaning without tense; signs include genitive case, tanween, the definite article, and vocative use.",formula:"جر أو تنوين أو أل أو نداء → علامة اسم",condition:"A recognized noun sign such as tanween, أل, genitive marking, or vocative use",terms:[["اسم","ism","noun"],["تنوين","tanween","nunation"],["أل","al","definite article"],["جر","jarr","genitive"]],examples:[ex("كِتَابٌ","Tanween noun","ٌ","اسم","Tanween is a noun sign.","Read tanween according to context.",48),ex("ٱلْكِتَابُ","Definite noun","ٱلْ","اسم","أل enters nouns.","Recognize hamzah al-wasl in the article.",48)]},
 {id:"tajweed-p2-u05-l07-particles",n:7,ar:"الحروف وحروف الجر",en:"Particles and prepositions",pages:[48],defAr:"الحرف كلمة لا يظهر معناها كاملًا إلا مع غيرها، ومنه حروف الجر التي تدخل على الأسماء.",defEn:"A particle expresses its function with another word; prepositions are particles that govern nouns.",formula:"حرف جر + اسم = تركيب يثبت نوع الكلمتين",condition:"A fixed particle form, especially a preposition followed by a noun",terms:[["حرف","harf","particle"],["حرف جر","harf jarr","preposition"],["مِن","min","from"],["إِلَى","ila","to"]],examples:[ex("مِنَ ٱلنَّاسِ","Preposition and noun","مِنَ","حرف جر","Min is a preposition before a noun.","Classify each word separately.",48),ex("فِي ٱلْأَرْضِ","In the earth","فِي","حرف جر","Fi is a preposition.","Use the noun context after it.",48)]},
 {id:"tajweed-p2-u05-l08-review",n:8,ar:"مراجعة مصطلحات النحو",en:"Grammar terms review",pages:[43,44,45,46,47,48],defAr:"تجمع المراجعة التمييز بين الاسم والفعل والحرف، وبين الماضي والمضارع والأمر، ثم توظف ذلك في قرارات همزة الوصل.",defEn:"The review distinguishes noun, verb, and particle; separates past, present, and command forms; and applies the result to hamzah al-wasl preparation.",formula:"الكلمة → النوع → الصيغة/العلامة → أثرها في البدء",condition:"Mixed word-category and verb-form identification",terms:T.base,examples:[ex("ٱقْرَأْ","Command","ٱقْرَأْ","فعل أمر","It requests an action.","Connect classification to starting vowel.",48),ex("ٱسْمُ","Noun","ٱسْم","اسم","It belongs to the noun category.","Apply the taught noun start.",48),ex("مِنَ","Particle","مِنَ","حرف","It functions with the following noun.","Do not call it a verb.",48)],extra:[q("6 · Mixed","يَعْلَمُ is:",["Present verb","Past verb","Noun"],"Present verb"),q("6 · Mixed","Tanween is commonly a sign of:",["A noun","A command","Every particle"],"A noun"),q("6 · Mixed","ٱقْرَأْ is:",["A command","A noun","Past tense"],"A command")]},
];
export const part2Unit05Lessons=specs.map(make);
