const source = (pages, section) => ({
  book: "Tajweed Rules of the Qur'an — Part Two",
  pdf: "tajweed-rules_part-2.pdf",
  pdfPages: pages.map((page) => page + 9),
  printedPages: pages,
  chapter: "The Accent in Recitation of the Glorious Qur'an",
  section,
  verification: "visually aligned to the scanned book; sound placement requires qualified-teacher review",
});

const example = (arabic, label, target, explanation, instruction, page, boundary = "within-word") => ({
  arabic,
  surah: { ar: "مثال من الكتاب", en: label },
  ayah: "—",
  targetText: target,
  triggerLetter: target,
  previousLetter: "موضع النبر",
  rule: "النبر · Accent",
  teacherExplanation: explanation,
  readingInstruction: instruction,
  commonError: "Making the accent so strong that it creates a new vowel, or omitting the intended letter.",
  wordBoundary: boundary,
  sourcePage: page,
  verificationStatus: "teacher-review-required",
});

const activity = (stage, prompt, items, answer, correct = "Correct.", incorrect = "Return to the accent trigger.") => ({
  stage,
  type: "accent-decision",
  instruction: { en: "Choose the best answer." },
  prompt,
  items,
  acceptedAnswers: [answer],
  feedbackCorrect: correct,
  feedbackIncorrect: incorrect,
});

function makeLesson(spec) {
  const { id, n, ar, en, pages, definitionAr, definitionEn, formula, condition, letters, examples, extra = [] } = spec;
  return {
    id,
    unitId: "part2-unit-01",
    lessonNumber: `1.${n}`,
    title: { ar, en },
    source: source(pages, en),
    contentOrigin: "book-source-and-instructional-design",
    level: "Part Two",
    estimatedMinutes: n === 5 ? 50 : 45,
    prerequisites: [
      "Complete Part One foundations.",
      "Distinguish shaddah, sukoon, madd, and leen.",
      "Stop on a word without adding a vowel.",
    ],
    learningOutcomes: [
      "Define accent as a controlled increase of audible pressure.",
      "Recognize the lesson's accent circumstance.",
      "Explain why the accent protects the intended letter or meaning.",
      "Apply it without creating a new vowel or excessive force.",
      "Pass two teacher-observed attempts.",
    ],
    definition: {
      linguistic: {
        ar: "النبر هو إبراز جزء أو حرف من الكلمة بضغط صوتي يسير يجعله أوضح مما جاوره.",
        en: "Accent is slight audible pressure on a specific part or letter so it is clearer than adjacent sounds.",
      },
      technical: { ar: definitionAr, en: definitionEn },
      studentFriendly: {
        ar: "أظهر الحرف المقصود بوضوح، من غير صياح ولا حركة جديدة.",
        en: "Make the intended letter clearly audible without shouting or adding a new vowel.",
      },
      memoryFormula: formula,
    },
    keyTerms: [
      { ar: "النبر", transliteration: "an-nabr", en: "controlled audible accent" },
      { ar: "الضغط الصوتي", transliteration: "ad-daght as-sawti", en: "slight vocal pressure" },
      { ar: "الشدة", transliteration: "ash-shaddah", en: "a doubled or strengthened letter" },
      { ar: "الوقف", transliteration: "al-waqf", en: "stopping" },
    ],
    teacherPreparation: [
      "Model the word once without the needed accent and once correctly.",
      "Keep volume separate from accent; the goal is clarity, not loudness.",
      "Mark the protected letter and explain what could otherwise be lost.",
      "Use book examples before adding other examples.",
    ],
    openingReview: [
      { minutes: 2, teacherPrompt: "Find the shaddah, madd, leen, or dual marker." },
      { minutes: 2, teacherPrompt: "Are we connecting or stopping?" },
    ],
    conceptExplanation: [
      { audience: "student", text: definitionEn },
      { audience: "teacher", text: "Judge accent by the preserved letter and natural word shape, not by raw loudness." },
    ],
    lessonPath: [
      { step: 1, title: "Find", text: "Locate the accent circumstance." },
      { step: 2, title: "Protect", text: "Name the letter or meaning that could be lost." },
      { step: 3, title: "Place", text: "Put slight pressure on the correct location." },
      { step: 4, title: "Avoid", text: "Do not create a vowel, madd, or harsh break." },
      { step: 5, title: "Recite", text: "Read the complete word or phrase naturally." },
    ],
    visualExplanation: [{ type: "rule-equation", display: formula, teacherUse: "Reveal trigger, protected feature, and accent location." }],
    ruleSummary: {
      condition,
      result: definitionEn,
      location: "At the marked circumstance in connected reading or stopping.",
      letters,
    },
    letterGroups: [
      { name: { ar: "موضع النبر", en: "Accent target" }, letters },
      { name: { ar: "الهدف", en: "Goal" }, letters: ["وضوح", "بلا حركة زائدة"] },
    ],
    quranExamples: examples,
    guidedPractice: [
      {
        sequence: 1,
        teacherAction: "Contrast a weak production with the intended accent.",
        studentAction: "Identify what became unclear.",
        feedback: "Name the protected letter or grammatical meaning.",
      },
      {
        sequence: 2,
        teacherAction: "Model the complete word in context.",
        studentAction: "Imitate, record, and compare.",
        feedback: "Reduce excess force while preserving clarity.",
      },
    ],
    oralPractice: [{
      cycle: ["find trigger", "name purpose", "place accent", "check for added sound", "recite in context"],
      examplesRequired: examples.length,
      teacherObservation: ["correct location", "clear protected letter", "no added vowel", "natural continuation or stop"],
    }],
    interactiveActivities: [
      activity("1 · Meaning", "What is accent in this chapter?", ["Slight pressure that makes a target clearer", "A full extra vowel", "Always raising the entire verse"], "Slight pressure that makes a target clearer"),
      activity("2 · Trigger", "What must be identified first?", [condition, "The English translation only", "The longest word"], condition),
      activity("3 · Purpose", "Why is accent used here?", ["To protect a letter or meaning from being lost", "To make every word louder", "To replace Tajweed rules"], "To protect a letter or meaning from being lost"),
      activity("4 · Error", "Which result is incorrect?", ["Creating a new vowel", "Keeping the intended letter clear", "Using slight controlled pressure"], "Creating a new vowel"),
      activity("5 · Mastery", "How is correct accent confirmed?", ["Teacher-observed recitation in context", "A visual quiz alone", "Maximum loudness"], "Teacher-observed recitation in context"),
      ...extra,
    ],
    commonMistakes: [
      "Confusing accent with shouting.",
      "Adding fathah, dammah, or kasrah.",
      "Breaking the word unnaturally.",
      "Applying accent to every shaddah or madd without checking the circumstance.",
    ],
    correctionTechniques: [
      "Clap once at the intended location, then recite without clapping.",
      "Contrast weak, exaggerated, and balanced production.",
      "Mark the protected letter in a second color.",
      "Record at normal volume and listen for clarity.",
    ],
    knowledgeChecks: [
      { type: "recognition", prompt: "Classify eight samples.", success: "At least seven correct with purpose." },
      { type: "recitation", prompt: "Recite four book examples.", success: "Two consecutive teacher-approved attempts." },
    ],
    teacherQuestions: ["Where is the accent?", "What could be lost?", "Are we connecting or stopping?", "Did a new vowel appear?"],
    studentTasks: ["Mark the target.", "Explain the purpose.", "Recite and compare two attempts."],
    liveClassFlow: [
      { minutes: 5, phase: "Review", display: "Shaddah, madd, leen, stop" },
      { minutes: 8, phase: "Meaning", display: formula },
      { minutes: 10, phase: "Teacher contrast", display: "Weak / balanced / excessive" },
      { minutes: 10, phase: "Book examples", display: "Find and protect" },
      { minutes: 8, phase: "Recitation", display: "Teacher listening" },
      { minutes: 4, phase: "Exit", display: "Location and purpose" },
    ],
    independentPractice: ["Record three book examples and mark the accent target."],
    homework: ["Prepare three examples with trigger, purpose, and stopping/connection context."],
    exitTicket: ["Point to the accent.", "Explain its purpose.", "Recite without an added vowel."],
    masteryCriteria: ["Locates the accent.", "Explains what it protects.", "Avoids added vowels.", "Uses natural controlled pressure.", "Passes two attempts."],
    teacherNotes: [
      "Accent is a practical sound topic and must not be reduced to text memorization.",
      "Avoid presenting every stress pattern as equally strong.",
    ],
    sourceNotes: [`Uses printed pages ${pages.join(", ")} (PDF pages ${pages.map((page) => page + 9).join(", ")}).`, "Activities are instructional-design additions."],
    verificationStatus: "source-aligned; qualified-teacher sound review required",
  };
}

const specs = [
  {
    id: "tajweed-p2-u01-l01-stop-shaddah",
    n: 1,
    ar: "النبر عند الوقف على الحرف المشدد",
    en: "Accent and stopping on a strengthened letter",
    pages: [1, 2],
    definitionAr: "عند الوقف على حرف مشدد يبقى في السماع ما يدل على أن أصله حرفان، فيوضع نبر لطيف على الحرف الأخير حتى لا يبدو كحرف واحد ضعيف، عدا النون والميم المشددتين إذ تدل الغنة الكاملة عليهما.",
    definitionEn: "When stopping on a strengthened final letter, a controlled accent helps the listener perceive its doubled origin; strengthened nun and mim are distinguished by their complete ghunnah.",
    formula: "وقف + حرف مشدد → نبر لطيف يحفظ أثر الحرفين",
    condition: "Stopping on a final strengthened letter",
    letters: ["ـّْ", "وقف"],
    examples: [
      example("مُسْتَقَرٌّ", "Stopping on strengthened ra", "رّ", "Stopping reduces the written shaddah to one audible sakin articulation, so accent preserves its doubled origin.", "Stop with a clear controlled ra without adding a vowel.", 1),
      example("ٱلْحَيُّ", "Stopping on strengthened ya", "يّ", "The accent prevents the final strengthened ya from sounding like a weak single consonant.", "Keep the final ya clear and sakin.", 1),
      example("مُسْتَمِرٌّ", "Stopping on strengthened ra", "رّ", "A slight accent signals the original two-letter structure.", "Avoid excessive repetition of ra.", 1),
    ],
  },
  {
    id: "tajweed-p2-u01-l02-ya-waw",
    n: 2,
    ar: "النبر مع الياء والواو المشددتين",
    en: "Accent with strengthened ya and waw",
    pages: [3],
    definitionAr: "ينبر على الياء أو الواو المشددتين في المواضع المبينة حتى لا يظن السامع أن قبلهما حرف مد أو أن زمنهما قد طال، وخاصة عند مجاورتهما لحركة من جنسهما أو للفتح.",
    definitionEn: "Strengthened ya and waw receive controlled accent in the taught settings so they are not mistaken for madd or lengthened beyond their consonantal structure.",
    formula: "يّ أو وّ + احتمال توهم المد → نبر يقطع زمن المد",
    condition: "A strengthened ya or waw where a madd-like sound could be mistakenly created",
    letters: ["يّ", "وّ"],
    examples: [
      example("ٱلْقُوَّةَ", "Strengthened waw after dammah", "وَّ", "The accent prevents the waw from being stretched as madd.", "Give the doubled waw its consonantal contact without a long vowel.", 3),
      example("شَرْقِيَّةٍ", "Strengthened ya after kasrah", "يَّ", "The accent distinguishes strengthened ya from ya madd.", "Keep the ya doubled and short.", 3),
      example("قَوَّامِينَ", "Strengthened waw after fathah", "وَّ", "The accent protects against turning the consonantal waw into a lengthened sound.", "Use slight pressure at the doubled waw.", 3),
    ],
  },
  {
    id: "tajweed-p2-u01-l03-after-madd",
    n: 3,
    ar: "النبر بعد حرف المد",
    en: "Accent after a madd letter",
    pages: [4],
    definitionAr: "عند الانتقال من حرف المد إلى الحرف الأول الساكن من المشدد يُنبر على الحرف المشدد ليظهر التصادم الصحيح ولا يضعف الحرف أو يسقط من السماع.",
    definitionEn: "When moving from madd into the first sakin component of a strengthened letter, accent makes the collision clear so the strengthened consonant is not weakened or lost.",
    formula: "حرف مد → حرف مشدد = نبر عند الانتقال يحفظ الساكن",
    condition: "Moving from a madd letter into a strengthened consonant",
    letters: ["مد", "ـّ"],
    examples: [
      example("ٱلضَّآلِّينَ", "Madd into strengthened lam", "آلّ", "After the madd, the first lam of the shaddah is sakin and needs a clear collision.", "Complete the madd count, then place controlled pressure on lam.", 4),
      example("دَآبَّةٍ", "Madd into strengthened ba", "آبّ", "The accent prevents the first ba component from disappearing after madd.", "Move from the open madd into firm lip closure.", 4),
    ],
  },
  {
    id: "tajweed-p2-u01-l04-final-hamzah",
    n: 4,
    ar: "النبر على الهمزة المتطرفة بعد المد أو اللين",
    en: "Accent on final hamzah after madd or leen",
    pages: [4],
    definitionAr: "عند الوقف على همزة متطرفة قبلها حرف مد أو لين ينبر على الهمزة حتى لا تضيع بعد انشغال الفم بصوت المد أو اللين، مع مراعاة أحكام الوقف على تنوين الفتح.",
    definitionEn: "When stopping on final hamzah preceded by madd or leen, accent keeps the hamzah audible after the flowing sound, while observing the separate rule for fathatayn endings.",
    formula: "مد أو لين + همزة متطرفة + وقف → نبر يحفظ الهمزة",
    condition: "Stopping on final hamzah after a madd or leen letter",
    letters: ["آء", "وْء", "يْء"],
    examples: [
      example("ٱلسَّمَآءُ", "Final hamzah after madd", "آء", "The mouth moves through madd before reaching final hamzah.", "At stopping, make hamzah clearly audible without a new vowel.", 4),
      example("سُوٓءٌ", "Final hamzah after waw madd", "وٓء", "Accent prevents hamzah from disappearing after the long waw sound.", "Finish the madd, then articulate hamzah cleanly.", 4),
      example("شَيْءٌ", "Final hamzah after leen", "يْء", "The leen transition can obscure final hamzah at stopping.", "Preserve hamzah with controlled pressure.", 4),
    ],
  },
  {
    id: "tajweed-p2-u01-l05-dual-verbs",
    n: 5,
    ar: "النبر في أفعال التثنية الخاصة",
    en: "Accent in special dual-form verbs",
    pages: [5],
    definitionAr: "ينبر في ثلاثة أفعال ماضية مثناة عند وصلها بما بعدها؛ لأن ألف التثنية حذفت منعًا لالتقاء الساكنين، فيحفظ النبر دلالة الاثنين حتى لا يتوهم السامع الإفراد.",
    definitionEn: "In three specific dual past-tense verbs, accent is used during connection because the dual alif is dropped before the next sakin sound; the accent preserves the meaning of two subjects.",
    formula: "فعل ماضٍ مثنى + وصل يسقط ألف التثنية → نبر يحفظ معنى الاثنين",
    condition: "Connecting one of the three specified dual verbs to the following word",
    letters: ["ذَاقَا", "ٱسْتَبَقَا", "قَالَا"],
    examples: [
      example("ذَاقَا ٱلشَّجَرَةَ", "The two tasted", "قَا ٱل", "The dual alif is not pronounced in connection before the following sakin lam.", "Use accent to preserve the audible sense of the dual form.", 5, "across-two-words"),
      example("وَٱسْتَبَقَا ٱلْبَابَ", "The two raced", "قَا ٱل", "Without accent, the connected verb may be heard as singular.", "Connect naturally while preserving the dual indication.", 5, "across-two-words"),
      example("وَقَالَا ٱلْحَمْدُ لِلَّهِ", "The two said", "لَا ٱل", "The accent indicates the dropped dual alif in connected reading.", "Use the accent only in connection; the reason disappears when stopping.", 5, "across-two-words"),
    ],
    extra: [
      activity("6 · Context", "When is the special dual-form accent needed?", ["During connection to the following word", "Whenever stopping on the verb", "In every dual noun"], "During connection to the following word"),
      activity("6 · Meaning", "What meaning does the accent protect?", ["Two subjects performed the action", "A feminine plural", "A command"], "Two subjects performed the action"),
    ],
  },
];

export const part2Unit01Lessons = specs.map(makeLesson);
