const source = (pages, section) => ({
  book: "Tajweed Rules of the Qur'an — Part Two",
  pdf: "tajweed-rules_part-2.pdf",
  pdfPages: pages.map((page) => page + 9),
  printedPages: pages,
  chapter: "The Characteristics of Letters",
  section,
  verification: "aligned to the book chapter and standard Hafs terminology; sound quality requires teacher review",
});

const ex = (arabic, label, target, quality, why, how, page) => ({
  arabic,
  surah: { ar: "مثال تعليمي", en: label },
  ayah: "—",
  targetText: target,
  triggerLetter: target,
  previousLetter: "الحرف المستهدف",
  rule: quality,
  teacherExplanation: why,
  readingInstruction: how,
  commonError: "Losing the characteristic or exaggerating it until the letter changes.",
  wordBoundary: "within-one-word",
  sourcePage: page,
  verificationStatus: "teacher-review-required",
});

const quiz = (stage, prompt, items, answer, correct = "Correct.", incorrect = "Review the letter group and sound effect.") => ({
  stage,
  type: "sifat-decision",
  instruction: { en: "Choose the best answer." },
  prompt,
  items,
  acceptedAnswers: [answer],
  feedbackCorrect: correct,
  feedbackIncorrect: incorrect,
});

function make(spec) {
  const {
    id, n, ar, en, pages, definitionAr, definitionEn, formula, condition,
    letters, opposite = "No direct opposite in this lesson", examples, extra = [],
  } = spec;
  return {
    id,
    unitId: "part2-unit-02",
    lessonNumber: `2.${n}`,
    title: { ar, en },
    source: source(pages, en),
    contentOrigin: "book-source-and-instructional-design",
    level: "Part Two",
    estimatedMinutes: n === 16 ? 55 : 42,
    prerequisites: [
      "Recall the articulation point of each target letter.",
      "Produce a sakin letter using the makhraj test.",
      "Distinguish a letter's articulation point from its characteristics.",
    ],
    learningOutcomes: [
      `Define ${en.toLowerCase()}.`,
      "Name the letters carrying the characteristic.",
      "Explain its audible or airflow effect.",
      `Contrast it with ${opposite}.`,
      "Produce teacher-approved examples without exaggeration.",
    ],
    definition: {
      linguistic: {
        ar: "الصفة هي الكيفية الملازمة لصوت الحرف عند خروجه من مخرجه.",
        en: "A characteristic describes how a letter sounds when it emerges from its articulation point.",
      },
      technical: { ar: definitionAr, en: definitionEn },
      studentFriendly: { ar: definitionAr, en: definitionEn },
      memoryFormula: formula,
    },
    keyTerms: [
      { ar: "الصفة", transliteration: "as-sifah", en: "letter characteristic" },
      { ar: "المخرج", transliteration: "al-makhraj", en: "articulation point" },
      { ar, transliteration: en, en: definitionEn },
      { ar: "الضد", transliteration: "ad-didd", en: opposite },
    ],
    teacherPreparation: [
      "Prepare sakin-letter contrasts from the same or nearby articulation areas.",
      "Model the characteristic once correctly and once with a controlled error.",
      "Separate the physical cause from the audible result.",
      "Assess at normal recitation speed after isolation practice.",
    ],
    openingReview: [
      { minutes: 2, teacherPrompt: "Where is the letter articulated?" },
      { minutes: 2, teacherPrompt: "What changes when the articulation remains the same but the quality changes?" },
    ],
    conceptExplanation: [
      { audience: "student", text: definitionEn },
      { audience: "teacher", text: `Teach the sound effect of ${condition}; do not accept memorized letter lists without production.` },
    ],
    lessonPath: [
      { step: 1, title: "Locate", text: "Produce the letter from its correct articulation point." },
      { step: 2, title: "Observe", text: "Notice airflow, voice, pressure, or tongue position." },
      { step: 3, title: "Name", text: "State the characteristic and its opposite if present." },
      { step: 4, title: "Contrast", text: "Compare a target letter with a neighboring group." },
      { step: 5, title: "Recite", text: "Preserve the characteristic naturally in context." },
    ],
    visualExplanation: [{ type: "rule-equation", display: formula, teacherUse: "Point to the physical state, sound result, then letters." }],
    ruleSummary: {
      condition,
      result: definitionEn,
      location: "The characteristic accompanies its letters whenever they are correctly articulated.",
      letters,
    },
    letterGroups: [
      { name: { ar, en }, letters },
      { name: { ar: "المقابل", en: "Contrast" }, letters: [opposite] },
    ],
    quranExamples: examples,
    guidedPractice: [
      {
        sequence: 1,
        teacherAction: "Model the target and contrast in isolation.",
        studentAction: "Identify the audible difference.",
        feedback: "Correct the makhraj before adjusting the characteristic.",
      },
      {
        sequence: 2,
        teacherAction: "Place the sound in a word.",
        studentAction: "Recite, record, and compare.",
        feedback: "Reduce exaggeration while preserving the defining effect.",
      },
    ],
    oralPractice: [{
      cycle: ["makhraj", "physical state", "sound effect", "contrast", "context"],
      examplesRequired: examples.length,
      teacherObservation: ["correct makhraj", "correct characteristic", "clear contrast", "no exaggeration"],
    }],
    interactiveActivities: [
      quiz("1 · Meaning", "What is a letter characteristic?", ["How the letter sounds at its makhraj", "The letter's written color", "The verse number"], "How the letter sounds at its makhraj"),
      quiz("2 · Letters", "Which set belongs to this lesson?", [letters.join(" "), "ء ه ع ح غ خ only", "ا و ي only"], letters.join(" ")),
      quiz("3 · Condition", "What should be observed?", [condition, "Translation length", "Page layout"], condition),
      quiz("4 · Contrast", "What is the taught contrast?", [opposite, "Every letter is identical", "No listening is needed"], opposite),
      quiz("5 · Mastery", "What confirms mastery?", ["Correct teacher-observed sound in context", "Memorizing the title only", "Maximum force"], "Correct teacher-observed sound in context"),
      ...extra,
    ],
    commonMistakes: [
      "Memorizing the letters without producing the sound.",
      "Changing the articulation point to imitate the characteristic.",
      "Exaggerating the effect.",
      "Dropping the characteristic during connected recitation.",
    ],
    correctionTechniques: [
      "Use the sakin-letter test.",
      "Contrast two letters with nearby articulation.",
      "Separate airflow, voice, and tongue-position checks.",
      "Move gradually from isolation to a complete phrase.",
    ],
    knowledgeChecks: [
      { type: "recognition", prompt: "Classify ten letters or samples.", success: "At least eight correct with a reason." },
      { type: "recitation", prompt: "Recite a mixed set.", success: "Two teacher-approved attempts." },
    ],
    teacherQuestions: ["Where is the makhraj?", "What happens to airflow or voice?", "What is the opposite?", "Did the letter change?"],
    studentTasks: ["Sort the letters.", "Describe the sound effect.", "Recite a contrast pair."],
    liveClassFlow: [
      { minutes: 5, phase: "Makhraj review", display: "Target letters" },
      { minutes: 8, phase: "Definition", display: formula },
      { minutes: 10, phase: "Sound contrast", display: "Target / opposite" },
      { minutes: 10, phase: "Book examples", display: "Identify and explain" },
      { minutes: 7, phase: "Recitation", display: "Teacher listening" },
      { minutes: 4, phase: "Exit", display: "Name and produce" },
    ],
    independentPractice: ["Record five target letters in isolation and in words."],
    homework: ["Prepare four examples with letter, characteristic, opposite, and sound effect."],
    exitTicket: ["Name the characteristic.", "Name its letters.", "Produce one correct contrast."],
    masteryCriteria: ["Defines the quality.", "Sorts its letters.", "Explains the sound effect.", "Avoids exaggeration.", "Passes two attempts."],
    teacherNotes: ["Characteristics refine a correct makhraj; they do not replace it.", "Use qualified listening for performance decisions."],
    sourceNotes: [`Uses printed pages ${pages.join(", ")}.`, "Practice sequencing is an instructional-design addition."],
    verificationStatus: "source-aligned; qualified-teacher sound review required",
  };
}

const specs = [
  {
    id:"tajweed-p2-u02-l01-meaning",n:1,ar:"معنى صفات الحروف وأقسامها",en:"Meaning and categories of letter characteristics",pages:[6],
    definitionAr:"صفات الحروف كيفيات تعرض للحرف عند النطق به، وتميز الحروف المشتركة في المخرج، وتنقسم إلى صفات لها ضد وصفات لا ضد لها.",
    definitionEn:"Letter characteristics are sound qualities that distinguish letters, especially those sharing an articulation point; they divide into qualities with opposites and qualities without opposites.",
    formula:"مخرج الحرف + صفاته = هويته الصوتية",condition:"The sound behavior accompanying a correctly articulated letter",letters:["صفات لها ضد","صفات لا ضد لها"],opposite:"The two main categories",
    examples:[ex("ط / ت","Shared area, different qualities","ط","صفات الحروف","Nearby articulation does not make the sounds identical.","Compare heaviness, pressure, and airflow.",6),ex("ظ / ذ","Distinct qualities","ظ","صفات الحروف","Characteristics preserve each letter's identity.","Keep the makhraj, then hear the quality difference.",6)],
  },
  {
    id:"tajweed-p2-u02-l02-categories",n:2,ar:"الصفات التي لها ضد والتي لا ضد لها",en:"Characteristics with and without opposites",pages:[7],
    definitionAr:"الصفات المتضادة تغطي جميع الحروف في أزواج أو مجموعات مقابلة، أما الصفات التي لا ضد لها فتختص بحروف معينة دون أن يقابلها وصف مسمى في بقية الحروف.",
    definitionEn:"Opposed characteristics classify every letter between named contrasts, while non-opposed characteristics belong to selected letters without a named opposite category.",
    formula:"له ضد: الحرف في أحد طرفين | لا ضد له: صفة خاصة",condition:"Whether the characteristic has a named opposite covering the remaining letters",letters:["همس/جهر","شدة/رخاوة","استعلاء/استفال","إطباق/انفتاح"],opposite:"Qualities without named opposites",
    examples:[ex("س / ز","Whisper and apparent sound","س","صفات متضادة","The pair illustrates named opposite airflow/voice behavior.","Compare with a sakin test.",7),ex("ص","Whistling","ص","صفة بلا ضد","Whistling belongs to a selected set.","Hear the narrow-channel sound without inventing an opposite.",7)],
  },
  {
    id:"tajweed-p2-u02-l03-hams-jahr",n:3,ar:"الهمس والجهر",en:"Whisper and apparent sound",pages:[8],
    definitionAr:"الهمس جريان النفس عند النطق بالحرف لضعف الاعتماد على المخرج، وحروفه فحثه شخص سكت. والجهر انحباس جريان النفس لقوة الاعتماد، وهو في باقي الحروف.",
    definitionEn:"Hams allows breath to flow because articulation pressure is lighter; its letters are ف ح ث ه ش خ ص س ك ت. Jahr restrains breath through firmer articulation and belongs to the remaining letters.",
    formula:"فحثه شخص سكت = همس | باقي الحروف = جهر",condition:"Whether breath flows noticeably during the sakin letter",letters:["ف","ح","ث","ه","ش","خ","ص","س","ك","ت"],opposite:"Jahr · apparent/voiced restraint of breath",
    examples:[ex("أَسْ","Whispered sin","سْ","الهمس","Breath continues through the narrow passage.","Keep audible breath without turning it into extra vowel.",8),ex("أَزْ","Jahr contrast","زْ","الجهر","Breath is restrained while voice remains apparent.","Contrast with sin at the same general area.",8),ex("أَكْ","Whispered kaf","كْ","الهمس","A breath release follows the articulation.","Avoid exaggerated aspiration.",8)],
  },
  {
    id:"tajweed-p2-u02-l04-shiddah",n:4,ar:"الشدة والتوسط والرخاوة",en:"Strength, in-between, and softness",pages:[9],
    definitionAr:"الشدة انحباس جريان الصوت وحروفها أجد قط بكت، والرخاوة جريان الصوت، والتوسط اعتدال بينهما وحروفه لن عمر.",
    definitionEn:"Shiddah blocks sound flow in أجد قط بكت; rikhawah allows sound to flow; tawassut is the middle state in لن عمر.",
    formula:"أجد قط بكت = شدة | لن عمر = توسط | الباقي = رخاوة",condition:"Whether the sound is blocked, partially sustained, or freely flowing",letters:["ء","ج","د","ق","ط","ب","ك","ت"],opposite:"Rikhawah, with tawassut between the two",
    examples:[ex("أَقْ","Strong qaf","قْ","الشدة","Sound is blocked at the articulation point.","Release correctly without adding a vowel.",9),ex("أَلْ","Moderate lam","لْ","التوسط","Sound is neither fully blocked nor freely prolonged.","Allow controlled partial flow.",9),ex("أَسْ","Soft sin","سْ","الرخاوة","Sound can flow through the narrow channel.","Sustain only enough to hear the quality.",9)],
  },
  {
    id:"tajweed-p2-u02-l05-effects",n:5,ar:"آثار الشدة والتوسط والرخاوة",en:"Effects of strength, moderation, and softness",pages:[9,10,11],
    definitionAr:"تؤثر هذه الصفات في زمن الحرف ووضوحه عند السكون؛ فحرف الشدة يحتاج تحريرًا بعد انحباس الصوت، والمتوسط زمنه بينهما، والرخو يجري صوته بلا مبالغة.",
    definitionEn:"These qualities affect how a sakin letter is completed and timed: strong letters require a clear release after blockage, moderate letters have controlled partial flow, and soft letters allow sound flow without exaggeration.",
    formula:"انحباس → تحرير | توسط → زمن متوسط | جريان → ضبط بلا إطالة",condition:"The practical completion and relative sound time of a sakin letter",letters:["شديد","متوسط","رخو"],opposite:"Three-way practical timing contrast",
    examples:[ex("يَجْعَلُ","Strong jim in context","جْ","أثر الشدة","Jim must remain audible before moving to ayn.","Complete the closure and release naturally.",10),ex("أَنْعَمْتَ","Moderate nun","نْ","أثر التوسط","Nun carries controlled sound and nasal quality.","Do not cut it abruptly or overlengthen.",10),ex("مِسْكِينٍ","Soft sin","سْ","أثر الرخاوة","Sin's sound flows before kaf.","Keep flow proportional to normal recitation.",11)],
  },
  {
    id:"tajweed-p2-u02-l06-istila",n:6,ar:"الاستعلاء والاستفال",en:"Elevation and lowering",pages:[12],
    definitionAr:"الاستعلاء ارتفاع أقصى اللسان إلى الحنك الأعلى عند النطق بحروف خص ضغط قظ، والاستفال انخفاض اللسان عن الحنك عند بقية الحروف.",
    definitionEn:"Isti'la raises the back of the tongue toward the upper palate in خص ضغط قظ; istifal keeps the tongue lowered for the remaining letters.",
    formula:"خص ضغط قظ = استعلاء | الباقي = استفال",condition:"Whether the back of the tongue rises toward the upper palate",letters:["خ","ص","ض","غ","ط","ق","ظ"],opposite:"Istifal · lowering",
    examples:[ex("قَالَ","Elevated qaf","ق","الاستعلاء","The back of the tongue rises and gives fullness.","Preserve elevation without distorting the vowel.",12),ex("كَانَ","Lowered kaf","ك","الاستفال","Kaf remains lowered despite its nearby articulation.","Do not make kaf heavy like qaf.",12),ex("صِرَاطَ","Elevated sad with kasrah","ص","الاستعلاء","Elevation remains even with kasrah.","Keep fullness at the appropriate level.",12)],
  },
  {
    id:"tajweed-p2-u02-l07-itbaq",n:7,ar:"الإطباق والانفتاح",en:"Adhesion and openness",pages:[12],
    definitionAr:"الإطباق انطباق طائفة من اللسان على الحنك الأعلى وانحصار الصوت بينهما في ص ض ط ظ، والانفتاح تباعدهما في سائر الحروف.",
    definitionEn:"Itbaq brings a broad part of the tongue close to the upper palate and confines sound in ص ض ط ظ; infitah leaves an open space for all other letters.",
    formula:"ص ض ط ظ = إطباق | الباقي = انفتاح",condition:"Whether the tongue broadly adheres toward the palate and confines sound",letters:["ص","ض","ط","ظ"],opposite:"Infitah · openness",
    examples:[ex("صَبْرٌ","Adhesive sad","ص","الإطباق","The tongue-palate relationship confines and strengthens the sound.","Keep the quality without pressing excessively.",12),ex("سَبْرٌ","Open sin contrast","س","الانفتاح","Sin does not carry itbaq.","Contrast it with sad while preserving the same vowel.",12),ex("طَيِّبٌ","Adhesive ta","ط","الإطباق","Ta combines elevation and adhesion.","Avoid replacing it with ت.",12)],
  },
  {
    id:"tajweed-p2-u02-l08-safir",n:8,ar:"الصفير",en:"Whistling",pages:[13],
    definitionAr:"الصفير صوت زائد يشبه صوت الطائر يصاحب الصاد والزاي والسين بسبب ضيق مجرى الصوت بين طرف اللسان والثنايا.",
    definitionEn:"Safir is a sharp whistle-like sound accompanying ص ز س because sound passes through a narrow channel near the tongue tip and incisors.",
    formula:"ص ز س + مجرى ضيق = صفير",condition:"Narrow airflow channel at the articulation of ص ز س",letters:["ص","ز","س"],opposite:"No named opposite",
    examples:[ex("ٱلصِّرَاطَ","Whistling sad","ص","الصفير","The narrow channel produces audible safir with heaviness.","Keep the whistle integrated into sad.",13),ex("زُلْزِلَتْ","Whistling zay","ز","الصفير","Zay combines safir with voiced sound.","Do not turn it into sin.",13),ex("ٱلنَّاسِ","Whistling sin","س","الصفير","Sin carries a clear light whistle.","Avoid excessive hissing.",13)],
  },
  {
    id:"tajweed-p2-u02-l09-leen",n:9,ar:"صفة اللين",en:"Leen as a letter characteristic",pages:[13],
    definitionAr:"اللين خروج الواو والياء الساكنتين المفتوح ما قبلهما بسهولة من غير كلفة، كما في خَوْف وبَيْت.",
    definitionEn:"Leen is the easy, effortless production of sakin waw or ya preceded by fathah, as in khawf and bayt.",
    formula:"ـَوْ أو ـَيْ = لين",condition:"Sakin waw or ya preceded by fathah",letters:["وْ","يْ"],opposite:"No named opposite",
    examples:[ex("خَوْفٍ","Leen waw","وْ","اللين","Fathah precedes sakin waw.","Glide easily without making natural madd.",13),ex("ٱلْبَيْتِ","Leen ya","يْ","اللين","Fathah precedes sakin ya.","Keep a smooth consonantal glide.",13),ex("قُرَيْشٍ","Leen ya","يْ","اللين","The ya is sakin after fathah.","Avoid turning it into ya madd.",13)],
  },
  {
    id:"tajweed-p2-u02-l10-inhiraf",n:10,ar:"الانحراف",en:"Drifting",pages:[14],
    definitionAr:"الانحراف ميل صوت الحرف عن مخرجه حتى يتصل بمخرج غيره، وهو في اللام والراء مع اختلاف كيفية الميل.",
    definitionEn:"Inhiraf is the sound's controlled inclination from its articulation toward a neighboring area; it belongs to lam and ra in distinct ways.",
    formula:"ل ر + ميل صوتي منضبط = انحراف",condition:"Controlled sound inclination in lam and ra",letters:["ل","ر"],opposite:"No named opposite",
    examples:[ex("ٱلْحَمْدُ","Lam drifting","لْ","الانحراف","Lam's sound inclines along the tongue edge.","Keep contact correct and avoid swallowing lam.",14),ex("رَبِّ","Ra drifting","ر","الانحراف","Ra has its own controlled inclination at the tip.","Do not convert inclination into repeated tapping.",14)],
  },
  {
    id:"tajweed-p2-u02-l11-takrir",n:11,ar:"التكرير المنضبط",en:"Controlled repetition",pages:[15],
    definitionAr:"التكرير ارتعاد طرف اللسان عند النطق بالراء، والواجب معرفة الصفة للتحرز من المبالغة فيها فلا تتولد راءات متعددة.",
    definitionEn:"Takrir is the natural tendency of the tongue tip to vibrate in ra; it is studied so the reader controls it and prevents multiple repeated taps.",
    formula:"ر + قابلية التكرير → ضربة منضبطة بلا راءات زائدة",condition:"The tongue-tip tendency to repeat during ra",letters:["ر"],opposite:"No named opposite; control the inherent tendency",
    examples:[ex("رَبِّ","Vowelled ra","ر","التكرير","Ra naturally tends toward repetition.","Use one controlled articulation.",15),ex("مَرْيَمَ","Sakin ra","رْ","التكرير","Sukoon can expose excessive tapping.","Keep the tip stable enough to avoid multiple ra sounds.",15),ex("ٱلرَّحْمَٰنِ","Strengthened ra","رَّ","التكرير","Shaddah requires two components but not uncontrolled rolling.","Fulfil shaddah without repeated trilling.",15)],
  },
  {
    id:"tajweed-p2-u02-l12-tafashshi",n:12,ar:"التفشي",en:"Spreading around",pages:[15],
    definitionAr:"التفشي انتشار الهواء والصوت في الفم عند النطق بالشين حتى يتصل بمخرج الظاء.",
    definitionEn:"Tafashshi is the spreading of air and sound through the mouth during shin, extending broadly across the oral space.",
    formula:"ش + انتشار الصوت في الفم = تفشي",condition:"Broad spreading of air and sound while producing shin",letters:["ش"],opposite:"No named opposite",
    examples:[ex("شَرِّ","Shin spreading","ش","التفشي","Air spreads across the mouth during shin.","Allow natural breadth without turning shin into an extended hiss.",15),ex("ٱلشَّمْسِ","Strengthened shin","شَّ","التفشي","The quality remains through both components of shaddah.","Preserve spreading while controlling duration.",15)],
  },
  {
    id:"tajweed-p2-u02-l13-istitalah",n:13,ar:"الاستطالة",en:"Lengthening characteristic",pages:[16],
    definitionAr:"الاستطالة امتداد الصوت من أول حافة اللسان إلى آخرها عند النطق بالضاد حتى يتصل بمخرج اللام.",
    definitionEn:"Istitalah is the extension of dad's sound along the tongue edge from its beginning toward the articulation area of lam.",
    formula:"ض + امتداد على حافة اللسان = استطالة",condition:"Sound extension along the tongue edge during dad",letters:["ض"],opposite:"No named opposite",
    examples:[ex("ٱلضَّآلِّينَ","Dad extension","ضَّ","الاستطالة","Dad extends along the tongue edge before release.","Preserve dad without replacing it with ظ.",16),ex("وَلَا ٱلضَّآلِّينَ","Dad in context","ضَّ","الاستطالة","The long edge contact distinguishes dad.","Do not confuse sound extension with madd timing.",16)],
  },
  {
    id:"tajweed-p2-u02-l14-ghunnah",n:14,ar:"صفة الغنة",en:"Nasalization characteristic",pages:[16],
    definitionAr:"الغنة صوت أغن يخرج من الخيشوم ملازم للنون والميم، وتختلف قوته وزمنه بحسب حال الحرف والحكم.",
    definitionEn:"Ghunnah is nasal resonance from the nasal passage inherent in nun and mim; its strength and timing vary with the letter's state and rule.",
    formula:"ن أو م + خيشوم = غنة بدرجة الحكم",condition:"Nasal resonance inherent in nun and mim",letters:["ن","م"],opposite:"No named opposite",
    examples:[ex("إِنَّ","Strengthened nun","نَّ","الغنة","Strengthened nun carries a complete strong ghunnah.","Hold the taught two-count nasal sound.",16),ex("ثُمَّ","Strengthened mim","مَّ","الغنة","Strengthened mim combines lip closure and nasal flow.","Keep lips closed while resonance continues.",16),ex("مِنْهُمْ","Sakin nun and mim","نْ","الغنة","Ghunnah degree changes with context.","Apply the specific noon and mim rulings.",16)],
  },
  {
    id:"tajweed-p2-u02-l15-jazariyyah",n:15,ar:"الصفات في متن الجزرية",en:"Characteristics in Al-Jazariyyah",pages:[17],
    definitionAr:"يجمع نظم الجزرية صفات الحروف في عبارات موجزة تعين على الحفظ، لكن فهم المعنى وسماع الأداء الصحيح مقدمان على مجرد حفظ الأبيات.",
    definitionEn:"Al-Jazariyyah summarizes letter characteristics in compact verse for memorization, but understanding and correct heard performance must accompany memorized wording.",
    formula:"نظم للحفظ + شرح للمعنى + أداء للصفة = تعلم صحيح",condition:"Connecting the poem's mnemonic wording to actual letter sound",letters:["صفات متضادة","صفات بلا ضد"],opposite:"Memorization without understanding",
    examples:[ex("فحثه شخص سكت","Hams mnemonic","فحثه شخص سكت","متن الجزرية","The phrase gathers the hams letters.","Use it to recall, then demonstrate breath flow.",17),ex("أجد قط بكت","Shiddah mnemonic","أجد قط بكت","متن الجزرية","The phrase gathers the shiddah letters.","Recall the list and demonstrate blocked sound.",17),ex("خص ضغط قظ","Isti'la mnemonic","خص ضغط قظ","متن الجزرية","The phrase gathers elevated letters.","Recall and produce tongue elevation.",17)],
  },
  {
    id:"tajweed-p2-u02-l16-review",n:16,ar:"مراجعة قوة الصفات وضعفها",en:"Strength and weakness review",pages:[18],
    definitionAr:"تتفاوت الحروف قوة وضعفًا بحسب اجتماع الصفات القوية والضعيفة فيها؛ وتفيد الموازنة في فهم وضوح الحرف وتأثيره من غير أن تغير مخرجه أو حكمه.",
    definitionEn:"Letters vary in relative strength according to the strong and weak characteristics combined within them; comparison explains sound clarity without changing the letter's makhraj or rule.",
    formula:"اجتماع الصفات القوية/الضعيفة → قوة نسبية للحرف",condition:"The combined characteristic profile of each letter",letters:["جهر","شدة","استعلاء","إطباق","صفير"],opposite:"Profiles containing more flowing or lowered qualities",
    examples:[ex("ط","Strong profile","ط","قوة الصفات","Ta combines jahr, shiddah, isti'la, and itbaq.","Produce strength without excessive force.",18),ex("ف","Lighter profile","ف","ضعف الصفات","Fa combines hams, rikhawah, istifal, and infitah.","Keep it clear despite flowing breath.",18),ex("ر","Mixed profile","ر","موازنة الصفات","Ra combines several qualities and needs controlled takrir.","Judge the full profile, not one quality alone.",18)],
    extra:[
      quiz("6 · Mixed","Which letters carry itbaq?",["ص ض ط ظ","خص ضغط قظ","فحثه شخص سكت"],"ص ض ط ظ"),
      quiz("6 · Mixed","Which phrase gathers tawassut letters?",["لن عمر","أجد قط بكت","فحثه شخص سكت"],"لن عمر"),
      quiz("6 · Mixed","What is the purpose of studying takrir?",["To control repetition in ra","To roll ra as much as possible","To make ra a madd letter"],"To control repetition in ra"),
      quiz("6 · Mixed","Which characteristic belongs only to dad?",["Istitalah","Safir","Tafashshi"],"Istitalah"),
    ],
  },
];

export const part2Unit02Lessons = specs.map(make);
