const src=(pages,section)=>({book:"Tajweed Rules of the Qur'an — Part Three",pdf:"Tajweed-Rules-of-the-Quran-p3.pdf",printedPages:pages,pdfPages:pages.map(p=>p+8),chapter:"The Stop",section,verification:"book chapter aligned; semantic stopping judgment requires teacher guidance"});
const ex=(arabic,label,target,rule,why,how,page)=>({arabic,surah:{ar:"مثال تعليمي",en:label},ayah:"—",targetText:target,triggerLetter:target,previousLetter:"موضع الوقف",rule,teacherExplanation:why,readingInstruction:how,commonError:"Stopping where the wording or meaning remains incorrectly attached.",wordBoundary:"stopping-context",sourcePage:page,verificationStatus:"teacher-review-required"});
const q=(stage,prompt,items,answer)=>({stage,type:"waqf-decision",instruction:{en:"Choose the best answer."},prompt,items,acceptedAnswers:[answer],feedbackCorrect:"Correct.",feedbackIncorrect:"Check wording completeness, meaning attachment, and the Mushaf sign."});
function make(s){const{id,n,ar,en,pages,defAr,defEn,formula,condition,letters,examples,extra=[]}=s;return{id,unitId:"part3-unit-01",lessonNumber:`1.${n}`,title:{ar,en},source:src(pages,en),contentOrigin:"book-source-and-instructional-design",level:"Part Three",estimatedMinutes:n===9?50:42,
 prerequisites:["Read connected Qur'anic phrases accurately.","Recognize basic Mushaf stop signs.","Distinguish word completion from meaning completion."],
 learningOutcomes:[`Define ${en.toLowerCase()}.`,"Judge wording and meaning at a proposed stop.","Use the Mushaf sign as guidance.","Choose a safe stop and restart.","Explain the decision before reciting."],
 definition:{linguistic:{ar:"الوقف قطع الصوت على الكلمة زمنًا يتنفس فيه عادة بنية استئناف القراءة.",en:"Stopping cuts the sound at a word long enough to breathe, with intention to resume recitation."},technical:{ar:defAr,en:defEn},studentFriendly:{ar:defAr,en:defEn},memoryFormula:formula},
 keyTerms:[{ar:"الوقف",transliteration:"al-waqf",en:"stopping to breathe"},{ar:"التعلق اللفظي",transliteration:"at-ta'alluq al-lafzi",en:"grammatical attachment"},{ar:"التعلق المعنوي",transliteration:"at-ta'alluq al-ma'nawi",en:"meaning attachment"},{ar:"الابتداء",transliteration:"al-ibtida'",en:"restart"}],
 teacherPreparation:["Display the phrase before and after the stop.","Mark grammatical and meaning attachment separately.","Use Mushaf signs only with explanation.","Practise the restart together with the stop."],
 openingReview:[{minutes:2,teacherPrompt:"Is the wording complete here?"},{minutes:2,teacherPrompt:"Is the meaning complete or attached to what follows?"}],
 conceptExplanation:[{audience:"student",text:defEn},{audience:"teacher",text:"A symbol supports judgment but does not replace understanding the phrase and restart."}],
 lessonPath:[{step:1,title:"Read",text:"Read beyond the proposed stop."},{step:2,title:"Check wording",text:"Is grammar complete?"},{step:3,title:"Check meaning",text:"Is meaning complete?"},{step:4,title:"Read sign",text:"Use the Mushaf symbol."},{step:5,title:"Stop and restart",text:"Choose both safely."}],
 visualExplanation:[{type:"rule-equation",display:formula,teacherUse:"Reveal wording, meaning, sign, stop, and restart."}],ruleSummary:{condition,result:defEn,location:"At a word boundary during recitation.",letters},
 letterGroups:[{name:{ar,en},letters}],quranExamples:examples,
 guidedPractice:[{sequence:1,teacherAction:"Read through the boundary.",studentAction:"Describe attachment.",feedback:"Separate grammar and meaning."},{sequence:2,teacherAction:"Show the Mushaf sign.",studentAction:"Choose stop and restart.",feedback:"Reject a correct stop with a harmful restart."}],
 oralPractice:[{cycle:["read through","check wording","check meaning","read sign","stop/restart"],examplesRequired:examples.length,teacherObservation:["correct category","safe meaning","clean stop","valid restart"]}],
 interactiveActivities:[q("1 · Meaning","What is waqf?",["Stopping to breathe with intent to resume","Ending study forever","A pause without breath only"],"Stopping to breathe with intent to resume"),q("2 · Wording","What must be checked first?",["Wording and grammatical attachment","Page color","Verse length"],"Wording and grammatical attachment"),q("3 · Meaning","What follows wording analysis?",["Meaning attachment","Translation language only","Voice volume"],"Meaning attachment"),q("4 · Sign","What is the role of a Mushaf sign?",["Guidance supporting a correct decision","A decoration","Permission to ignore meaning"],"Guidance supporting a correct decision"),q("5 · Complete skill","A stop decision also requires:",["A valid restart","Only silence","Changing the final word"],"A valid restart"),...extra],
 commonMistakes:["Stopping from breath shortage without planning.","Reading signs without meaning.","Restarting from a dependent phrase.","Calling every verse ending a complete stop."],correctionTechniques:["Read one phrase beyond the stop.","Draw grammar and meaning links.","Pair every stop card with a restart card.","Shorten breath units before difficult locations."],
 knowledgeChecks:[{type:"decision",prompt:"Classify eight proposed stops.",success:"Seven correct with reason and restart."}],teacherQuestions:["Is wording complete?","Is meaning attached?","What sign appears?","Where will you restart?"],studentTasks:["Mark attachment.","Name category.","Stop and restart."],
 liveClassFlow:[{minutes:5,phase:"Review",display:"Read through"},{minutes:8,phase:"Definition",display:formula},{minutes:12,phase:"Meaning map",display:"Links"},{minutes:10,phase:"Signs",display:"Mushaf"},{minutes:7,phase:"Recitation",display:"Stop/restart"},{minutes:3,phase:"Exit",display:"Decision"}],
 independentPractice:["Mark five stops and restarts in a teacher-selected passage."],homework:["Prepare four stop decisions with wording, meaning, sign, and restart."],exitTicket:["Name the stop.","Give reason.","Demonstrate restart."],masteryCriteria:["Checks wording.","Checks meaning.","Uses sign.","Stops cleanly.","Restarts safely."],teacherNotes:["Meaning judgment should be supervised by a qualified teacher."],sourceNotes:[`Uses printed pages ${pages.join(", ")}.`],verificationStatus:"source-aligned; teacher semantic review required"}}
const specs=[
 {id:"tajweed-p3-u01-l01-intro",n:1,ar:"مقدمة في الوقف",en:"Introduction to stopping",pages:[1],defAr:"الوقف مهارة تحفظ اللفظ والمعنى وتراعي النفس، ولا يكون في وسط الكلمة ولا فيما اتصل رسمًا.",defEn:"Stopping protects wording and meaning while accommodating breath; it occurs at a valid word boundary, not inside a word or joined written form.",formula:"نهاية كلمة + نفس + نية الاستئناف = وقف",condition:"A valid word boundary with a planned restart",letters:["نهاية كلمة","تنفس","استئناف"],examples:[ex("ٱلْحَمْدُ لِلَّهِ ۝","Verse-end stop","۝","وقف","A complete word boundary is available.","Stop with correct final-word rules.",1),ex("رَبِّ ٱلْعَٰلَمِينَ","Planned phrase","ٱلْعَٰلَمِينَ","وقف","The reader plans breath at a meaningful boundary.","Do not break inside the phrase.",1)]},
 {id:"tajweed-p3-u01-l02-divisions",n:2,ar:"أقسام الوقف",en:"Divisions of the stop",pages:[2],defAr:"ينقسم الوقف باعتبار السبب إلى اختباري واضطراري وانتظاري واختياري، ويقسم الاختياري باعتبار التعلق إلى تام وكاف وحسن وقبيح.",defEn:"By cause, stopping may be testing, compelled, waiting, or optional; optional stops are evaluated as complete, sufficient, good, or repulsive.",formula:"سبب الوقف → اختباري/اضطراري/انتظاري/اختياري → تقييم المعنى",condition:"The reason for stopping and, for an optional stop, the degree of wording and meaning attachment",letters:["اختباري","اضطراري","انتظاري","اختياري"],examples:[ex("موضع تعليمي","Testing stop","كلمة","اختباري","The teacher tests a written form.","Restart from a valid location.",2),ex("ضيق نفس","Compelled stop","وقف","اضطراري","Breath forces an unplanned stop.","Return to a sound restart.",2)]},
 {id:"tajweed-p3-u01-l03-optional",n:3,ar:"الوقف الاختياري",en:"Optional stopping",pages:[2],defAr:"الوقف الاختياري يختاره القارئ دون ضرورة، ولذلك يجب أن يقع في موضع صحيح لفظًا ومعنى ويقترن بابتداء صحيح.",defEn:"An optional stop is chosen freely, so it must preserve wording and meaning and be paired with a sound restart.",formula:"اختيار القارئ → لا عذر → يلزم موضع وابتداء صحيحان",condition:"The reader chooses to stop without compulsion",letters:["تام","كاف","حسن","قبيح"],examples:[ex("نهاية معنى مستقل","Chosen boundary","وقف","اختياري","The reader has time to select a safe location.","Plan before breath runs out.",2),ex("موضع متعلق بما بعده","Unsafe choice","وقف","قبيح محتمل","A freely chosen harmful boundary has no necessity excuse.","Continue to a safer place.",2)]},
 {id:"tajweed-p3-u01-l04-complete",n:4,ar:"الوقف التام",en:"Complete stop",pages:[3],defAr:"الوقف التام يكون على كلام تم لفظه ومعناه ولم يتعلق بما بعده لا لفظًا ولا معنى، ويحسن الوقف عليه والابتداء بما بعده.",defEn:"A complete stop ends wording and meaning with no grammatical or meaning attachment to what follows; stopping and beginning after it are both sound.",formula:"لا تعلق لفظي + لا تعلق معنوي = وقف تام",condition:"Neither wording nor meaning is attached to what follows",letters:["تمام اللفظ","تمام المعنى"],examples:[ex("نهاية قصة أو موضوع","Complete topic","وقف","تام","The following passage begins a new independent topic.","Stop and begin after it.",3),ex("نهاية سورة","Surah ending","۝","تام غالبًا","The discourse closes fully.","Use correct final-word stopping.",3)]},
 {id:"tajweed-p3-u01-l05-sufficient",n:5,ar:"الوقف الكافي",en:"Sufficient stop",pages:[4,5],defAr:"الوقف الكافي يتم فيه اللفظ ويتعلق ما بعده به في المعنى دون الإعراب، فيحسن الوقف والابتداء بما بعده.",defEn:"A sufficient stop completes the grammatical wording while a meaning relationship remains; it is sound to stop and to begin with what follows.",formula:"لا تعلق لفظي + تعلق معنوي = وقف كاف",condition:"Grammar is complete but meaning remains related to what follows",letters:["لفظ مكتمل","معنى متعلق"],examples:[ex("نهاية آية مرتبطة بالموضوع","Related verse ending","۝","كاف","The sentence is complete though the topic continues.","Stop, then begin with the next complete sentence.",4),ex("انتقال بين أوصاف","Related descriptions","وقف","كاف","Descriptions share a theme without grammatical dependence.","Maintain thematic understanding.",5)]},
 {id:"tajweed-p3-u01-l06-good",n:6,ar:"الوقف الحسن",en:"Good stop",pages:[6],defAr:"الوقف الحسن يكون على كلام أفاد معنى صحيحًا لكنه متعلق بما بعده لفظًا ومعنى؛ يحسن الوقف عليه ولا يحسن الابتداء بما بعده غالبًا.",defEn:"A good stop gives a valid meaning but remains grammatically and semantically attached to what follows; stopping may be acceptable, but beginning with what follows is generally not.",formula:"معنى مفيد + تعلق لفظي ومعنوي = حسن؛ أعد من قبل التعلق",condition:"The stopped phrase gives meaning but what follows remains grammatically dependent",letters:["وقف جائز","ابتداء غير مستقل"],examples:[ex("ٱلْحَمْدُ لِلَّهِ","Meaningful phrase","لِلَّهِ","حسن","The phrase is meaningful while the following description remains attached.","If stopping, restart from a point including the attachment.",6),ex("بِسْمِ ٱللَّهِ","Dependent continuation","ٱللَّهِ","حسن","The phrase is meaningful but connected to what follows in use.","Do not restart from a dependent adjective.",6)]},
 {id:"tajweed-p3-u01-l07-repulsive",n:7,ar:"الوقف القبيح",en:"Repulsive stop",pages:[7,8,9,10],defAr:"الوقف القبيح يكون على ما لم يتم معناه لشدة تعلقه بما بعده، أو يوهم معنى فاسدًا، فلا يتعمد إلا لضرورة ثم يعاد من موضع يصح معه المعنى.",defEn:"A repulsive stop leaves meaning severely incomplete or suggests a false meaning; it must not be chosen, and a compelled stop requires restarting from a point that restores meaning.",formula:"معنى ناقص/فاسد → لا تتعمد الوقف؛ ارجع لابتداء صحيح",condition:"The stop breaks essential wording or suggests an incorrect meaning",letters:["لا","قبيح","إعادة"],examples:[ex("لَا تَقْرَبُوا","Incomplete prohibition","تَقْرَبُوا","قبيح","Stopping before the object can distort the intended command.","Continue or restart with the full construction.",7),ex("إِنَّ ٱللَّهَ","Particle and subject only","ٱللَّهَ","قبيح","The predicate is still required.","Do not choose this stop.",8),ex("فَوَيْلٌ لِّلْمُصَلِّينَ","Meaning completed later","لِّلْمُصَلِّينَ","قبيح معنًى","Stopping can falsely condemn all who pray.","Continue through the qualifying verses.",9)]},
 {id:"tajweed-p3-u01-l08-required",n:8,ar:"توضيح الوقف اللازم",en:"Required-stop clarification",pages:[10],defAr:"علامة الوقف اللازم في المصحف تدل على أن الوصل قد يوهم معنى غير مراد، فهي لزوم أدائي لحفظ المعنى وليست حكمًا شرعيًا يأثم تاركه.",defEn:"The required-stop sign indicates that connection may suggest an unintended meaning; it is a recitation requirement protecting meaning, not a legal ruling that makes omission sinful.",formula:"مـ → الوقف أولى لحماية المعنى؛ ليس حكمًا فقهيًا",condition:"A Mushaf required-stop sign where connection risks meaning confusion",letters:["مـ"],examples:[ex("مـ","Required-stop sign","مـ","وقف لازم","Connection can confuse the intended relation.","Stop and restart after the sign.",10),ex("موضع احتمال معنى","Meaning protection","وقف","لازم أدائي","The sign protects interpretation.","Do not describe it as legal obligation.",10)]},
 {id:"tajweed-p3-u01-l09-signs",n:9,ar:"علامات الوقف في مصحف المدينة",en:"Madinah Mushaf stop signs",pages:[11],defAr:"تجمع علامات مصحف المدينة: مـ للزوم الوقف، لا للنهي عن الوقف، ج للجواز، صلى للوصل أولى، قلى للوقف أولى، وعلامات التعانق للوقف على أحد الموضعين دون كليهما.",defEn:"Madinah Mushaf signs include required stop, do-not-stop, permissible stop, connection preferred, stopping preferred, and paired embrace signs where one of two locations may be used but not both.",
    formula:"مـ قف | لا لا تقف | ج يجوز | صلى صل أولى | قلى قف أولى | ∴ أحد الموضعين",condition:"The stop symbol printed at the word boundary",letters:["مـ","لا","ج","صلى","قلى","∴"],
    examples:[ex("ج","Permissible","ج","جائز","Both stop and connection are acceptable.","Choose according to breath and meaning.",11),ex("صلى","Connection preferred","صلى","الوصل أولى","Connection better preserves flow.","Continue when able.",11),ex("قلى","Stopping preferred","قلى","الوقف أولى","Stopping better separates meaning.","Stop when practical.",11),ex("∴   ∴","Embrace signs","∴","تعانق","Stop at one of the paired places, not both.","Plan the pair before reading.",11)],extra:[q("6 · Sign","Which means connection is preferred?",["صلى","قلى","مـ"],"صلى"),q("6 · Sign","Which means stopping is preferred?",["قلى","صلى","لا"],"قلى"),q("6 · Sign","At embrace signs, stop at:",["One of the two, not both","Both","Neither ever"],"One of the two, not both")]},
];
export const part3Unit01Lessons=specs.map(make);
