const src = (pages, section) => ({
  book: "Tajweed Rules of the Qur'an — Part One",
  pdf: "en_Tajweed_Rules_of_the_Quran_Part_01.pdf",
  pdfPages: pages,
  printedPages: pages,
  chapter: "Qalqalah",
  section,
  verification: "book source aligned; recitation quality requires teacher observation",
});

const quranExample = (arabic, label, target, rule, why, how, page) => ({
  arabic,
  surah: { ar: "مثال قرآني", en: label },
  ayah: "—",
  targetText: target,
  triggerLetter: target,
  previousLetter: "حرف القلقلة",
  rule,
  teacherExplanation: why,
  readingInstruction: how,
  commonError: "Turning qalqalah into a full short vowel.",
  wordBoundary: "word-or-stop-context",
  sourcePage: page,
  verificationStatus: "teacher-review-required",
});

const quiz = (stage, prompt, items, answer, right, wrong) => ({
  stage,
  type: "qalqalah-decision",
  instruction: { en: "Choose the best answer." },
  prompt,
  items,
  acceptedAnswers: [answer],
  feedbackCorrect: right,
  feedbackIncorrect: wrong,
});

function lesson(spec) {
  const { id, n, ar, en, pages, definitionAr, definitionEn, formula, condition, examples, extra = [] } = spec;
  return {
    id,
    unitId: "unit-09",
    lessonNumber: `9.${n}`,
    title: { ar, en },
    source: src(pages, en),
    contentOrigin: "source-and-instructional-design",
    level: "Foundation",
    estimatedMinutes: n === 5 ? 60 : 45,
    prerequisites: [
      "Identify sukoon and stopping context.",
      "Produce sakin letters without adding a vowel.",
      "Recognize the articulation points of ق ط ب ج د.",
    ],
    learningOutcomes: [
      `Define ${en.toLowerCase()}.`,
      "Identify the qalqalah letter and its state.",
      "Select the correct qalqalah level.",
      "Produce a clear release without an added vowel.",
      "Apply the ruling in teacher-approved recitation.",
    ],
    definition: {
      linguistic: { ar: "القلقلة لغةً: الاضطراب والتحرك.", en: "Qalqalah linguistically means shaking or disturbance." },
      technical: { ar: definitionAr, en: definitionEn },
      studentFriendly: { ar: definitionAr, en: definitionEn },
      memoryFormula: formula,
    },
    keyTerms: [
      { ar: "القلقلة", transliteration: "al-qalqalah", en: "controlled audible release" },
      { ar: "قطب جد", transliteration: "qutbu jadd", en: "the five qalqalah letters" },
      { ar: "القلقلة الصغرى", transliteration: "al-qalqalah as-sughra", en: "lesser qalqalah" },
      { ar: "القلقلة الكبرى", transliteration: "al-qalqalah al-kubra", en: "greater qalqalah" },
    ],
    teacherPreparation: [
      "Prepare minimal pairs: correct qalqalah versus added fathah, dammah, and kasrah.",
      "Model the letter from its true articulation point.",
      "Use waveform or recording only as support; judge by listening.",
      "Prepare connected and stopping examples.",
    ],
    openingReview: [
      { minutes: 2, teacherPrompt: "Is the target one of ق ط ب ج د?" },
      { minutes: 2, teacherPrompt: "Is it sakin originally or because of stopping?" },
    ],
    conceptExplanation: [
      { audience: "student", text: definitionEn },
      { audience: "teacher", text: "Qalqalah makes the sakin letter audible through a controlled release; it does not assign a new vowel." },
    ],
    lessonPath: [
      { step: 1, title: "Find", text: "Locate one of ق ط ب ج د." },
      { step: 2, title: "Check", text: "Confirm that it is sakin or made sakin by stopping." },
      { step: 3, title: "Classify", text: "Choose lesser or greater qalqalah." },
      { step: 4, title: "Release", text: "Make the letter audible from its articulation point." },
      { step: 5, title: "Audit", text: "Check that no full vowel was added." },
    ],
    visualExplanation: [
      { type: "rule-equation", display: formula, teacherUse: "Point to letter, sukoon context, level, then release." },
    ],
    ruleSummary: {
      condition,
      result: definitionEn,
      location: "On a sakin qalqalah letter in connection or at stopping.",
      letters: ["ق", "ط", "ب", "ج", "د"],
    },
    letterGroups: [
      { name: { ar: "حروف القلقلة", en: "Qalqalah letters" }, letters: ["ق", "ط", "ب", "ج", "د"] },
      { name: { ar: "الحالة", en: "Required state" }, letters: ["ْ", "وقف"] },
    ],
    quranExamples: examples,
    guidedPractice: [
      {
        sequence: 1,
        teacherAction: "Model the articulation without qalqalah, then with controlled qalqalah.",
        studentAction: "Identify which production keeps the letter audible.",
        feedback: "Reject both a swallowed letter and a full added vowel.",
      },
      {
        sequence: 2,
        teacherAction: "Model the example in connected or stopping context.",
        studentAction: "Classify the level and repeat.",
        feedback: "Correct articulation, clarity, and degree.",
      },
    ],
    oralPractice: [{
      cycle: ["find letter", "confirm sukoon", "name level", "release", "check vowel"],
      examplesRequired: examples.length,
      teacherObservation: ["correct letter", "correct level", "audible release", "no added vowel"],
    }],
    interactiveActivities: [
      quiz("1 · Letters", "Which group contains all qalqalah letters?", ["ق ط ب ج د", "ي ر م ل و ن", "ء ه ع ح غ خ"], "ق ط ب ج د", "Correct.", "Use the mnemonic قطب جد."),
      quiz("2 · State", "When is qalqalah applied?", ["When a qalqalah letter is sakin", "Whenever the letter is vowelled", "On every final letter"], "When a qalqalah letter is sakin", "Correct.", "The letter and sukoon must meet."),
      quiz("3 · Sound", "What is the goal of qalqalah?", ["A controlled audible release", "A complete fathah", "A long madd"], "A controlled audible release", "Correct.", "Keep the letter clear without a new vowel."),
      quiz("4 · Diagnosis", "The learner says أَدَ for أَدْ. What is the error?", ["An added fathah", "Correct qalqalah", "Missing madd"], "An added fathah", "Correct.", "The ending must remain sakin."),
      quiz("5 · Method", "What should be checked before choosing the degree?", ["Whether the letter is connected or stopped on", "The English translation", "The line number"], "Whether the letter is connected or stopped on", "Correct.", "Context determines lesser or greater."),
      ...extra,
    ],
    commonMistakes: [
      "Adding a full fathah, dammah, or kasrah.",
      "Applying qalqalah while the letter is vowelled.",
      "Swallowing the sakin letter completely.",
      "Using the same strength in every context.",
      "Moving the articulation point during release.",
    ],
    correctionTechniques: [
      "Contrast أَدْ with أَدَ, أَدُ, and أَدِ.",
      "Hold the articulation position before the controlled release.",
      "Practice the target alone, then in the word.",
      "Record one lesser and one greater example for comparison.",
    ],
    knowledgeChecks: [
      { type: "recognition", prompt: "Classify twelve samples.", success: "At least ten correct with letter, state, and level." },
      { type: "recitation", prompt: "Recite a mixed set.", success: "Teacher approves two consecutive attempts without added vowels." },
    ],
    teacherQuestions: [
      "Which qalqalah letter is present?",
      "Why is it sakin?",
      "Is this lesser or greater?",
      "Did the release create a full vowel?",
    ],
    studentTasks: ["Highlight the target.", "Name the level.", "Recite and self-diagnose the release."],
    liveClassFlow: [
      { minutes: 5, phase: "Review", display: "قطب جد" },
      { minutes: 8, phase: "Definition", display: formula },
      { minutes: 10, phase: "Teacher model", display: "Correct / added vowel" },
      { minutes: 10, phase: "Classification", display: "Lesser / greater" },
      { minutes: 8, phase: "Recitation", display: "Teacher listening" },
      { minutes: 4, phase: "Exit", display: "Letter, state, level" },
    ],
    independentPractice: ["Mark and record five teacher-approved qalqalah examples."],
    homework: ["Prepare two lesser and two greater examples with written classification."],
    exitTicket: ["Name the letter.", "State the level.", "Recite without an added vowel."],
    masteryCriteria: [
      "Recognizes all five letters.",
      "Confirms the sukoon context.",
      "Distinguishes lesser and greater.",
      "Produces an audible release without a full vowel.",
      "Passes two teacher-observed attempts.",
    ],
    teacherNotes: [
      "Do not teach qalqalah as an extra vowel.",
      "Degree is heard in context; typography alone is insufficient.",
    ],
    sourceNotes: [
      `Uses pages ${pages.join(", ")}.`,
      "Activities and diagnostic contrasts are instructional-design additions.",
    ],
    verificationStatus: "source-aligned; teacher recitation review required",
  };
}

const specs = [
  {
    id: "tajweed-u09-l01-mechanism",
    n: 1,
    ar: "حقيقة القلقلة وحروفها",
    en: "Qalqalah mechanism and letters",
    pages: [87],
    definitionAr: "القلقلة اضطراب صوت الحرف عند النطق به ساكنًا حتى يسمع له نبرة قوية من غير أن يصاحبه فتح للفم أو ضم للشفتين أو كسر للفك، وحروفها ق ط ب ج د.",
    definitionEn: "Qalqalah is a controlled disturbance and audible release of a sakin ق ط ب ج د, without turning the release into a short vowel.",
    formula: "ق ط ب ج د + سكون = قلقلة مسموعة بلا حركة",
    condition: "One of ق ط ب ج د carrying sukoon",
    examples: [
      quranExample("يَقْطَعُونَ", "Sakin qaf", "قْ", "قلقلة", "Qaf is one of the five letters and is sakin.", "Release qaf audibly without saying قَ.", 87),
      quranExample("أَطْعَمَهُم", "Sakin ta", "طْ", "قلقلة", "Ta is sakin inside the word.", "Keep its heavy articulation and controlled release.", 87),
      quranExample("أَبْصَارِهِمْ", "Sakin ba", "بْ", "قلقلة", "The lips close for sakin ba.", "Release without adding fathah.", 87),
      quranExample("يَجْعَلُونَ", "Sakin jim", "جْ", "قلقلة", "Jim is sakin in connection.", "Make jim audible, then move directly to ayn.", 87),
      quranExample("يَدْعُونَ", "Sakin dal", "دْ", "قلقلة", "Dal is sakin before ayn.", "Release dal without a vowel.", 87),
    ],
  },
  {
    id: "tajweed-u09-l02-no-added-vowel",
    n: 2,
    ar: "تجنب الحركة الزائدة في القلقلة",
    en: "Avoiding an added vowel",
    pages: [88],
    definitionAr: "تبقى حركة الفم عند القلقلة على وضع السكون، ويُسمع الحرف بتحرير مخرجه من غير فتح كامل أو ضم أو كسر يكوّن حركة جديدة.",
    definitionEn: "During qalqalah the letter remains sakin: its release is audible, but the mouth must not complete the movement of fathah, dammah, or kasrah.",
    formula: "صوت واضح − (فتحة أو ضمة أو كسرة مضافة) = قلقلة صحيحة",
    condition: "A sakin qalqalah letter whose release must remain vowel-free",
    examples: [
      quranExample("قَدْ", "Dal without added fathah", "دْ", "قلقلة بلا حركة", "The word ends in sakin dal.", "Say قَدْ, never قَدَ.", 88),
      quranExample("لَمْ يَلِدْ", "Final dal", "دْ", "قلقلة بلا حركة", "Stopping strengthens clarity but not a vowel.", "Keep the ending closed and controlled.", 88),
      quranExample("ٱلْفَلَقِ", "Stopping on qaf", "قِ", "قلقلة عند الوقف", "Stopping removes the kasrah and makes qaf sakin.", "Do not preserve the kasrah or add fathah.", 88),
    ],
    extra: [
      quiz("6 · Contrast", "Which is the correct target for قَدْ?", ["A clear sakin dal", "دَ", "دُ"], "A clear sakin dal", "Correct.", "Qalqalah does not add a vowel."),
      quiz("6 · Correction", "What should the teacher correct first when a full vowel appears?", ["Mouth direction and release", "Verse number", "Reading speed only"], "Mouth direction and release", "Correct.", "Reset the articulation and keep sukoon."),
    ],
  },
  {
    id: "tajweed-u09-l03-lesser",
    n: 3,
    ar: "القلقلة الصغرى",
    en: "Lesser qalqalah",
    pages: [89],
    definitionAr: "القلقلة الصغرى تكون في حرف القلقلة الساكن سكونًا أصليًا في أثناء الوصل، ويكون اضطراب الصوت فيها أخف من القلقلة عند الوقف.",
    definitionEn: "Lesser qalqalah occurs on an originally sakin qalqalah letter during connected recitation and has a lighter controlled release than stopping qalqalah.",
    formula: "حرف قلقلة + سكون أصلي في الوصل = قلقلة صغرى",
    condition: "Original sukoon on a qalqalah letter during connection",
    examples: [
      quranExample("يَقْطَعُونَ", "Connected qaf", "قْ", "قلقلة صغرى", "Qaf is originally sakin inside the word.", "Use a light, clear release.", 89),
      quranExample("أَطْعَمَهُم", "Connected ta", "طْ", "قلقلة صغرى", "Ta remains sakin while reading continues.", "Release and move directly to ayn.", 89),
      quranExample("يَبْتَغُونَ", "Connected ba", "بْ", "قلقلة صغرى", "Ba is sakin inside the word.", "Keep the bounce controlled and light.", 89),
      quranExample("يَجْعَلُونَ", "Connected jim", "جْ", "قلقلة صغرى", "Jim has original sukoon.", "Avoid separating it from the following ayn.", 89),
      quranExample("يَدْعُونَ", "Connected dal", "دْ", "قلقلة صغرى", "Dal is sakin during connection.", "Do not add a vowel between dal and ayn.", 89),
    ],
  },
  {
    id: "tajweed-u09-l04-greater",
    n: 4,
    ar: "القلقلة الكبرى",
    en: "Greater qalqalah",
    pages: [90],
    definitionAr: "القلقلة الكبرى تكون عند الوقف على حرف من حروف القلقلة فيصير ساكنًا، ويكون صوت القلقلة أوضح وأقوى، ويزداد وضوحه إن كان الحرف مشددًا.",
    definitionEn: "Greater qalqalah occurs when stopping on a qalqalah letter makes it sakin; its release is clearer and stronger, especially when the stopped letter is strengthened.",
    formula: "وقف على ق ط ب ج د = قلقلة كبرى واضحة بلا حركة",
    condition: "Stopping on a qalqalah letter",
    examples: [
      quranExample("ٱلْفَلَقِ", "Stop on qaf", "قِ", "قلقلة كبرى", "Stopping makes the final qaf sakin.", "Release qaf clearly without adding a vowel.", 90),
      quranExample("مُحِيطٌ", "Stop on ta", "طٌ", "قلقلة كبرى", "Stopping removes tanween and makes ta sakin.", "Preserve heavy ta and a clear release.", 90),
      quranExample("لَهَبٍ", "Stop on ba", "بٍ", "قلقلة كبرى", "Stopping makes final ba sakin.", "Close and release the lips without بَ.", 90),
      quranExample("بَهِيجٍ", "Stop on jim", "جٍ", "قلقلة كبرى", "Final jim becomes sakin when stopping.", "Make the articulation clear and controlled.", 90),
      quranExample("أَحَدٌ", "Stop on dal", "دٌ", "قلقلة كبرى", "Stopping creates final sakin dal.", "Use a clear greater release without دَ.", 90),
    ],
  },
  {
    id: "tajweed-u09-l05-final-review",
    n: 5,
    ar: "المراجعة النهائية للجزء الأول",
    en: "Final Part One review",
    pages: [87, 88, 89, 90, 91],
    definitionAr: "تجمع المراجعة النهائية بين تحديد حرف القلقلة وحالته ودرجته وتصحيح الأداء، ثم تربط ذلك بالمهارات السابقة في المخارج والغنة وأحكام السواكن والمدود.",
    definitionEn: "The final review diagnoses qalqalah letter, state, level, and sound, then integrates it with Part One articulation, ghunnah, sakin-letter rules, and madd decisions.",
    formula: "حدّد → صنّف → طبّق → استمع → صحّح → اربط بأحكام الجزء الأول",
    condition: "Mixed Part One recognition and teacher-observed recitation",
    examples: [
      quranExample("يَقْطَعُونَ", "Lesser qalqalah", "قْ", "قلقلة صغرى", "Original sukoon occurs during connection.", "Use a lighter controlled release.", 91),
      quranExample("أَحَدٌ", "Greater qalqalah at stop", "دٌ", "قلقلة كبرى", "Stopping makes dal sakin.", "Use a clearer release without a vowel.", 91),
      quranExample("مِنۢ بَعْدِ", "Noon rule review", "نۢ ب", "إقلاب", "Noon saakinah meets ba.", "Apply the previously learned iqlab.", 91),
      quranExample("مِن شَرِّ", "Noon rule review", "ن ش", "إخفاء", "Noon saakinah meets shin.", "Apply the previously learned ikhfa.", 91),
      quranExample("جَآءَ", "Madd review", "جَآءَ", "مد متصل", "Hamzah follows madd in one word.", "Use the consistent taught count.", 91),
    ],
    extra: [
      quiz("6 · Level", "Stopping on أَحَدٌ produces which level?", ["Greater qalqalah", "Lesser qalqalah", "No qalqalah"], "Greater qalqalah", "Correct.", "Stopping makes final dal sakin."),
      quiz("6 · Connection", "The qaf in يَقْطَعُونَ has:", ["Lesser qalqalah", "Greater qalqalah", "Natural madd"], "Lesser qalqalah", "Correct.", "It is originally sakin during connection."),
      quiz("6 · Integration", "Noon saakinah before ba requires:", ["Iqlab", "Izhar", "Qalqalah"], "Iqlab", "Correct.", "Ba triggers iqlab."),
      quiz("6 · Integration", "A madd letter followed by hamzah in one word is:", ["Attached madd", "Separate madd", "Leen only"], "Attached madd", "Correct.", "Both occur in the same word."),
      quiz("6 · Mastery", "What completes Part One mastery?", ["Knowledge checks plus teacher-observed correct recitation", "Quiz score alone", "Reading quickly"], "Knowledge checks plus teacher-observed correct recitation", "Correct.", "Tajweed is applied sound knowledge."),
    ],
  },
];

export const unit09Lessons = specs.map(lesson);
