export const lessonId = "Review-Beginner-Units1-5";

export const lesson = {
    meta: {
        level: "Beginner",
        unit: "Cumulative Review 1",
        lessonTitle: "Review Units 1-5",
        contentVersion: 2026081501,
        availableTabs: ["overview", "grammar", "translation", "practice"],
    },
    overview: {
        title: "Cumulative Review 1",
        description: "A teacher-led cumulative review of greetings, family, daily routine, food, and transportation. The learner may retry, check answers, and discuss mistakes.",
        goals: [
            "Recall essential vocabulary from Units 1-5.",
            "Build accurate present-tense sentences and questions.",
            "Review gender, possession, negation, quantities, directions, and commands.",
            "Use all five units together in one spoken situation.",
        ],
        speakingOutcomes: ["The learner can handle a connected real-life situation using material from Units 1-5."],
    },
    vocabulary: { core: [], extra: [] },
    dialogue: { title: "Review through practice", setting: "Use the Practice tab for this review.", lines: [] },
    grammar: [
        {
            title: "Review 1 — Introductions and agreement",
            short: "Pronouns, question words, and gender",
            description: "Build a complete introduction by choosing the right pronoun, question word, and masculine or feminine description. The form must match the person being described.",
            table: {
                title: "Fast recall",
                headers: ["Function", "Masculine", "Feminine", "Plural"],
                rows: [
                    ["pronoun", "هو", "هي", "همّ"],
                    ["from where?", "من وين إنت؟", "من وين إنتِ؟", "من وين إنتو؟"],
                    ["living", "ساكن", "ساكنة", "ساكنين"],
                ],
            },
            examples: [
                { ar: "شو اسمِك ومن وين إنتِ؟", arabeezy: "sho ismik w min ween inti?", en: "What is your name, and where are you from? (to a woman)" },
                { ar: "هِيَّ مِن غَزَّة وَسَاكْنَة فِي غَزَّة.", arabeezy: "hiyye min Ghazza w sakneh fi Ghazza.", en: "She is from Gaza and lives in Gaza." },
            ],
            commonMistakes: ["Match the description to the person: هو ساكن, هي ساكنة.", "Use شو for ‘what’, مين for ‘who’, وين for ‘where’, and كيف for ‘how’."],
            exercises: [
                { prompt: "Complete: ___ اسمِك؟ (to a woman)", options: ["شو", "مين", "وين", "قدّيش"], correct: "شو", explanation: "شو asks for the name: ‘what is your name?’" },
                { prompt: "Choose the sentence for: She lives in Gaza.", options: ["هِيَّ سَاكْنَة فِي غَزَّة.", "هِيَّ سَاكِن فِي غَزَّة.", "هُوَّ سَاكْنَة فِي غَزَّة.", "هِيَّ سَاكْنِين فِي غَزَّة."], correct: "هِيَّ سَاكْنَة فِي غَزَّة.", explanation: "The active description agrees with the feminine subject." },
            ],
        },
        {
            title: "Review 2 — Family and possession",
            short: "عندي, attached ownership, dual, and adjective agreement",
            description: "Use عندي to say what family members you have, and attached endings to identify whose person or thing it is. Review two-person forms and adjective agreement.",
            table: {
                title: "Possession map",
                headers: ["Meaning", "Pattern", "Example"],
                rows: [
                    ["I have", "عندي", "عندي أخ"],
                    ["my", "ـي", "أخوي / أختي"],
                    ["his", "ـه", "أخوه"],
                    ["her", "ـها", "أختها"],
                    ["two", "ـين", "أخوين / أختين"],
                ],
            },
            examples: [
                { ar: "عندي أخوين وأخت وحدة.", arabeezy: "3indi akhwein w ukht wa7de.", en: "I have two brothers and one sister." },
                { ar: "أُخْتْهَا مِتْجَوِّزَة.", arabeezy: "ukht-ha mitjawwzeh.", en: "Her sister is married." },
            ],
            commonMistakes: ["Negate عندي with ما: ما عندي إخوة.", "The adjective follows the gender: أخ كبير, أخت كبيرة."],
            exercises: [
                { prompt: "Choose: ‘I do not have brothers.’", options: ["ما عندي إخوة.", "مش عندي إخوة.", "ما إخوتي عندي.", "عندي ما إخوة."], correct: "ما عندي إخوة.", explanation: "Existence/possession with عندي is negated using ما." },
                { prompt: "Complete: عندي ___ . ‘two sisters’", options: ["أختين", "أختان", "أختات", "اتنين أخت"], correct: "أختين", explanation: "The spoken dual form is أختين." },
            ],
        },
        {
            title: "Review 3 — Daily routine",
            short: "Present conjugation, time, frequency, and ما",
            description: "A routine combines the بـ-present with a time or frequency expression. The beginning and ending of the verb identify the subject.",
            table: {
                title: "Present-tense checkpoints",
                headers: ["Subject", "Wake up", "Go"],
                rows: [
                    ["أنا", "بصحى", "بروح"],
                    ["إنتَ", "بتصحى", "بتروح"],
                    ["إنتِ", "بتصحي", "بتروحي"],
                    ["هو", "بصحى", "بروح"],
                    ["هي", "بتصحى", "بتروح"],
                    ["إحنا", "بنصحى", "بنروح"],
                    ["همّ", "بصحوا", "بروحوا"],
                ],
            },
            examples: [
                { ar: "كل يوم بصحى عالسبعة وبروح عالشغل.", arabeezy: "kol yom baS7a 3as-sab3a w baroo7 3ash-shoghol.", en: "Every day I wake up at seven and go to work." },
                { ar: "يَوم الجُمْعَة مَا بِنْصَحَى بَدْرِي.", arabeezy: "yom el-jom3a ma binSa7a badri.", en: "On Friday we do not wake up early." },
            ],
            commonMistakes: ["Add ـي for feminine ‘you’: بتروحي.", "Use ما before the routine verb: ما بروح."],
            exercises: [
                { prompt: "Complete the sentence for: You go to class every day. (to a woman)\nإِنْتِ ___ عَالدَّرْس كُلّ يَوم.", options: ["بِتْرُوحِي", "بِتْرُوح", "بَرُوحُوا", "بِنْرُوح"], correct: "بِتْرُوحِي", explanation: "Feminine singular ‘you’ takes تـ and final ـي." },
                { prompt: "Choose the sentence for: I do not drink coffee at night.", options: ["أَنَا مَا بَشْرَب قَهْوَة بِاللِّيل.", "أَنَا بَشْرَب قَهْوَة بِاللِّيل.", "أَنَا مَا بَنَام بِاللِّيل.", "أَنَا مَا بَاكُل قَهْوَة."], correct: "أَنَا مَا بَشْرَب قَهْوَة بِاللِّيل.", explanation: "ما negates a present-tense habitual verb." },
            ],
        },
        {
            title: "Review 4 — Food, quantity, and commands",
            short: "Order naturally and match the number phrase",
            description: "Food language combines بدّي with the item, a useful quantity, and a polite closer. Commands change for a man, woman, or group.",
            table: {
                title: "Ordering and commands",
                headers: ["Function", "Pattern", "Example"],
                rows: [
                    ["request", "بدّي + item", "بدّي قهوة"],
                    ["quantity", "number + حبّات", "تلات حبّات فلافل"],
                    ["to a man", "command", "خد / كُل / اشرب"],
                    ["to a woman", "command + ي", "خدي / كلي / اشربي"],
                    ["polite refusal", "لَا يِسْلَمُوا", "لَا يِسْلَمُوا، شْبِعِت"],
                ],
            },
            examples: [
                { ar: "بدّي تلات حبّات فلافل وكاسة شاي.", arabeezy: "baddi talat 7abbat falafel w kaset shay.", en: "I want three falafel pieces and a glass of tea." },
                { ar: "خدي حبّة وكليها.", arabeezy: "khodi 7abbe w kuliha.", en: "Take one and eat it. (to a woman)" },
            ],
            commonMistakes: ["Give an English cue for the missing item so the learner knows what to produce.", "Do not use the masculine command when addressing a woman."],
            exercises: [
                { prompt: "Complete with the English cue ‘pieces’: بدّي تلات ___ فلافل.", options: ["حبّات", "كاسات", "كيلو", "صحون"], correct: "حبّات", explanation: "حبّات is a natural counter for individual falafel pieces." },
                { prompt: "Tell a woman: ‘Drink the water.’", options: ["اشربي الميّ.", "اشرب الميّ.", "اشربوا الميّ.", "بتشربي الميّ."], correct: "اشربي الميّ.", explanation: "The feminine command ends in ـي." },
            ],
        },
        {
            title: "Review 5 — Transport, directions, and prohibition",
            short: "Ask the fare and guide someone safely",
            description: "Combine a transport question with place words, prepositions, directions, and commands. A negative command uses لا + present form without the habitual بـ.",
            table: {
                title: "Direction toolkit",
                headers: ["Job", "Palestinian Arabic", "Meaning"],
                rows: [
                    ["fare", "قدّيش الأجرة؟", "How much is the fare?"],
                    ["straight", "دغري", "straight"],
                    ["turn", "لف يمين / شمال", "turn right / left"],
                    ["location", "جنب / قبال / ورا", "beside / opposite / behind"],
                    ["prohibition", "لا تلف", "do not turn"],
                ],
            },
            examples: [
                { ar: "روح دغري، وبعد الإشارة لفّ شمال.", arabeezy: "roo7 doghri, w ba3d el-ishara liff shmal.", en: "Go straight, and after the traffic light turn left." },
                { ar: "لَا تِنْزَل هِنَا؛ اِنْزَل قُبَال المَدْرَسَة.", arabeezy: "la tinzal hena; inzal qbal el-madraseh.", en: "Do not get off here; get off opposite the school." },
            ],
            commonMistakes: ["Use وين للمكان and قدّيش للسعر.", "The prohibition is لا تلف, not لا لف."],
            exercises: [
                { prompt: "Which question asks for the taxi fare?", options: ["قدّيش الأجرة؟", "وين الأجرة؟", "مين الأجرة؟", "كيف الأجرة؟"], correct: "قدّيش الأجرة؟", explanation: "قدّيش asks about an amount or price." },
                { prompt: "Choose the negative command: ‘Do not turn right.’", options: ["لا تلف يمين.", "مش لف يمين.", "ما بتلف يمين.", "لا يمين لفّيت."], correct: "لا تلف يمين.", explanation: "A spoken prohibition uses لا + the matching present form without بـ." },
            ],
        },
    ],
    microChecks: { enabled: false, every: 5, items: [] },
    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        quiz: [
            { id: "br1_q1", questionAr: "Choose the natural reply to صَبَاح الخِير (sabah el-kheir).", optionsEn: ["مَع السَّلَامَة", "صَبَاح النُّور", "شُو اِسْمَك؟"], correctIndex: 1 },
            { id: "br1_q2", questionAr: "Choose the meaning of عِنْدِي أَخ وَأُخْت (3indi akh w ukht).", optionsEn: ["I live with my parents.", "My brother is older.", "I have a brother and a sister."], correctIndex: 2 },
            { id: "br1_q3", questionAr: "Choose the sentence for: Every day I wake up early.", optionsEn: ["كُلّ يَوم بَصْحَى بَدْرِي.", "بِاللِّيل بَنَام بَدْرِي.", "اليَوم مَا بَرُوح."], correctIndex: 0 },
            { id: "br1_q4", questionAr: "Choose the polite phrase meaning: No thanks, I am full.", optionsEn: ["بَدِّي مَيّ.", "لَا يِسْلَمُوا، شْبِعِت.", "الجَاج زَاكِي."], correctIndex: 1 },
            { id: "br1_q5", questionAr: "Choose the question used to ask a taxi fare.", optionsEn: ["مَع مِين سَاكِن؟", "كِيفَك؟", "قَدِّيش الأُجْرَة؟"], correctIndex: 2 },
            { id: "br1_q6", questionAr: "Choose the sentence for: My name is Lina.", optionsEn: ["اِسْمِي لِينَا.", "أَنَا مِن لِينَا.", "شُو اِسْمِك؟"], correctIndex: 0 },
            { id: "br1_q7", questionAr: "Choose the sentence for: My sister is younger than me.", optionsEn: ["أُخْتِي قَدِّي.", "أُخْتِي أَصْغَر مِنِّي.", "أُخْتِي أَكْبَر مِنِّي."], correctIndex: 1 },
            { id: "br1_q8", questionAr: "Choose the English meaning of: بَعْد مَا بَرْجَع، بَرْتَاح شُوَيّ.", optionsEn: ["Before I leave, I have breakfast.", "At night I sleep late.", "After I return, I rest a little."], correctIndex: 2 },
            { id: "br1_q9", questionAr: "Choose the sentence for: I do not like fish.", optionsEn: ["مَا بَحِبّ السَّمَك.", "بَحِبّ السَّمَك.", "أَنَا عَطْشَان."], correctIndex: 0 },
            { id: "br1_q10", questionAr: "Choose the polite request meaning: I get off here, please.", optionsEn: ["بَرْكَب البَاص.", "بَنْزَل هِنَا، لَوْ سَمَحْت.", "التَّاكْسِي غَالِي."], correctIndex: 1 },
        ],
        rolePlays: [
            "Unit 1: Meet a new classmate. Greet them, exchange names and origins, then close naturally.",
            "Unit 2: Describe your family in five sentences and ask your partner two family questions.",
            "Unit 3: Describe your day from waking up until sleeping.",
            "Unit 4: Offer your guest food and water; the guest accepts one item and politely refuses more.",
            "Unit 5: Take a taxi, ask about the fare, and tell the driver where you want to get off.",
            "Integrated task: Introduce yourself, mention one family member, describe your morning, say one food you like, and explain how you go to class or work.",
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "مِن وِين؟", arabeezy: "min ween?", en: "Where are you from?" },
                    { ar: "أَهْلِي", arabeezy: "ahli", en: "my family / parents" },
                    { ar: "بَرْجَع", arabeezy: "barja3", en: "I return" },
                    { ar: "شْبِعِت", arabeezy: "shbi3t", en: "I am full" },
                    { ar: "دُغْرِي", arabeezy: "dughri", en: "straight" },
                    { ar: "بِنْشُوفَك بَعْدِين", arabeezy: "binshoofak ba3deen", en: "See you later" },
                    { ar: "أَصْغَر", arabeezy: "asghar", en: "younger" },
                    { ar: "بَفْطَر", arabeezy: "bafTar", en: "I have breakfast" },
                    { ar: "مِش جَاي عَلَى بَالِي", arabeezy: "mish jay 3ala bali", en: "I do not feel like it" },
                    { ar: "الأُجْرَة", arabeezy: "el-ojra", en: "the fare" },
                ],
                multipleChoice: [],
            },
            {
                title: "B - Controlled review",
                fillInTheBlank: [
                    { prompt: "___ اِسْمَك؟", arabeezy: "___ ismak?", cueEn: "what", answer: "شُو" },
                    { prompt: "أَنَا سَاكِن ___ أَهْلِي.", arabeezy: "ana saken ___ ahli.", cueEn: "with", answer: "مَع" },
                    { prompt: "كُلّ يَوم ___ السَّاعَة سَبْعَة.", arabeezy: "kul yom ___ es-sa3a sab3a.", cueEn: "I wake up", answer: "بَصْحَى" },
                    { prompt: "أَنَا عَطْشَان، بَدِّي ___.", arabeezy: "ana 3atshan, baddi ___.", cueEn: "water", answer: "مَيّ" },
                    { prompt: "لَوْ سَمَحْت، بَنْزَل ___.", arabeezy: "law sama7t, banzal ___.", cueEn: "here", answer: "هِنَا" },
                    { prompt: "هِيَّ ___ فِي غَزَّة.", arabeezy: "hiyyeh ___ fi ghazzeh.", cueEn: "lives (feminine)", answer: "سَاكْنَة" },
                    { prompt: "أَنَا مَا ___ إِخْوَة.", arabeezy: "ana ma ___ ikhweh.", cueEn: "have", answer: "عِنْدِي" },
                    { prompt: "إِنْتِ ___ بَدْرِي كُلّ يَوم.", arabeezy: "inti ___ badri kul yom.", cueEn: "wake up (feminine)", answer: "بِتْصْحِي" },
                    { prompt: "بَدِّي تَلَات ___ فَلَافِل.", arabeezy: "baddi talat ___ falafel.", cueEn: "pieces", answer: "حَبَّات" },
                    { prompt: "رُوح دُغْرِي وُ___ شِمَال.", arabeezy: "roo7 dughri w ___ shmal.", cueEn: "turn", answer: "لِف" },
                ],
                correctTheMistake: [
                    { prompt: "Correct: هِيَّ مْنِيح.", arabeezy: "hiyyeh mneeh.", answer: "هِيَّ مْنِيحَة." },
                    { prompt: "Correct: أَنَا مِش عِنْدِي إِخْوَة.", arabeezy: "ana mish 3indi ikhweh.", answer: "أَنَا مَا عِنْدِي إِخْوَة." },
                    { prompt: "Correct: إِنْتِ بِتْصْحَى بَدْرِي.", arabeezy: "inti btiS7a badri.", answer: "إِنْتِ بِتْصْحِي بَدْرِي." },
                    { prompt: "Correct: السَّلَطَة زَاكِي.", arabeezy: "es-salaTa zaki.", answer: "السَّلَطَة زَاكِيَة." },
                    { prompt: "Correct the verb form to make a command: بِتْلُفّ يَمِين.", arabeezy: "bitluff yameen.", answer: "لِفّ يَمِين." },
                    { prompt: "Correct: هُوَّ سَاكْنَة مَع أَهْلُه.", arabeezy: "huwwe sakneh ma3 ahlo.", answer: "هُوَّ سَاكِن مَع أَهْلُه." },
                ],
                reorderSentences: [
                    { prompt: "Build: I live with my family.", arabeezy: "ana saken ma3 ahli.", words: ["أَنَا سَاكِن", "مَع", "أَهْلِي."], answer: "أَنَا سَاكِن مَع أَهْلِي." },
                    { prompt: "Build: In the morning I drink coffee.", arabeezy: "eS-Subu7 bashrab qahweh.", words: ["الصُّبُح", "بَشْرَب", "قَهْوَة."], answer: "الصُّبُح بَشْرَب قَهْوَة." },
                    { prompt: "Build: Go straight and turn left.", arabeezy: "roo7 dughri w lif shmal.", words: ["رُوح دُغْرِي", "وَلِف", "شِمَال."], answer: "رُوح دُغْرِي وَلِف شِمَال." },
                    { prompt: "Build: She lives with her family.", words: ["هِيَّ سَاكْنَة", "مَع", "أَهْلَهَا."], answer: "هِيَّ سَاكْنَة مَع أَهْلَهَا." },
                    { prompt: "Build: I do not have siblings.", words: ["أَنَا", "مَا عِنْدِي", "إِخْوَة."], answer: "أَنَا مَا عِنْدِي إِخْوَة." },
                    { prompt: "Build: I want three pieces of falafel.", words: ["بَدِّي", "تَلَات حَبَّات", "فَلَافِل."], answer: "بَدِّي تَلَات حَبَّات فَلَافِل." },
                ],
            },
        ],
        translation: [
            { id: "br1_t1", type: "enToAr", textEn: "Hello, how are you?", textAr: "مَرْحَبَا، كِيفَك؟" },
            { id: "br1_t2", type: "arToEn", textEn: "My name is Lina, and I am from Gaza.", textAr: "اِسْمِي لِينَا، وَأَنَا مِن غَزَّة." },
            { id: "br1_t3", type: "enToAr", textEn: "Goodbye, see you later.", textAr: "مَع السَّلَامَة، بِنْشُوفَك بَعْدِين." },
            { id: "br1_t4", type: "arToEn", textEn: "I have a brother and two sisters.", textAr: "عِنْدِي أَخ وَأُخْتِين." },
            { id: "br1_t5", type: "enToAr", textEn: "My sister is younger than me.", textAr: "أُخْتِي أَصْغَر مِنِّي." },
            { id: "br1_t6", type: "arToEn", textEn: "I live with my family.", textAr: "أَنَا سَاكِن/سَاكْنَة مَع أَهْلِي." },
            { id: "br1_t7", type: "enToAr", textEn: "Every day I wake up early.", textAr: "كُلّ يَوم بَصْحَى بَدْرِي." },
            { id: "br1_t8", type: "arToEn", textEn: "After I return, I rest a little.", textAr: "بَعْد مَا بَرْجَع، بَرْتَاح شُوَيّ." },
            { id: "br1_t9", type: "enToAr", textEn: "At night I do not drink coffee.", textAr: "بِاللِّيل مَا بَشْرَب قَهْوَة." },
            { id: "br1_t10", type: "arToEn", textEn: "I am hungry, and I want rice and chicken.", textAr: "أَنَا جَعَان، وَبَدِّي رُزّ وَجَاج." },
            { id: "br1_t11", type: "enToAr", textEn: "I do not like fish.", textAr: "مَا بَحِبّ السَّمَك." },
            { id: "br1_t12", type: "arToEn", textEn: "No thanks, I am full.", textAr: "لَا يِسْلَمُوا، شْبِعِت." },
            { id: "br1_t13", type: "enToAr", textEn: "I take the bus every day.", textAr: "كُلّ يَوم بَرْكَب البَاص." },
            { id: "br1_t14", type: "arToEn", textEn: "How much is the taxi fare?", textAr: "قَدِّيش أُجْرَة التَّاكْسِي؟" },
            { id: "br1_t15", type: "enToAr", textEn: "I get off here, please.", textAr: "بَنْزَل هِنَا، لَوْ سَمَحْت." },
        ],
    },
    homework: { instructions: "Review your mistakes orally. No written homework is required for this checkpoint." },
    teacherNotes: { myNotes: "" },
};
