export const lessonId = "Review-PreIntermediate-Units6-10";

export const lesson = {
    meta: { level: "Pre-Intermediate", unit: "Cumulative Review 2", lessonTitle: "Review Units 6-10", contentVersion: 2026082001, availableTabs: ["overview", "grammar", "practice"] },
    overview: {
        title: "Cumulative Review 2",
        description: "A structured review of work and study, weather, shopping, health, and apartment problems using only language taught through Unit 10.",
        goals: ["Retrieve key vocabulary from Units 6-10.", "Review agreement, comparison, quantities, commands, and location.", "Prepare for the Pre-Intermediate Final."],
        speakingOutcomes: ["The learner can manage five short practical situations with clear Gaza Palestinian Arabic."],
    },
    vocabulary: { core: [], extra: [] },
    dialogue: { title: "Review", setting: "Use the role-plays in Practice.", lines: [] },
    grammar: [
        { title: "Unit 6 — Work and study", short: "بَدْرُس، بِتْشْتَغْلِي، بِشْتِغْلُوا — لَازِم أَكَمِّل", description: "Match the present form to the subject. After لازم، بدّي، and بقدر, the next action appears without the habitual بـ.", examples: [{ ar: "هُمَّ بِشْتِغْلُوا فِي مَكْتَب.", arabeezy: "humme bishtighlu fi maktab.", en: "They work in an office." }, { ar: "لَازِم أَكَمِّل المَشْرُوع اليَوم.", arabeezy: "lazem akammel el-mashroo3 el-yom.", en: "I must finish the project today." }], commonMistakes: ["Use بِشْتِغْلُوا with هُمَّ.", "Do not keep بـ on the second verb after لَازِم."], exercises: [{ prompt: "Complete: هُمَّ ___ فِي المَكْتَب.", options: ["بِشْتِغْلُوا", "بِتْشْتَغِل", "بَشْتِغِل"], correct: "بِشْتِغْلُوا", explanation: "هُمَّ takes the plural ending ـوا." }] },
        { title: "Unit 7 — Weather", short: "الجَوّ مْغَيَّم — أَحْسَن مِن — رَاح يِكُون", description: "Describe weather directly, use مِن after a comparison, and use راح before a future action without habitual بـ.", examples: [{ ar: "الجَوّ اليَوم مْغَيَّم.", arabeezy: "el-jaw el-yom mghayyam.", en: "The weather is cloudy today." }, { ar: "اليَوم أَحْسَن مِن اِمْبَارِح.", arabeezy: "el-yom a7san min imbari7.", en: "Today is better than yesterday." }], commonMistakes: ["Use أَحْسَن مِن, not أَحْسَن عَلَى.", "Keep غَيْم as the noun and مْغَيَّم as the description."], exercises: [{ prompt: "Complete: اليَوم أَحْسَن ___ اِمْبَارِح.", options: ["مِن", "عَلَى", "مَع"], correct: "مِن", explanation: "Direct comparison uses مِن." }] },
        { title: "Unit 8 — Shopping", short: "قَدِّيش هَادَا؟ — نُصّ كِيلُو — مُمْكِن تْنَزِّل شُوَيّ؟", description: "Ask the price, choose a quantity, check size or color, and bargain politely before closing the purchase.", examples: [{ ar: "بَدِّي نُصّ كِيلُو بَنْدُورَة.", arabeezy: "baddi noSS kilo bandora.", en: "I want half a kilo of tomatoes." }, { ar: "هَادَا غَالِي، مُمْكِن تْنَزِّل شُوَيّ؟", arabeezy: "hada ghali, mumkin tnazzel shway?", en: "This is expensive; can you lower it a little?" }], commonMistakes: ["قَدِّيش asks price or amount.", "Match رْخِيص / رْخِيصَة to the item."], exercises: [{ prompt: "Choose: half a kilo.", options: ["نُصّ كِيلُو", "تَلَات قِطَع", "خَمْسِين شِيكِل"], correct: "نُصّ كِيلُو", explanation: "نُصّ means half." }] },
        { title: "Unit 9 — Health", short: "رَاسِي بِيْجَعْنِي — خُدِي حَبَّة — مَا بَقْدَر أَتْنَفَّس", description: "Use a body-part phrase for pain, match an instruction to the listener, and keep emergency language short and clear. Medicine examples are language models, not medical advice.", examples: [{ ar: "رَاسِي بِيْجَعْنِي مِن الصُّبْح.", arabeezy: "rasi biyja3ni min eS-Sub7.", en: "My head has hurt since morning." }, { ar: "مَا بَقْدَر أَتْنَفَّس مْنِيح.", arabeezy: "ma ba2dar atnaffas mnee7.", en: "I cannot breathe well." }], commonMistakes: ["ـنِي marks the person affected.", "Use خُدِي for one woman and خُد for one man."], exercises: [{ prompt: "Choose the instruction to one woman.", options: ["خُدِي حَبَّة.", "خُد حَبَّة.", "خُدُوا حَبَّة."], correct: "خُدِي حَبَّة.", explanation: "The feminine command ends in ـي." }] },
        { title: "Unit 10 — Apartment problems", short: "المَغْسَلَة مَسْدُودَة — المَاسُورَة بْتِنْقُط", description: "Name the exact item, state, and location before requesting help. Match masculine and feminine result descriptions.", examples: [{ ar: "المَغْسَلَة مَسْدُودَة.", arabeezy: "el-maghSale masdoode.", en: "The sink is blocked." }, { ar: "المَاسُورَة تَحْت المَغْسَلَة بْتِنْقُط.", arabeezy: "el-masoora ta7t el-maghSale btin2oT.", en: "The pipe under the sink is dripping." }], commonMistakes: ["Use مَسْدُودَة with the feminine noun المَغْسَلَة.", "A useful complaint names the problem instead of saying only في مشكلة."], exercises: [{ prompt: "Complete: المَغْسَلَة ___.", options: ["مَسْدُودَة", "مَسْدُود", "خَرْبَان"], correct: "مَسْدُودَة", explanation: "The description agrees with the feminine noun." }] },
    ],
    microChecks: { enabled: false, every: 5, items: [] },
    practice: {
        showRealUse: false, showWriting: false, separateExerciseTypes: true,
        quiz: [
            { id: "pr2_q1", questionAr: "Choose: They work in a company.", optionsEn: ["هُمَّ بِشْتِغْلُوا فِي شَرِكَة.", "هُوَّ بِشْتِغِل فِي شَرِكَة.", "إِحْنَا بِنْدْرُس."], correctIndex: 0 },
            { id: "pr2_q2", questionAr: "Complete: I can finish the project.\nبَقْدَر ___ المَشْرُوع.", optionsEn: ["أَكَمِّل", "بَكَمِّل", "بِكَمِّلُوا"], correctIndex: 0 },
            { id: "pr2_q3", questionAr: "Choose: Today is better than yesterday.", optionsEn: ["اليَوم أَحْسَن مِن اِمْبَارِح.", "اليَوم أَحْسَن عَلَى اِمْبَارِح.", "اليَوم مْغَيَّم مِن اِمْبَارِح."], correctIndex: 0 },
            { id: "pr2_q4", questionAr: "Choose: The weather is cloudy.", optionsEn: ["الجَوّ مْغَيَّم.", "الجَوّ غَيْم.", "الجَوّ رُطُوبَة."], correctIndex: 0 },
            { id: "pr2_q5", questionAr: "Choose the phrase for half a kilo.", optionsEn: ["نُصّ كِيلُو", "تَلَات قِطَع", "خَمْسِين شِيكِل"], correctIndex: 0 },
            { id: "pr2_q6", questionAr: "Choose the polite bargaining phrase.", optionsEn: ["مُمْكِن تْنَزِّل شُوَيّ؟", "مُمْكِن تِسَاعِدْنِي؟", "شُو مَالَك؟"], correctIndex: 0 },
            { id: "pr2_q7", questionAr: "Choose: My stomach hurts.", optionsEn: ["بَطْنِي بِيْجَعْنِي.", "رَاسِي بِيْجَعْنِي.", "ضَهْرِي بِيْجَعْنِي."], correctIndex: 0 },
            { id: "pr2_q8", questionAr: "Choose the emergency phrase.", optionsEn: ["مَا بَقْدَر أَتْنَفَّس مْنِيح.", "مَا بَسْتَحْمِل الشُّوب.", "مَا عِنْدِي كَاش."], correctIndex: 0 },
            { id: "pr2_q9", questionAr: "Choose: The sink is blocked.", optionsEn: ["المَغْسَلَة مَسْدُودَة.", "المَغْسَلَة خَرْبَان.", "المَغْسَلَة بْتِنْقُط."], correctIndex: 0 },
            { id: "pr2_q10", questionAr: "Choose the polite housing request.", optionsEn: ["مُمْكِن تِسَاعِدْنِي؟", "آخِر سِعِر؟", "كِيف الجَوّ؟"], correctIndex: 0 },
        ],
        rolePlays: ["Describe your work/study schedule.", "Give a weather update and comparison.", "Buy one item and bargain politely.", "Describe two symptoms at a clinic.", "Report one apartment problem and request help."],
        sections: [{ title: "Controlled Review", matching: [{ ar: "دَوَام", arabeezy: "dawam", en: "shift" }, { ar: "مْغَيَّم", arabeezy: "mghayyam", en: "cloudy" }, { ar: "خَصْم", arabeezy: "khaSm", en: "discount" }, { ar: "دُوخَة", arabeezy: "dookha", en: "dizziness" }, { ar: "مَسْدُود", arabeezy: "masdood", en: "blocked" }], fillInTheBlank: [
            { prompt: "هُمَّ ___ فِي المَكْتَب.", cueEn: "work (they)", answer: "بِشْتِغْلُوا" }, { prompt: "اليَوم أَحْسَن ___ اِمْبَارِح.", cueEn: "than", answer: "مِن" }, { prompt: "بَدِّي نُصّ ___ بَنْدُورَة.", cueEn: "kilo", answer: "كِيلُو" }, { prompt: "رَاسِي بِيْجَع___.", cueEn: "me", answer: "نِي" }, { prompt: "المَغْسَلَة ___.", cueEn: "blocked", answer: "مَسْدُودَة" },
        ], correctTheMistake: [
            { prompt: "Correct: هِيَّ بِشْتِغِل.", answer: "هِيَّ بِتْشْتَغِل." }, { prompt: "Correct: اليَوم أَحْسَن عَلَى اِمْبَارِح.", answer: "اليَوم أَحْسَن مِن اِمْبَارِح." }, { prompt: "Correct: هَادِي رْخِيص.", answer: "هَادِي رْخِيصَة." }, { prompt: "Correct: خُد حَبَّة. (to a woman)", answer: "خُدِي حَبَّة." }, { prompt: "Correct: السَّخَّان خَرْبَانَة.", answer: "السَّخَّان خَرْبَان." },
        ], reorderSentences: [
            { prompt: "Build: They study from Saturday to Thursday.", words: ["هُمَّ بَدْرُسُوا", "مِن السَّبِت", "لِلْخَمِيس."], answer: "هُمَّ بَدْرُسُوا مِن السَّبِت لِلْخَمِيس." }, { prompt: "Build: Today is better than yesterday.", words: ["اليَوم", "أَحْسَن", "مِن اِمْبَارِح."], answer: "اليَوم أَحْسَن مِن اِمْبَارِح." }, { prompt: "Build: I want half a kilo of tomatoes.", words: ["بَدِّي", "نُصّ كِيلُو", "بَنْدُورَة."], answer: "بَدِّي نُصّ كِيلُو بَنْدُورَة." }, { prompt: "Build: My head hurts.", words: ["رَاسِي", "بِيْجَعْنِي."], answer: "رَاسِي بِيْجَعْنِي." }, { prompt: "Build: The sink is blocked.", words: ["المَغْسَلَة", "مَسْدُودَة."], answer: "المَغْسَلَة مَسْدُودَة." },
        ] }],
        translation: [
            { id: "pr2_t1", type: "enToAr", textEn: "They work in an office.", textAr: "هُمَّ بِشْتِغْلُوا فِي مَكْتَب." }, { id: "pr2_t2", type: "arToEn", textEn: "I must finish the project today.", textAr: "لَازِم أَكَمِّل المَشْرُوع اليَوم." }, { id: "pr2_t3", type: "enToAr", textEn: "The weather is cloudy today.", textAr: "الجَوّ مْغَيَّم اليَوم." }, { id: "pr2_t4", type: "arToEn", textEn: "Today is better than yesterday.", textAr: "اليَوم أَحْسَن مِن اِمْبَارِح." }, { id: "pr2_t5", type: "enToAr", textEn: "Take water with you; it is hot.", textAr: "خُد مَعَك مَيّ، الدُّنْيَا شُوب." }, { id: "pr2_t6", type: "arToEn", textEn: "How much is this?", textAr: "قَدِّيش هَادَا؟" }, { id: "pr2_t7", type: "enToAr", textEn: "I want half a kilo of tomatoes.", textAr: "بَدِّي نُصّ كِيلُو بَنْدُورَة." }, { id: "pr2_t8", type: "arToEn", textEn: "I have a card, not cash.", textAr: "مَعِي كَارْت، مِش كَاش." }, { id: "pr2_t9", type: "enToAr", textEn: "My head hurts.", textAr: "رَاسِي بِيْجَعْنِي." }, { id: "pr2_t10", type: "arToEn", textEn: "I have an allergy to a medicine.", textAr: "عِنْدِي حَسَاسِيَّة مِن دَوَا." }, { id: "pr2_t11", type: "enToAr", textEn: "I cannot breathe well.", textAr: "مَا بَقْدَر أَتْنَفَّس مْنِيح." }, { id: "pr2_t12", type: "arToEn", textEn: "How much is the rent per month?", textAr: "قَدِّيش الإِيجَار بِالشَّهْر؟" }, { id: "pr2_t13", type: "enToAr", textEn: "The sink is blocked.", textAr: "المَغْسَلَة مَسْدُودَة." }, { id: "pr2_t14", type: "arToEn", textEn: "The pipe is dripping.", textAr: "المَاسُورَة بْتِنْقُط." }, { id: "pr2_t15", type: "enToAr", textEn: "Can you help me?", textAr: "مُمْكِن تِسَاعِدْنِي؟" },
        ],
    },
    homework: { instructions: "Review incorrect answers orally, then repeat the five role-plays before taking the final assessment." },
    teacherNotes: { myNotes: "" },
};
