export const lessonId = "Assessment-PreIntermediate-Final";

export const lesson = {
    meta: { level: "Pre-Intermediate", unit: "Pre-Intermediate Final", lessonTitle: "Pre-Intermediate Final Assessment", contentVersion: 2026082001, availableTabs: ["overview", "practice"] },
    overview: {
        title: "Pre-Intermediate Final",
        description: "A balanced scored assessment of Units 6-10: four questions from each unit, followed by a teacher-scored speaking task.",
        goals: ["Measure practical control of Units 6-10.", "Measure grammar in clear contexts.", "Identify readiness for Intermediate."],
        speakingOutcomes: ["The learner can connect work, weather, shopping, health, and housing language in one practical situation."],
    },
    vocabulary: { core: [], extra: [] },
    dialogue: { title: "Assessment", setting: "Complete Practice.", lines: [] },
    microChecks: { enabled: false, every: 5, items: [] },
    practice: {
        assessmentMode: true,
        assessmentTitle: "Pre-Intermediate Final",
        questions: [
            { prompt: "Unit 6 — Choose: They work in an office.", options: ["هُمَّ بِشْتِغْلُوا فِي مَكْتَب.", "هُوَّ بِشْتِغِل فِي مَكْتَب.", "إِحْنَا بِنْدْرُس."], correctIndex: 0, skill: "Work: plural present" },
            { prompt: "Unit 6 — Complete: I must finish the project today.\nلَازِم ___ المَشْرُوع اليَوم.", options: ["أَكَمِّل", "بَكَمِّل", "بِكَمِّلُوا"], correctIndex: 0, skill: "Work: لازم + verb" },
            { prompt: "Unit 6 — Choose the feminine form of busy.", options: ["مَشْغُولَة", "مَشْغُولِين", "مُوَظَّف"], correctIndex: 0, skill: "Work: agreement" },
            { prompt: "Unit 6 — Choose the question for: How many hours is your shift?", options: ["كَم سَاعَة دَوَامَك؟", "أَيّ يَوم عِنْدَك؟", "قَدِّيش الإِيجَار؟"], correctIndex: 0, skill: "Work: schedule question" },
            { prompt: "Unit 7 — Choose the correct comparison.", options: ["اليَوم أَحْسَن مِن اِمْبَارِح.", "اليَوم أَحْسَن عَلَى اِمْبَارِح.", "اليَوم أَحْسَن مَع اِمْبَارِح."], correctIndex: 0, skill: "Weather: comparison" },
            { prompt: "Unit 7 — Choose: The weather is cloudy today.", options: ["الجَوّ اليَوم مْغَيَّم.", "الجَوّ اليَوم مَطَر.", "الجَوّ اليَوم رُطُوبَة."], correctIndex: 0, skill: "Weather: description" },
            { prompt: "Unit 7 — Complete: Tomorrow the weather will be sunny.\nبُكْرَا الجَوّ رَاح يِكُون ___.", options: ["مُشْمِس", "شَمْس", "غَيْم"], correctIndex: 0, skill: "Weather: future" },
            { prompt: "Unit 7 — Choose the natural warning when there is rain on the road.", options: ["دِير بَالَك عَالطَّرِيق.", "آخِر سِعِر؟", "عِنْدِي مَوْعِد."], correctIndex: 0, skill: "Weather: advice" },
            { prompt: "Unit 8 — Choose the quantity: half a kilo.", options: ["نُصّ كِيلُو", "تَلَات قِطَع", "نُصّ شِيكِل"], correctIndex: 0, skill: "Shopping: quantity" },
            { prompt: "Unit 8 — Choose the polite bargaining phrase.", options: ["مُمْكِن تْنَزِّل شُوَيّ؟", "مَا بَقْدَر أَتْنَفَّس.", "السَّخَّان خَرْبَان."], correctIndex: 0, skill: "Shopping: bargaining" },
            { prompt: "Unit 8 — Choose: I have a card, not cash.", options: ["مَعِي كَارْت، مِش كَاش.", "مَعِي وَصْل، مِش سِعِر.", "مَعِي مَقَاس، مِش لَوْن."], correctIndex: 0, skill: "Shopping: payment" },
            { prompt: "Unit 8 — Choose the correct feminine sentence.", options: ["هَادِي رْخِيصَة.", "هَادِي رْخِيص.", "هَادَا رْخِيصَة."], correctIndex: 0, skill: "Shopping: agreement" },
            { prompt: "Unit 9 — Choose: My stomach hurts.", options: ["بَطْنِي بِيْجَعْنِي.", "رَاسِي بِيْجَعْنِي.", "ضَهْرِي بِيْجَعْنِي."], correctIndex: 0, skill: "Health: symptom" },
            { prompt: "Unit 9 — Choose the emergency sentence.", options: ["مَا بَقْدَر أَتْنَفَّس مْنِيح.", "مَا بَسْتَحْمِل الشُّوب.", "مَا عِنْدِي وَقْت فَاضِي."], correctIndex: 0, skill: "Health: emergency" },
            { prompt: "Unit 9 — Choose the feminine instruction: Take one pill.", options: ["خُدِي حَبَّة.", "خُد حَبَّة.", "خُدُوا حَبَّة."], correctIndex: 0, skill: "Health: imperative" },
            { prompt: "Unit 9 — Choose: I have an allergy to a medicine.", options: ["عِنْدِي حَسَاسِيَّة مِن دَوَا.", "عِنْدِي دُوخَة مِن شِيكِل.", "عِنْدِي خَصْم مِن دَوَا."], correctIndex: 0, skill: "Health: allergy" },
            { prompt: "Unit 10 — Choose the feminine result state.", options: ["المَغْسَلَة مَسْدُودَة.", "المَغْسَلَة مَسْدُود.", "المَغْسَلَة خَرْبَان."], correctIndex: 0, skill: "Housing: state agreement" },
            { prompt: "Unit 10 — Choose the clearest repair report.", options: ["المَاسُورَة تَحْت المَغْسَلَة بْتِنْقُط.", "فِي مُشْكِلِة هُون.", "الإِشِي مِش مْنِيح."], correctIndex: 0, skill: "Housing: exact report" },
            { prompt: "Unit 10 — Choose the polite request for help.", options: ["مُمْكِن تِسَاعِدْنِي؟", "إِنْتَ غَلْطَان.", "مَا بَدِّي أَحْكِي."], correctIndex: 0, skill: "Housing: polite request" },
            { prompt: "Unit 10 — Complete: How much is the rent per month?\nقَدِّيش ___ بِالشَّهْر؟", options: ["الإِيجَار", "التَّأْمِين", "الطَّابِق"], correctIndex: 0, skill: "Housing: rent" },
        ],
        speaking: {
            prompt: "Speak for 2-3 minutes. Explain your weekly work/study schedule, describe today's weather and compare it with yesterday, buy one item within a budget, describe one health symptom without giving yourself medical advice, then report one apartment problem and request help politely.",
            criteria: ["Completes all five unit tasks", "Uses clear Palestinian pronunciation and connected speech", "Controls pronouns, gender, and plural agreement", "Uses quantity, comparison, and time accurately", "Uses clear questions and polite practical requests"],
            maxScore: 10,
        },
        quiz: [], rolePlays: [], translation: [], sections: [],
    },
    homework: { instructions: "No homework. Use the score and speaking rubric to select targeted review." },
    teacherNotes: { myNotes: "" },
};
