// Practice and translation are kept separate from lesson vocabulary so they can
// test transfer without changing the teacher's vocabulary bank.
const q = (id, questionAr, optionsEn, correctIndex) => ({ id, questionAr, optionsEn, correctIndex });
const t = (id, type, textEn, textAr) => ({ id, type, textEn, textAr });

export const practiceChallengeOverrides = {
    "Beginner-Greetings-L1": {
        quiz: [
            q("greet_x1", "Change the sentence to feminine: إِنْتَ مْنِيح.", ["إِنْتِ مْنِيحَة.", "هِيَّ مْنِيح.", "إِنْتِ مْنِيحِين."], 0),
            q("greet_x2", "Your friend spoke too quickly and you did not understand. What should you say?", ["مَع السَّلَامَة.", "لَوْ سَمَحْت، عِيد السُّؤَال.", "أَنَا مِن كَنَدَا."], 1),
            q("greet_x3", "Change the sentence to “she”: أَنَا سَاكِن فِي غَزَّة.", ["هُوَّ سَاكْنَة فِي غَزَّة.", "هِيَّ سَاكِن فِي غَزَّة.", "هِيَّ سَاكْنَة فِي غَزَّة."], 2),
            q("greet_x4", "Choose the question that gives this answer: أَنَا مِن فَرَنْسَا.", ["كِيفَك؟", "مِن وِين إِنْتَ؟", "وِين سَاكِن؟"], 1),
        ],
        translation: [
            t("greet_xt1", "enToAr", "What is her name and where does she live?", "شُو اِسْمْهَا وَوِين سَاكْنَة؟"),
            t("greet_xt2", "arToEn", "We are from Canada, but now we live in Gaza.", "إِحْنَا مِن كَنَدَا، بَس هَلْقِيت سَاكْنِين فِي غَزَّة."),
            t("greet_xt3", "enToAr", "Please speak slowly; I do not understand the word.", "لَوْ سَمَحْت، اِحْكِي شُوَيّ شُوَيّ؛ أَنَا مِش فَاهِم الكِلْمَة."),
            t("greet_xt4", "arToEn", "Nice to meet you all. See you later.", "تْشَرَّفْنَا فِيكُم. بِنْشُوفْكُم بَعْدِين."),
            t("greet_xt5", "enToAr", "What is your name, and where are you from? (to a woman)", "شُو اِسْمِك، وَإِنْتِ مِن وِين؟"),
            t("greet_xt6", "arToEn", "She is fine, but she is a little tired today.", "هِيَّ مْنِيحَة، بَس تَعْبَانَة شُوَيّ اليَوم."),
            t("greet_xt7", "enToAr", "Good morning. My name is Adam and I live in Cairo.", "صَبَاح الخِير. اِسْمِي آدَم وَأَنَا سَاكِن فِي القَاهِرَة."),
        ],
    },
    "Beginner-Family-L1": {
        quiz: [
            q("family_x1", "Change the sentence to “he”: أَنَا عِنْدِي أُخْتِين.", ["هُوَّ عِنْدُه أُخْتِين.", "هِيَّ عِنْدُه أُخْتِين.", "هُمَّ عِنْدِي أُخْتِين."], 0),
            q("family_x2", "Change the sentence to feminine: هَادَا أَخُوي.", ["هَادَا أُخْتِي.", "هِيَّ أَخُوي.", "هَادِي أُخْتِي."], 2),
            q("family_x3", "Choose the question that asks who this person is: هَادَا أَبُوي.", ["مِين هَادَا؟", "وِين أَبُوي؟", "قَدِّيش عُمْرَك؟"], 0),
            q("family_x4", "Make the sentence negative: إِحْنَا سَاكْنِين مَع سِتِّي.", ["إِحْنَا مِش سَاكْنِين مَع سِتِّي.", "إِحْنَا مَا سَكَنَّا بُكْرَا.", "إِحْنَا لَا سِتِّي."], 0),
        ],
        translation: [
            t("family_xt1", "enToAr", "My brother is married, but my sister is not married.", "أَخُوي مْتْجَوِّز، بَس أُخْتِي مِش مْتْجَوِّزَة."),
            t("family_xt2", "arToEn", "They live with their parents and visit their grandmother on Friday.", "هُمَّ سَاكْنِين مَع أَهْلْهُم وَبِيزُورُوا سِتّْهُم يَوم الجُمْعَة."),
            t("family_xt3", "enToAr", "Who is this woman, and how many children does she have?", "مِين هَادِي المَرَة، وَقَدِّيش عِنْدْهَا وْلَاد؟"),
            t("family_xt4", "arToEn", "We eat with my uncle's family on Friday.", "بِنَاكُل مَع عِيلَة عَمِّي يَوم الجُمْعَة."),
            t("family_xt5", "enToAr", "This is my sister, and this is her son.", "هَادِي أُخْتِي، وَهَادَا اِبْنْهَا."),
            t("family_xt6", "arToEn", "My grandparents live near our house.", "سِيدِي وَسِتِّي سَاكْنِين قَرِيب مِن بِيتْنَا."),
            t("family_xt7", "enToAr", "I do not have brothers, but I have one sister.", "مَا عِنْدِيش إِخْوَان، بَس عِنْدِي أُخْت وَحْدَة."),
        ],
    },
    "Beginner-DailyRoutine-L1": {
        quiz: [
            q("daily_x1", "Change the sentence to feminine: إِنْتَ بِتِصْحَى بَدْرِي.", ["إِنْتِ بِتِصْحَى بَدْرِي.", "إِنْتِ بِتِصْحِي بَدْرِي.", "هِيَّ بِصْحَى بَدْرِي."], 1),
            q("daily_x2", "Choose the question that asks about the time: إِنْتَ بِتْرُوح عَالشُّغُل السَّاعَة تَمَانْيَة.", ["أَيّ سَاعَة بِتْرُوح عَالشُّغُل؟", "وِين سَاكِن؟", "مِين بِتْرُوح؟"], 0),
            q("daily_x3", "Make the sentence negative: هُوَّ بِيشْرَب قَهْوَة الصُّبُح.", ["هُوَّ مِش قَهْوَة.", "هُوَّ مَا بِيشْرَب قَهْوَة الصُّبُح.", "هُوَّ مَا شِرِب بُكْرَا."], 1),
            q("daily_x4", "Change the sentence to “they”: هِيَّ بِتْرَجَع عَالبِيت.", ["هُمَّ بِتْرَجَع عَالبِيت.", "إِحْنَا بَرْجَع عَالبِيت.", "هُمَّ بِيرْجَعُوا عَالبِيت."], 2),
        ],
        translation: [
            t("daily_xt1", "enToAr", "What time do you wake up and leave the house? (to a woman)", "أَيّ سَاعَة بِتِصْحِي وَبِتِطْلَعِي مِن البِيت؟"),
            t("daily_xt2", "arToEn", "He returns home late and does not eat dinner.", "هُوَّ بِيرْجَع عَالبِيت مْتَأَخِّر وَمَا بِيَاكُل عَشَا."),
            t("daily_xt3", "enToAr", "We do not work on Friday; we visit our family.", "إِحْنَا مَا بِنِشْتِغِل يَوم الجُمْعَة؛ بِنْزُور أَهْلْنَا."),
            t("daily_xt4", "arToEn", "After they finish work, they drink coffee together.", "بَعْد مَا يْخَلِّصُوا شُغُل، بِيشْرَبُوا قَهْوَة مَع بَعْض."),
            t("daily_xt5", "enToAr", "She wakes up early and goes to university.", "هِيَّ بِتِصْحَى بَدْرِي وَبِتْرُوح عَالجَامْعَة."),
            t("daily_xt6", "arToEn", "What do you do after work? (to a man)", "شُو بِتِعْمَل بَعْد الشُّغُل؟"),
            t("daily_xt7", "enToAr", "They return home at six and eat dinner together.", "هُمَّ بِيرْجَعُوا عَالبِيت السَّاعَة سِتَّة وَبِيَاكُلُوا عَشَا مَع بَعْض."),
        ],
    },
    "Beginner-Transportation-L1": {
        quiz: [
            q("trans_x1", "The driver asks: وِين بَدَّك تِنْزَل؟ Choose a useful response.", ["عِنْدِي أُخْتِين.", "قُبَال الجَامْعَة، لَوْ سَمَحْت.", "بَحِبّ القَهْوَة."], 1),
            q("trans_x2", "Change the sentence to feminine: إِنْتَ بِتْرْكَب البَاص.", ["إِنْتِ بِتْرَكْبِي البَاص.", "هِيَّ بِتْرْكَبُوا البَاص.", "إِنْتِ بَرْكَب البَاص."], 0),
            q("trans_x3", "Make the sentence negative: أَنَا بَرْكَب البَاص كُلّ يَوم.", ["أَنَا مِش البَاص.", "أَنَا مَا بَرْكَب البَاص كُلّ يَوم.", "أَنَا لَا رْكِبْت البَاص."], 1),
            q("trans_x4", "Choose the command for a group: Go straight.", ["رُوحِي دُغْرِي.", "رُوح دُغْرِي.", "رُوحُوا دُغْرِي."], 2),
        ],
        translation: [
            t("trans_xt1", "enToAr", "How much is the fare, and where should we get off?", "قَدِّيش الأُجْرَة، وَوِين لَازِم نِنْزَل؟"),
            t("trans_xt2", "arToEn", "The bus is late, so we want a taxi.", "البَاص مْتَأَخِّر، عَشَان هِيك بَدّْنَا تَاكْسِي."),
            t("trans_xt3", "enToAr", "Go straight, then turn left after the university. (to a woman)", "رُوحِي دُغْرِي، بَعْدِين لِفِّي شِمَال بَعْد الجَامْعَة."),
            t("trans_xt4", "arToEn", "They do not go to work by bus; they walk.", "هُمَّ مَا بِيرُوحُوا عَالشُّغُل بِالبَاص؛ بِيمْشُوا."),
            t("trans_xt5", "enToAr", "Please stop here in front of the hospital.", "وَقِّف هُون قُبَال المُسْتَشْفَى، لَوْ سَمَحْت."),
            t("trans_xt6", "arToEn", "She takes the bus and gets off near the university.", "هِيَّ بِتِرْكَب البَاص وَبِتِنْزَل قَرِيب مِن الجَامْعَة."),
            t("trans_xt7", "enToAr", "Do you go by taxi or do you walk? (to a man)", "بِتْرُوح بِالتَّاكْسِي وَلَا بِتِمْشِي؟"),
        ],
    },
    "PreInt-WorkStudy-L1": {
        quiz: [
            q("work_x1", "Change the sentence to “she”: أَنَا بَشْتِغِل فِي مَكْتَب.", ["هِيَّ بَشْتِغِل فِي مَكْتَب.", "هِيَّ بِتِشْتِغِل فِي مَكْتَب.", "هُوَّ بِتِشْتِغِل فِي مَكْتَب."], 1),
            q("work_x2", "Choose the best completion: عِنْدِي اِمْتِحَان بُكْرَا، عَشَان هِيك ___.", ["لَازِم أَدْرُس اليَوم.", "بَدِّي مَيّ.", "مَا عِنْدِيش أُخْت."], 0),
            q("work_x3", "Make the sentence negative: هُوَّ بِيقْدَر يْسَاعِدْنَا بَعْد المُحَاضَرَة.", ["هُوَّ مِش مُحَاضَرَة.", "هُوَّ مَا بِيقْدَر يْسَاعِدْنَا بَعْد المُحَاضَرَة.", "هُوَّ مَا سَاعَدْنَا بُكْرَا."], 1),
            q("work_x4", "Choose the question that asks about a schedule: دَوَامِي مِن تَلَاتَة لَسَبْعَة.", ["وِين دَوَامَك؟", "مِن أَيّ سَاعَة لَأَيّ سَاعَة دَوَامَك؟", "مِين فِي الدَّوَام؟"], 1),
        ],
        translation: [
            t("work_xt1", "enToAr", "Where do you work, and what time does your shift start?", "وِين بِتِشْتِغِل، وَأَيّ سَاعَة بِبَلِّش دَوَامَك؟"),
            t("work_xt2", "arToEn", "She studies at university and works part-time.", "هِيَّ بِتِدْرُس فِي الجَامْعَة وَبِتِشْتِغِل دَوَام جُزْئِي."),
            t("work_xt3", "enToAr", "We have an exam, so we have to study tonight.", "عِنْدْنَا اِمْتِحَان، عَشَان هِيك لَازِم نِدْرُس اللَّيْلَة."),
            t("work_xt4", "arToEn", "He cannot attend the meeting because he is busy.", "هُوَّ مَا بِيقْدَر يِحْضَر الاِجْتِمَاع عَشَان مَشْغُول."),
            t("work_xt5", "enToAr", "When do you finish class, and what do you do afterward? (to a woman)", "إِمْتَى بِتْخَلِّصِي الدَّرْس، وَشُو بِتِعْمَلِي بَعْدُه؟"),
            t("work_xt6", "arToEn", "They organize their time and finish their tasks together.", "هُمَّ بِنَظِّمُوا وَقْتْهُم وَبِيخَلِّصُوا مَهَامّْهُم مَع بَعْض."),
            t("work_xt7", "enToAr", "I do not have free time today, but I can help you tomorrow.", "مَا عِنْدِيش وَقْت فَاضِي اليَوم، بَس بَقْدَر أَسَاعْدَك بُكْرَا."),
        ],
    },
    "PreInt-WeatherSmallTalk-L1": {
        quiz: [
            q("weather_x1", "Choose the best description: اليَوم الجَوّ أَبْرَد مِن اِمْبَارِح.", ["Today is warmer than yesterday.", "Today is colder than yesterday.", "Yesterday was windy."], 1),
            q("weather_x2", "Complete the condition: إِذَا الدُّنْيَا شَتَّت، ___.", ["بِنْضَلّ فِي البِيت.", "رُحْنَا عَالبَحَر اِمْبَارِح.", "الجَوّ كَان حَارّ."], 0),
            q("weather_x3", "Change the sentence to “they”: هِيَّ رَاح تَاخُد شَمْسِيَّة.", ["هُمَّ رَاح يَاخْدُوا شَمْسِيَّة.", "هُمَّ رَاح تَاخُد شَمْسِيَّة.", "إِحْنَا أَخَدْنَا شَمْسِيَّة."], 0),
            q("weather_x4", "Choose the natural advice for hot weather.", ["خُد مَعَك جَاكِيت تْقِيل.", "اِشْرَب مَيّ وَمَا تِطْلَع وَقْت الضُّهُر.", "اِفْتَح الشَّمْسِيَّة عَشَان المَطَر."], 1),
        ],
        translation: [
            t("weather_xt1", "enToAr", "How is the weather today compared with yesterday?", "كِيف الجَوّ اليَوم مُقَارَنَة بِاِمْبَارِح؟"),
            t("weather_xt2", "arToEn", "It is cloudy and windy, but it is not cold.", "الدُّنْيَا غَايْمَة وَفِي هَوَا، بَس مِش بَرْد."),
            t("weather_xt3", "enToAr", "If it rains tomorrow, we will stay at home.", "إِذَا شَتَّت بُكْرَا، رَاح نْضَلّ فِي البِيت."),
            t("weather_xt4", "arToEn", "She took a jacket because the evening was cold.", "هِيَّ أَخَدَت جَاكِيت عَشَان المَسَا كَان بَارِد."),
            t("weather_xt5", "enToAr", "Take water with you because the weather is very hot. (to a woman)", "خُدِي مَيّ مَعِك عَشَان الجَوّ حَارّ كْتِير."),
            t("weather_xt6", "arToEn", "In summer, they prefer to go out in the evening.", "فِي الصَّيْف هُمَّ بِفَضِّلُوا يِطْلَعُوا بِالمَسَا."),
            t("weather_xt7", "enToAr", "Was the weather sunny when you went to the sea?", "كَان الجَوّ مُشْمِس لَمَّا رُحْت عَالبَحَر؟"),
        ],
    },
    "PreInt-ShoppingPrices-L1": {
        quiz: [
            q("shop_x1", "Choose the best question for this answer: القَمِيص بِخَمْسِين شِيكِل.", ["قَدِّيش سِعِر القَمِيص؟", "وِين القَمِيص؟", "مِين اِشْتَرَى القَمِيص؟"], 0),
            q("shop_x2", "Change the request to feminine: خُد هَادَا المَقَاس.", ["خُدِي هَادَا المَقَاس.", "خُدُوا هَادَا المَقَاس.", "بِتَاخْدِي هَادَا المَقَاس."], 0),
            q("shop_x3", "Choose the most polite bargaining sentence.", ["هَادَا غَالِي! مَا بَدِّي.", "إِذَا أَخَدْت تْنِين، مُمْكِن تْنَزِّل شُوَيّ؟", "أَعْطِينِي إِيَّاه بِبَلَاش."], 1),
            q("shop_x4", "Complete the condition: إِذَا المَقَاس مَا زَبَط، ___.", ["بَقْدَر أَبَدِّلُه؟", "اِشْتَرَيْتُه اِمْبَارِح.", "السِّعِر خَمْسِين."], 0),
        ],
        translation: [
            t("shop_xt1", "enToAr", "How much is this shirt, and do you have another size?", "قَدِّيش هَادَا القَمِيص، وَعِنْدَك مَقَاس تَانِي؟"),
            t("shop_xt2", "arToEn", "This one is cheaper, but I prefer the black one.", "هَادَا أَرْخَص، بَس أَنَا بِفَضِّل الأَسْوَد."),
            t("shop_xt3", "enToAr", "If I take two, can you lower the price a little?", "إِذَا أَخَدْت تْنِين، مُمْكِن تْنَزِّل السِّعِر شُوَيّ؟"),
            t("shop_xt4", "arToEn", "She bought a gift for her sister and paid cash.", "هِيَّ اِشْتَرَت هَدِيَّة لِأُخْتْهَا وَدَفَعَت كَاش."),
            t("shop_xt5", "enToAr", "We want half a kilo of tomatoes and one kilo of cucumbers.", "بَدّْنَا نُصّ كِيلُو بَنْدُورَة وَكِيلُو خِيَار."),
            t("shop_xt6", "arToEn", "The size did not fit, so they exchanged it.", "المَقَاس مَا زَبَط، عَشَان هِيك هُمَّ بَدَّلُوه."),
            t("shop_xt7", "enToAr", "Can I pay by card, or do you only accept cash?", "بَقْدَر أَدْفَع بِالكَارْت، وَلَا عِنْدْكُم بَس كَاش؟"),
        ],
    },
    "PreInt-HealthEmergencies-L1": {
        quiz: [
            q("health_x1", "Change the sentence to feminine: أَنَا تَعْبَان وَرَاسِي بِيوْجَعْنِي.", ["أَنَا تَعْبَانَة وَرَاسِي بِيوْجَعْنِي.", "هِيَّ تَعْبَان وَرَاسِي بِيوْجَعْنِي.", "أَنَا تَعْبَانِين وَرَاسِي بِيوْجَعْنِي."], 0),
            q("health_x2", "Choose the best question for a patient.", ["قَدِّيش سِعِر القَمِيص؟", "مِن إِمْتَى وَإِنْتَ تَعْبَان؟", "وِين بَدَّك تِنْزَل؟"], 1),
            q("health_x3", "Choose the command for one woman: Take one pill after food.", ["خُد حَبَّة بَعْد الأَكْل.", "خُدُوا حَبَّة بَعْد الأَكْل.", "خُدِي حَبَّة بَعْد الأَكْل."], 2),
            q("health_x4", "Choose the clearest emergency request.", ["مُمْكِن مِيّ؟", "بَدِّي دُكْتُور بِسُرْعَة؛ هُوَّ مَا بِيقْدَر يِتْنَفَّس.", "عِنْدِي مَوْعِد بُكْرَا."], 1),
        ],
        translation: [
            t("health_xt1", "enToAr", "What hurts, and when did the pain start?", "شُو بِيوْجَعَك، وَإِمْتَى بَلَّش الوَجَع؟"),
            t("health_xt2", "arToEn", "She has a fever and has not eaten since morning.", "هِيَّ عِنْدْهَا حَرَارَة وَمَا أَكَلَت مِن الصُّبُح."),
            t("health_xt3", "enToAr", "Take this medicine twice a day after food. (to a man)", "خُد هَادَا الدَّوَا مَرَّتِين فِي اليَوم بَعْد الأَكْل."),
            t("health_xt4", "arToEn", "We went to the pharmacy because my brother was sick.", "رُحْنَا عَالصَّيْدَلِيَّة عَشَان أَخُوي كَان مَرِيض."),
            t("health_xt5", "enToAr", "She cannot breathe well; we need a doctor quickly.", "هِيَّ مَا بِتِقْدَر تِتْنَفَّس مْنِيح؛ بَدّْنَا دُكْتُور بِسُرْعَة."),
            t("health_xt6", "arToEn", "Do not drink coffee tonight, and try to rest. (to a woman)", "مَا تِشْرَبِي قَهْوَة اللَّيْلَة، وَحَاوْلِي تِرْتَاحِي."),
            t("health_xt7", "enToAr", "I have had this pain for three days, but today it is worse.", "صَارْلِي تَلَات أَيَّام عِنْدِي هَادَا الوَجَع، بَس اليَوم أَسْوَأ."),
        ],
    },
    "PreInt-ApartmentProblems-L1": {
        quiz: [
            q("apt_x1", "Choose the clearest way to report the problem.", ["فِي رُطُوبَة وَرَا الخِزَانَة.", "الخِزَانَة مْنِيحَة رُطُوبَة.", "أَنَا بِحِبّ الخِزَانَة."], 0),
            q("apt_x2", "Make the sentence negative: السَّخَّان شَغَّال.", ["السَّخَّان مَا شَغَّل.", "السَّخَّان مِش شَغَّال.", "السَّخَّان لَا شَغَّال اِمْبَارِح."], 1),
            q("apt_x3", "Choose the best completion: المَيّ مَقْطُوعَة، عَشَان هِيك ___.", ["لَازِم نِحْكِي مَع صَاحِب البِيت.", "بَدّْنَا نِشْتَرِي قَمِيص.", "الجَوّ أَبْرَد."], 0),
            q("apt_x4", "Change the report to the past: العَامِل بِيصَلِّح البَاب.", ["العَامِل صَلَّح البَاب.", "العَامِل رَاح يْصَلِّح البَاب.", "العَامِل مِش صَلَّح البَاب."], 0),
        ],
        translation: [
            t("apt_xt1", "enToAr", "There is no hot water, and the heater is not working.", "مَا فِي مَيّ سَاخْنَة، وَالسَّخَّان مِش شَغَّال."),
            t("apt_xt2", "arToEn", "We called the landlord, but he did not answer.", "اِتَّصَلْنَا عَلَى صَاحِب البِيت، بَس هُوَّ مَا رَدّ."),
            t("apt_xt3", "enToAr", "There is dampness behind the closet, and it is getting worse.", "فِي رُطُوبَة وَرَا الخِزَانَة، وَالمُشْكِلَة بِتِزِيد."),
            t("apt_xt4", "arToEn", "The worker came yesterday, but he did not fix the door.", "العَامِل إِجَا اِمْبَارِح، بَس مَا صَلَّح البَاب."),
            t("apt_xt5", "enToAr", "When can you send someone to check the electricity?", "إِمْتَى بِتِقْدَر تِبْعَت حَدَا يْشُوف الكَهْرَبَا؟"),
            t("apt_xt6", "arToEn", "If the problem is not fixed today, we will call again.", "إِذَا المُشْكِلَة مَا اِنْحَلَّت اليَوم، رَاح نِتَّصِل كَمَان مَرَّة."),
            t("apt_xt7", "enToAr", "The apartment is comfortable, but the rent is too expensive.", "الشَّقَّة مُرِيحَة، بَس الإِيجَار غَالِي زِيَادَة."),
        ],
    },
    "Intermediate-Opinions-L1": {
        quiz: [
            q("opinion_x1", "Choose the most polite partial disagreement.", ["إِنْتَ غَلَط.", "مَعَك حَقّ، بَس أَنَا شَايِف المَوْضُوع غِير هِيك.", "أَكِيد أَنَا الصَّحّ."], 1),
            q("opinion_x2", "Complete the opinion with a reason: بِرَأْيِي هَادَا المَكَان أَحْسَن ___.", ["عَشَان أَهْدَى وَأَقْرَب.", "مَع السَّلَامَة.", "اِمْبَارِح السَّاعَة تَمَانْيَة."], 0),
            q("opinion_x3", "Change the sentence to feminine: أَنَا مِش مُقْتَنِع بِهَادَا الرَّأْي.", ["أَنَا مِش مُقْتَنِعَة بِهَادَا الرَّأْي.", "هِيَّ مِش مُقْتَنِعِين بِهَادَا الرَّأْي.", "أَنَا مَا اِقْتَنَعْت بُكْرَا."], 0),
            q("opinion_x4", "Choose the sentence that compares two options clearly.", ["الخِيَار الأَوَّل مْنَاسِب.", "الخِيَار التَّانِي أَرْخَص، بَس الأَوَّل أَرْيَح.", "أَنَا بِحِبّ الخِيَار."], 1),
        ],
        translation: [
            t("opinion_xt1", "enToAr", "In my opinion, the second option is better because it is cheaper.", "بِرَأْيِي، الخِيَار التَّانِي أَحْسَن عَشَان أَرْخَص."),
            t("opinion_xt2", "arToEn", "I agree with you about the price, but not about the location.", "أَنَا مَعَك بِالنِّسْبَة لِلسِّعِر، بَس مِش بِالنِّسْبَة لِلمَكَان."),
            t("opinion_xt3", "enToAr", "She is not completely convinced, although the idea is practical.", "هِيَّ مِش مُقْتَنِعَة مِيَّة بِالمِيَّة، مَع إِنُّه الفِكْرَة عَمَلِيَّة."),
            t("opinion_xt4", "arToEn", "They prefer the quieter apartment even though it is more expensive.", "هُمَّ بِفَضِّلُوا الشَّقَّة الأَهْدَى مَع إِنّْهَا أَغْلَى."),
            t("opinion_xt5", "enToAr", "What makes you think this solution will work?", "شُو اللِّي بِخَلِّيك تِفَكِّر إِنُّه هَادَا الحَلّ رَاح يِزْبَط؟"),
            t("opinion_xt6", "arToEn", "Honestly, I used to agree, but I changed my opinion.", "بِصَرَاحَة، كُنْت مُوَافِق، بَس غَيَّرْت رَأْيِي."),
            t("opinion_xt7", "enToAr", "We can disagree without turning the discussion into a problem.", "بِنَقْدَر نِخْتَلِف مِن غِير مَا نْحَوِّل النِّقَاش لِمُشْكِلَة."),
        ],
    },
    "Intermediate-Complaints-L1": {
        quiz: [
            q("complaint_x1", "Choose the clearest polite complaint.", ["إِنْتُو مَا بِتِفْهَمُوا.", "لَوْ سَمَحْت، الطَّلَب وِصِل نَاقِص وَبَدِّي نْلَاقِي حَلّ.", "مَا بَدِّي أَحْكِي."], 1),
            q("complaint_x2", "Choose the sentence that explains cause and result.", ["الخِدْمَة تْأَخَّرَت، عَشَان هِيك مَا لْحِقْنَا المَوْعِد.", "الخِدْمَة وَالمَوْعِد.", "بُكْرَا الخِدْمَة اِمْبَارِح."], 0),
            q("complaint_x3", "Change the report to “they”: هُوَّ إِجَا، بَس مَا صَلَّح المُشْكِلَة.", ["هُمَّ إِجُوا، بَس مَا صَلَّحُوا المُشْكِلَة.", "هُمَّ إِجَا، بَس مَا صَلَّح المُشْكِلَة.", "إِحْنَا بِنيجِي نْصَلِّح."], 0),
            q("complaint_x4", "Choose the best follow-up when nothing has changed.", ["أَنَا بِتَّصِل عَشَان المُشْكِلَة لِسَّه مَا اِنْحَلَّتْش.", "شُو بِتَاكُل الصُّبُح؟", "الجَوّ اليَوم حِلِو."], 0),
        ],
        translation: [
            t("complaint_xt1", "enToAr", "I am calling because the order arrived late and one item is missing.", "أَنَا بِتَّصِل عَشَان الطَّلَب وِصِل مْتَأَخِّر وَفِي غَرَض نَاقِص."),
            t("complaint_xt2", "arToEn", "They promised to fix the problem, but no one came.", "هُمَّ وَعَدُوا يْصَلِّحُوا المُشْكِلَة، بَس مَا حَدَا إِجَا."),
            t("complaint_xt3", "enToAr", "Could you please check what happened and call me back?", "مُمْكِن لَوْ سَمَحْت تْشُوف شُو صَار وَتِرْجَع تِتَّصِل فِيَّ؟"),
            t("complaint_xt4", "arToEn", "The service was not what we agreed on, so I want a solution.", "الخِدْمَة مَا كَانَت زَيّ مَا اِتَّفَقْنَا، عَشَان هِيك بَدِّي حَلّ."),
            t("complaint_xt5", "enToAr", "If the item cannot be replaced, I would like my money back.", "إِذَا مَا بِتِقْدَرُوا تَبَدِّلُوا الغَرَض، بَدِّي مَصَارِيَّاتِي تِرْجَع."),
            t("complaint_xt6", "arToEn", "She explained the problem calmly, but the employee did not listen.", "هِيَّ شَرَحَت المُشْكِلَة بِهُدُوء، بَس المَوَظَّف مَا سْمِعْهَا."),
            t("complaint_xt7", "enToAr", "This is the second time the same problem has happened.", "هَادِي تَانِي مَرَّة بْتِصِير نَفْس المُشْكِلَة."),
        ],
    },
    "Intermediate-PlansFuture-L1": {
        quiz: [
            q("plans_x1", "Choose the sentence that expresses a future plan.", ["اِمْبَارِح رُحْنَا عَالبَحَر.", "بُكْرَا رَاح نْزُور أَهْلْنَا.", "كُلّ يَوم بِنِشْتِغِل."], 1),
            q("plans_x2", "Complete the condition: إِذَا خَلَّصْت شُغُل بَدْرِي، ___.", ["رَاح أَجِي مَعْكُم.", "كُنْت فِي البِيت.", "مَا رُحْت اِمْبَارِح."], 0),
            q("plans_x3", "Make the future sentence negative: هُمَّ رَاح يِسَافْرُوا يَوم الجُمْعَة.", ["هُمَّ مَا سَافَرُوا يَوم الجُمْعَة.", "هُمَّ مِش رَاح يِسَافْرُوا يَوم الجُمْعَة.", "هُمَّ مِش بِيسَافْرُوا اِمْبَارِح."], 1),
            q("plans_x4", "Choose the sentence that gives a backup plan.", ["إِذَا شَتَّت، بِنْضَلّ فِي البِيت وَبِنِحْضَر فِيلِم.", "إِذَا شَتَّت اِمْبَارِح بُكْرَا.", "الخُطَّة شَتَّت."], 0),
        ],
        translation: [
            t("plans_xt1", "enToAr", "What are you planning to do next weekend?", "شُو مُخَطِّط تِعْمَل نِهَايَة الأُسْبُوع الجَّاي؟"),
            t("plans_xt2", "arToEn", "We are going to meet after work and decide where to go.", "رَاح نِلْتَقِي بَعْد الشُّغُل وَنْقَرِّر وِين نْرُوح."),
            t("plans_xt3", "enToAr", "If she finishes the project, she will travel with us.", "إِذَا خَلَّصَت المَشْرُوع، رَاح تِسَافِر مَعْنَا."),
            t("plans_xt4", "arToEn", "They are not going to stay long because they have work tomorrow.", "هُمَّ مِش رَاح يْضَلُّوا كْتِير عَشَان عِنْدْهُم شُغُل بُكْرَا."),
            t("plans_xt5", "enToAr", "We had planned to go out, but the plan changed.", "كُنَّا مُخَطِّطِين نِطْلَع، بَس الخُطَّة تْغَيَّرَت."),
            t("plans_xt6", "arToEn", "If the first place is full, we have another option.", "إِذَا المَكَان الأَوَّل مَلْيَان، عِنْدْنَا خِيَار تَانِي."),
            t("plans_xt7", "enToAr", "Call me when you know the final time.", "اِتَّصِل فِيَّ لَمَّا تِعْرَف الوَقْت النِّهَائِي."),
        ],
    },
    "Intermediate-Hobbies-L1": {
        quiz: [
            q("hobby_x1", "Choose the question that asks about duration: صَارْلِي سَنَتِين بَتْعَلَّم عَزْف.", ["مِن إِمْتَى وَإِنْتَ بِتْعَلَّم عَزْف؟", "وِين بِتْعَلَّم؟", "مِين بِتْعَلَّم؟"], 0),
            q("hobby_x2", "Change the sentence to “she”: أَنَا بَمَارِس الرِّيَاضَة مَرَّتِين فِي الأُسْبُوع.", ["هِيَّ بَمَارِس الرِّيَاضَة.", "هِيَّ بِتْمَارِس الرِّيَاضَة مَرَّتِين فِي الأُسْبُوع.", "هُمَّ بِتْمَارِس الرِّيَاضَة."], 1),
            q("hobby_x3", "Choose the sentence that contrasts the past with the present.", ["كُنْت أَلْعَب كُرَة قَدِيم، بَس هَلْقِيت بِفَضِّل المَشْي.", "بُكْرَا كُنْت أَلْعَب.", "أَنَا هِوَايَة كُرَة."], 0),
            q("hobby_x4", "Complete the reason: بَحِبّ القِرَايَة ___.", ["عَشَان بِتْسَاعِدْنِي أَرْتَاح وَأَتْعَلَّم.", "بَعْدِين اِمْبَارِح.", "مَا عِنْدِيش قِرَايَة."], 0),
        ],
        translation: [
            t("hobby_xt1", "enToAr", "How long have you been learning to play the guitar?", "صَارْلَك قَدِّيش بِتْتَعَلَّم تِعْزَف غِيتَار؟"),
            t("hobby_xt2", "arToEn", "She exercises twice a week because it improves her mood.", "هِيَّ بِتْمَارِس الرِّيَاضَة مَرَّتِين فِي الأُسْبُوع عَشَان بِتْحَسِّن نَفْسِيَّتْهَا."),
            t("hobby_xt3", "enToAr", "I used to play football, but now I prefer swimming.", "كُنْت أَلْعَب كُرَة قَدِيم، بَس هَلْقِيت بِفَضِّل السِّبَاحَة."),
            t("hobby_xt4", "arToEn", "They joined a photography group and met new people.", "هُمَّ اِنْضَمُّوا لِمَجْمُوعَة تَصْوِير وَتْعَرَّفُوا عَلَى نَاس جْدَاد."),
            t("hobby_xt5", "enToAr", "If I have free time this weekend, I will finish the book.", "إِذَا عِنْدِي وَقْت فَاضِي نِهَايَة الأُسْبُوع، رَاح أَخَلِّص الكِتَاب."),
            t("hobby_xt6", "arToEn", "What hobby would you like to try, and why?", "أَيّ هِوَايَة بْتِحِبّ تْجَرِّب، وَلِيش؟"),
            t("hobby_xt7", "enToAr", "Reading helps me relax after a long day at work.", "القِرَايَة بِتْسَاعِدْنِي أَرْتَاح بَعْد يَوم طْوِيل فِي الشُّغُل."),
        ],
    },
    "Intermediate-Feelings & Mental State": {
        quiz: [
            q("feeling_x1", "Change the sentence to feminine: أَنَا مَضْغُوط وَمِحْتَاج أَرْتَاح.", ["أَنَا مَضْغُوطَة وَمِحْتَاجَة أَرْتَاح.", "هِيَّ مَضْغُوط وَمِحْتَاج.", "أَنَا مَضْغُوطِين."], 0),
            q("feeling_x2", "Choose the most supportive response: أَنَا قَلْقَان مِن النَّتِيجَة.", ["مَا إِلَك حَقّ تِقْلَق.", "بَفْهَم عَلَيْك؛ إِذَا بَدَّك، اِحْكِيلِي أَكْتَر.", "غَيِّر المَوْضُوع."], 1),
            q("feeling_x3", "Choose the sentence that shows a change of state.", ["لَمَّا سَمِعْت الخَبَر، صِرْت أَهْدَى.", "أَنَا خَبَر أَهْدَى.", "بُكْرَا كُنْت أَهْدَى اِمْبَارِح."], 0),
            q("feeling_x4", "Complete the reason naturally: هِيَّ زَعْلَانَة ___.", ["عَشَان صَاحْبْتْهَا مَا رَدَّت عَلِيهَا.", "عَشَان رَاح تِفْرَح اِمْبَارِح.", "زَعْلَانَة المَكَان."], 0),
        ],
        translation: [
            t("feeling_xt1", "enToAr", "I have been stressed for several days because of work.", "صَارْلِي كَمّ يَوم مَضْغُوط عَشَان الشُّغُل."),
            t("feeling_xt2", "arToEn", "She was worried, but she became calmer after the phone call.", "هِيَّ كَانَت قَلْقَانَة، بَس صَارَت أَهْدَى بَعْد المُكَالَمَة."),
            t("feeling_xt3", "enToAr", "I understand how you feel. Do you want to talk about it?", "أَنَا فَاهِم كِيف حَاسِس. بَدَّك تِحْكِي عَن المَوْضُوع؟"),
            t("feeling_xt4", "arToEn", "They felt disappointed because the plan changed at the last minute.", "هُمَّ حَسُّوا بِخَيْبَة أَمَل عَشَان الخُطَّة تْغَيَّرَت بِآخِر لَحْظَة."),
            t("feeling_xt5", "enToAr", "When I feel overwhelmed, I take a break and speak with someone I trust.", "لَمَّا أَحِسّ حَالِي مَضْغُوط زِيَادَة، بَاخُد اِسْتِرَاحَة وَبَحْكِي مَع حَدَا بِوثَق فِيه."),
            t("feeling_xt6", "arToEn", "What happened that made you feel this way? (to a woman)", "شُو صَار وَخَلَّاكِ تِحِسِّي هِيك؟"),
            t("feeling_xt7", "enToAr", "Even though he was tired, he tried to stay positive.", "مَع إِنُّه كَان تَعْبَان، حَاوَل يْضَلّ إِيجَابِي."),
        ],
    },
    "Review-Beginner-Units1-5": {
        quiz: [
            q("br_x1", "Choose the best reply: كِيفَك اليَوم؟", ["أَنَا مْنِيح، الحَمْدُ لله.", "مِن وِين؟", "مَع أَهْلِي."], 0),
            q("br_x2", "Change the sentence to feminine: أَنَا سَاكِن فِي غَزَّة.", ["أَنَا سَاكِنِين فِي غَزَّة.", "أَنَا سَاكْنَة فِي غَزَّة.", "هُوَّ سَاكْنَة فِي غَزَّة."], 1),
            q("br_x3", "Change the sentence to “he”: أَنَا عِنْدِي أَخ وَأُخْت.", ["هِيَّ عِنْدُهَا أَخ وَأُخْت.", "هُمَّ عِنْدْهُم أَخ وَأُخْت.", "هُوَّ عِنْدُه أَخ وَأُخْت."], 2),
            q("br_x4", "Choose the question that asks who this person is: هَادَا أَخُوي.", ["مِين هَادَا؟", "وِين أَخُوي؟", "قَدِّيش عُمْرَك؟"], 0),
            q("br_x5", "Make the sentence negative: أَنَا بَشْرَب قَهْوَة بِاللِّيل.", ["أَنَا مِش قَهْوَة بِاللِّيل.", "أَنَا مَا بَشْرَب قَهْوَة بِاللِّيل.", "أَنَا لَا شِرِبْت قَهْوَة."], 1),
            q("br_x6", "Change the sentence to feminine: إِنْتَ بِتْصْحَى بَدْرِي.", ["إِنْتِ بِتْصْحَى بَدْرِي.", "هِيَّ بِتْصْحِي بَدْرِي.", "إِنْتِ بِتْصْحِي بَدْرِي."], 2),
            q("br_x7", "Your guest says: أَنَا عَطْشَان. Choose a helpful response.", ["تْفَضَّل مَيّ.", "قَدِّيش الأُجْرَة؟", "وِين سَاكِن؟"], 0),
            q("br_x8", "Choose the polite refusal when you are full.", ["بَدِّي كَمَان.", "لَا يِسْلَمُوا، شِبْعِت.", "أَنَا جَعَان."], 1),
            q("br_x9", "The driver asks: وِين بَدَّك تِنْزَل؟ Choose a useful response.", ["أَنَا مِن كَنَدَا.", "بَحِبّ الفَلَافِل.", "قُبَال الجَامْعَة، لَوْ سَمَحْت."], 2),
            q("br_x10", "Choose the command for one woman: Go straight and turn right.", ["رُوحِي دُغْرِي وَلِفِّي يَمِين.", "رُوح دُغْرِي وَلِف يَمِين.", "رُوحُوا دُغْرِي وَلِفُّوا يَمِين."], 0),
        ],
        rolePlays: [
            "Meet a new classmate. Introduce yourself, ask two questions, and talk briefly about your family and daily routine.",
            "Your classmate visits your home. Offer food and drink, then explain how to travel from your home to the university.",
        ],
        sections: [
            {
                title: "Mixed transformation review",
                fillInTheBlank: [
                    { prompt: "Change to she: أَنَا بَشْرَب شَاي. — هِيَّ ___ شَاي.", answer: "بِتْشْرَب" },
                    { prompt: "Make it negative: إِحْنَا سَاكْنِين مَع سِتِّي. — إِحْنَا ___ سَاكْنِين مَع سِتِّي.", answer: "مِش" },
                    { prompt: "Complete the question: ___ الأُجْرَة؟", cueEn: "how much", answer: "قَدِّيش" },
                    { prompt: "Command one woman: ___ مَيّ.", cueEn: "drink", answer: "اِشْرَبِي" },
                    { prompt: "Complete: أَنَا عَطْشَان، ___ مَيّ.", cueEn: "I want", answer: "بَدِّي" },
                ],
                correctTheMistake: [
                    { prompt: "Correct the gender: هِيَّ مْنِيح.", answer: "هِيَّ مْنِيحَة." },
                    { prompt: "Correct the person: هُوَّ عِنْدِي أُخْتِين.", answer: "هُوَّ عِنْدُه أُخْتِين." },
                    { prompt: "Correct the verb: إِنْتِ بِتْرُوح عَالجَامْعَة.", answer: "إِنْتِ بِتْرُوحِي عَالجَامْعَة." },
                    { prompt: "Correct the negation: أَنَا مِش بَحِبّ السَّمَك.", answer: "أَنَا مَا بَحِبّ السَّمَك." },
                    { prompt: "Correct the command to a woman: رُوح دُغْرِي.", answer: "رُوحِي دُغْرِي." },
                ],
                reorderSentences: [
                    { prompt: "Build: Where are you from?", words: ["إِنْتَ", "مِن", "وِين؟"], answer: "إِنْتَ مِن وِين؟" },
                    { prompt: "Build: She lives with her family.", words: ["مَع أَهْلْهَا.", "هِيَّ", "سَاكْنَة"], answer: "هِيَّ سَاكْنَة مَع أَهْلْهَا." },
                    { prompt: "Build: We do not drink coffee at night.", words: ["قَهْوَة", "إِحْنَا", "مَا بِنِشْرَب", "بِاللِّيل."], answer: "إِحْنَا مَا بِنِشْرَب قَهْوَة بِاللِّيل." },
                    { prompt: "Build: I want bread and cheese.", words: ["خُبِز", "بَدِّي", "وَجُبْنَة."], answer: "بَدِّي خُبِز وَجُبْنَة." },
                    { prompt: "Build: Go straight, then turn left.", words: ["بَعْدِين", "رُوح دُغْرِي،", "لِف شِمَال."], answer: "رُوح دُغْرِي، بَعْدِين لِف شِمَال." },
                ],
            },
        ],
        translation: [
            t("br_xt1", "enToAr", "What is your name, and where do you live? (to a woman)", "شُو اِسْمِك، وَوِين سَاكْنَة؟"),
            t("br_xt2", "arToEn", "He has two sisters and lives with his family.", "هُوَّ عِنْدُه أُخْتِين وَسَاكِن مَع أَهْلُه."),
            t("br_xt3", "enToAr", "We wake up early, but we do not drink coffee.", "إِحْنَا بِنِصْحَى بَدْرِي، بَس مَا بِنِشْرَب قَهْوَة."),
            t("br_xt4", "arToEn", "My sister is hungry and wants bread and cheese.", "أُخْتِي جَعَانَة وَبَدَّهَا خُبِز وَجُبْنَة."),
            t("br_xt5", "enToAr", "Please drink some water. (to a woman)", "لَوْ سَمَحْت، اِشْرَبِي شُوَيّ مَيّ."),
            t("br_xt6", "arToEn", "They take the bus and get off near the university.", "هُمَّ بِيرْكَبُوا البَاص وَبِينْزَلُوا قَرِيب مِن الجَامْعَة."),
            t("br_xt7", "enToAr", "Go straight and stop in front of the hospital. (to a man)", "رُوح دُغْرِي وَوَقِّف قُبَال المُسْتَشْفَى."),
        ],
    },
    "Assessment-Beginner-Final": {
        questions: [
            { prompt: "Choose the best reply: كِيفَك اليَوم؟", options: ["مِن وِين؟", "أَنَا مْنِيح، الحَمْدُ لله.", "مَع السَّلَامَة."], correctIndex: 1, skill: "Greetings" },
            { prompt: "Choose the question that asks where someone is from: أَنَا مِن كَنَدَا.", options: ["وِين سَاكِن؟", "كِيفَك؟", "مِن وِين إِنْتَ؟"], correctIndex: 2, skill: "Introduction" },
            { prompt: "Change the sentence to feminine: أَنَا سَاكِن فِي غَزَّة.", options: ["أَنَا سَاكْنَة فِي غَزَّة.", "هِيَّ سَاكِن فِي غَزَّة.", "أَنَا سَاكِنِين فِي غَزَّة."], correctIndex: 0, skill: "Gender" },
            { prompt: "Change the sentence to “he”: أَنَا عِنْدِي أَخ وَأُخْت.", options: ["هِيَّ عِنْدْهَا أَخ وَأُخْت.", "هُوَّ عِنْدُه أَخ وَأُخْت.", "هُوَّ عِنْدِي أَخ وَأُخْت."], correctIndex: 1, skill: "Family possession" },
            { prompt: "Choose the correct sentence about a sister.", options: ["هَادَا أُخْتِي.", "هَادِي أُخْتِي.", "هَادِي أَخُوي."], correctIndex: 1, skill: "Demonstratives" },
            { prompt: "Make the sentence negative: إِحْنَا سَاكْنِين مَع سِتِّي.", options: ["إِحْنَا مَا سَكَنَّا بُكْرَا.", "إِحْنَا لَا سِتِّي.", "إِحْنَا مِش سَاكْنِين مَع سِتِّي."], correctIndex: 2, skill: "Nominal negation" },
            { prompt: "Change the sentence to feminine: إِنْتَ بِتْصْحَى بَدْرِي.", options: ["إِنْتِ بِتْصْحِي بَدْرِي.", "إِنْتِ بِتْصْحَى بَدْرِي.", "هِيَّ بِتْصْحِي بَدْرِي."], correctIndex: 0, skill: "Present tense" },
            { prompt: "Choose the question that asks about time: بَرُوح عَالشُّغُل السَّاعَة تَمَانْيَة.", options: ["وِين بِتْرُوح؟", "مِين بِيرُوح؟", "أَيّ سَاعَة بِتْرُوح عَالشُّغُل؟"], correctIndex: 2, skill: "Time questions" },
            { prompt: "Make the sentence negative: هُوَّ بِيشْرَب قَهْوَة بِاللِّيل.", options: ["هُوَّ مِش قَهْوَة.", "هُوَّ مَا بِيشْرَب قَهْوَة بِاللِّيل.", "هُوَّ لَا قَهْوَة بِاللِّيل."], correctIndex: 1, skill: "Verbal negation" },
            { prompt: "Your guest says: أَنَا جَعَان. Choose a helpful response.", options: ["تْفَضَّل كُل.", "قَدِّيش الأُجْرَة؟", "وِين سَاكِن؟"], correctIndex: 0, skill: "Food situation" },
            { prompt: "Change the sentence to feminine: أَنَا عَطْشَان وَبَدِّي مَيّ.", options: ["أَنَا عَطْشَانِين وَبَدِّي مَيّ.", "هِيَّ عَطْشَان وَبَدِّي مَيّ.", "أَنَا عَطْشَانَة وَبَدِّي مَيّ."], correctIndex: 2, skill: "Food agreement" },
            { prompt: "Choose the polite refusal when you do not want more food.", options: ["بَدِّي كَمَان.", "لَا يِسْلَمُوا، شِبْعِت.", "أَنَا عَطْشَان."], correctIndex: 1, skill: "Hospitality" },
            { prompt: "The driver asks: وِين بَدَّك تِنْزَل؟ Choose a useful response.", options: ["قُبَال الجَامْعَة، لَوْ سَمَحْت.", "عِنْدِي أُخْتِين.", "بَحِبّ الجَاج."], correctIndex: 0, skill: "Transportation" },
            { prompt: "Choose the command for one woman: Go straight.", options: ["رُوح دُغْرِي.", "رُوحِي دُغْرِي.", "رُوحُوا دُغْرِي."], correctIndex: 1, skill: "Directions" },
            { prompt: "Choose the question that asks for the fare.", options: ["وِين الأُجْرَة؟", "مِين الأُجْرَة؟", "قَدِّيش الأُجْرَة؟"], correctIndex: 2, skill: "Transport questions" },
        ],
    },
    "Review-PreIntermediate-Units6-10": {
        quiz: [
            q("pr_x1", "Choose the best completion: عِنْدِي اِمْتِحَان بُكْرَا، عَشَان هِيك ___.", ["لَازِم أَدْرُس اليَوم.", "بَدِّي أَبَدِّل القَمِيص.", "السَّخَّان مِش شَغَّال."], 0),
            q("pr_x2", "Change the sentence to “they”: هِيَّ بِتِشْتِغِل فِي مَكْتَب.", ["هُمَّ بِتِشْتِغِل فِي مَكْتَب.", "هُمَّ بِيشْتِغِلُوا فِي مَكْتَب.", "إِحْنَا بِنِشْتِغِل فِي مَكْتَب."], 1),
            q("pr_x3", "Choose the correct comparison: اليَوم الجَوّ ___.", ["أَبْرَد عَلَى اِمْبَارِح.", "أَبْرَد مَع اِمْبَارِح.", "أَبْرَد مِن اِمْبَارِح."], 2),
            q("pr_x4", "Complete the condition: إِذَا الدُّنْيَا شَتَّت، ___.", ["بِنْضَلّ فِي البِيت.", "رُحْنَا عَالسُّوق اِمْبَارِح.", "الجَوّ مِش شَغَّال."], 0),
            q("pr_x5", "Choose the most polite bargaining sentence.", ["هَادَا غَالِي؛ خَلَاص.", "إِذَا أَخَدْت تْنِين، مُمْكِن تْنَزِّل شُوَيّ؟", "أَعْطِينِي إِيَّاه بِبَلَاش."], 1),
            q("pr_x6", "Choose the correct sentence about a feminine item.", ["هَادَا الشَّنْطَة الأَسْوَد.", "هَادِي القَمِيص السُّودَا.", "هَادِي الشَّنْطَة السُّودَا."], 2),
            q("pr_x7", "Choose the command for one woman: Take one pill after food.", ["خُدِي حَبَّة بَعْد الأَكْل.", "خُد حَبَّة بَعْد الأَكْل.", "خُدُوا حَبَّة بَعْد الأَكْل."], 0),
            q("pr_x8", "Choose the clearest emergency request.", ["عِنْدِي مَوْعِد بُكْرَا.", "بَدِّي دُكْتُور بِسُرْعَة؛ مَا بَقْدَر أَتْنَفَّس.", "الجَوّ أَلْطَف اليَوم."], 1),
            q("pr_x9", "Make the sentence negative: السَّخَّان شَغَّال.", ["السَّخَّان مَا شَغَّل بُكْرَا.", "السَّخَّان لَا شَغَّال.", "السَّخَّان مِش شَغَّال."], 2),
            q("pr_x10", "Change the report to the past: العَامِل بِيصَلِّح البَاب.", ["العَامِل صَلَّح البَاب.", "العَامِل رَاح يْصَلِّح البَاب.", "العَامِل مِش بِيصَلِّح البَاب."], 0),
        ],
        rolePlays: [
            "Explain your work or study schedule, then discuss how weather can change your plans.",
            "Buy a household item, ask for a lower price, then call the landlord to report a health or repair problem clearly.",
        ],
        sections: [
            {
                title: "Mixed practical review",
                fillInTheBlank: [
                    { prompt: "Complete: هُمَّ ___ فِي الجَامْعَة.", cueEn: "study (they)", answer: "بِيدْرُسُوا" },
                    { prompt: "Complete the comparison: اليَوم أَدْفَى ___ اِمْبَارِح.", cueEn: "than", answer: "مِن" },
                    { prompt: "Complete: بَدِّي ___ كِيلُو بَنْدُورَة.", cueEn: "half", answer: "نُصّ" },
                    { prompt: "Complete: رَاسِي بِيوْجَع___.", cueEn: "me", answer: "نِي" },
                    { prompt: "Complete: فِي رُطُوبَة ___ الخِزَانَة.", cueEn: "behind", answer: "وَرَا" },
                ],
                correctTheMistake: [
                    { prompt: "Correct the person: هِيَّ بِشْتِغِل فِي مَكْتَب.", answer: "هِيَّ بِتِشْتِغِل فِي مَكْتَب." },
                    { prompt: "Correct the comparison: اليَوم أَحْسَن عَلَى اِمْبَارِح.", answer: "اليَوم أَحْسَن مِن اِمْبَارِح." },
                    { prompt: "Correct the demonstrative: هَادَا الشَّنْطَة السُّودَا.", answer: "هَادِي الشَّنْطَة السُّودَا." },
                    { prompt: "Correct the command to a woman: خُد حَبَّة.", answer: "خُدِي حَبَّة." },
                    { prompt: "Correct the agreement: المَغْسَلَة مَسْدُود.", answer: "المَغْسَلَة مَسْدُودَة." },
                ],
                reorderSentences: [
                    { prompt: "Build: They work from Sunday to Thursday.", words: ["مِن الأَحَد", "هُمَّ بِيشْتِغِلُوا", "لِلْخَمِيس."], answer: "هُمَّ بِيشْتِغِلُوا مِن الأَحَد لِلْخَمِيس." },
                    { prompt: "Build: If it rains, we will stay home.", words: ["رَاح نْضَلّ بِالبِيت.", "إِذَا شَتَّت،", "إِحْنَا"], answer: "إِذَا شَتَّت، إِحْنَا رَاح نْضَلّ بِالبِيت." },
                    { prompt: "Build: Can you lower the price a little?", words: ["السِّعِر", "مُمْكِن", "شُوَيّ؟", "تْنَزِّل"], answer: "مُمْكِن تْنَزِّل السِّعِر شُوَيّ؟" },
                    { prompt: "Build: Take this medicine twice a day. (to a woman)", words: ["مَرَّتِين فِي اليَوم.", "خُدِي", "هَادَا الدَّوَا"], answer: "خُدِي هَادَا الدَّوَا مَرَّتِين فِي اليَوم." },
                    { prompt: "Build: There is dampness behind the closet.", words: ["وَرَا الخِزَانَة.", "فِي", "رُطُوبَة"], answer: "فِي رُطُوبَة وَرَا الخِزَانَة." },
                ],
            },
        ],
        translation: [
            t("pr_xt1", "enToAr", "She studies at university and works part-time.", "هِيَّ بِتِدْرُس فِي الجَامْعَة وَبِتِشْتِغِل دَوَام جُزْئِي."),
            t("pr_xt2", "arToEn", "If it rains tomorrow, we will stay at home.", "إِذَا شَتَّت بُكْرَا، رَاح نْضَلّ فِي البِيت."),
            t("pr_xt3", "enToAr", "If I take two shirts, can you lower the price?", "إِذَا أَخَدْت قَمِيصِين، مُمْكِن تْنَزِّل السِّعِر؟"),
            t("pr_xt4", "arToEn", "She has had a fever since morning and needs a doctor.", "عِنْدْهَا حَرَارَة مِن الصُّبُح وَمِحْتَاجَة دُكْتُور."),
            t("pr_xt5", "enToAr", "Take one pill after food and drink plenty of water. (to a woman)", "خُدِي حَبَّة بَعْد الأَكْل وَاِشْرَبِي مَيّ كْتِير."),
            t("pr_xt6", "arToEn", "The worker came, but he did not fix the heater.", "العَامِل إِجَا، بَس مَا صَلَّح السَّخَّان."),
            t("pr_xt7", "enToAr", "There is no hot water, so we called the landlord.", "مَا فِي مَيّ سَاخْنَة، عَشَان هِيك اِتَّصَلْنَا عَلَى صَاحِب البِيت."),
        ],
    },
    "Assessment-PreIntermediate-Final": {
        questions: [
            { prompt: "Change the sentence to “they”: هِيَّ بِتِشْتِغِل فِي مَكْتَب.", options: ["هُمَّ بِيشْتِغِلُوا فِي مَكْتَب.", "هُمَّ بِتِشْتِغِل فِي مَكْتَب.", "إِحْنَا بِنِشْتِغِل فِي مَكْتَب."], correctIndex: 0, skill: "Work and study" },
            { prompt: "Choose the best completion: عِنْدِي اِمْتِحَان، عَشَان هِيك ___.", options: ["السِّعِر غَالِي.", "لَازِم أَدْرُس.", "السَّخَّان خَرْبَان."], correctIndex: 1, skill: "Obligation" },
            { prompt: "Choose the question that asks about a schedule: دَوَامِي مِن تَلَاتَة لَسَبْعَة.", options: ["وِين دَوَامَك؟", "مِين فِي الدَّوَام؟", "مِن أَيّ سَاعَة لَأَيّ سَاعَة دَوَامَك؟"], correctIndex: 2, skill: "Schedule" },
            { prompt: "Choose the correct comparison: اليَوم الجَوّ ___.", options: ["أَلْطَف مِن اِمْبَارِح.", "أَلْطَف عَلَى اِمْبَارِح.", "أَلْطَف مَع اِمْبَارِح."], correctIndex: 0, skill: "Comparison" },
            { prompt: "Complete the condition: إِذَا شَتَّت بُكْرَا، ___.", options: ["رُحْنَا عَالبَحَر.", "رَاح نْضَلّ فِي البِيت.", "الجَوّ كَان حَارّ."], correctIndex: 1, skill: "Weather condition" },
            { prompt: "Choose the natural advice for very hot weather.", options: ["خُد جَاكِيت تْقِيل.", "اِفْتَح الشَّمْسِيَّة عَشَان المَطَر.", "اِشْرَب مَيّ وَمَا تِطْلَع وَقْت الضُّهُر."], correctIndex: 2, skill: "Weather advice" },
            { prompt: "Choose the best question for this answer: القَمِيص بِخَمْسِين شِيكِل.", options: ["قَدِّيش سِعِر القَمِيص؟", "وِين القَمِيص؟", "مِين اِشْتَرَى القَمِيص؟"], correctIndex: 0, skill: "Shopping" },
            { prompt: "Choose the most polite bargaining sentence.", options: ["هَادَا غَالِي!", "إِذَا أَخَدْت تْنِين، مُمْكِن تْنَزِّل شُوَيّ؟", "أَعْطِينِي إِيَّاه بِبَلَاش."], correctIndex: 1, skill: "Bargaining" },
            { prompt: "Choose the sentence with correct feminine agreement.", options: ["هَادَا الشَّنْطَة الأَسْوَد.", "هَادِي القَمِيص السُّودَا.", "هَادِي الشَّنْطَة السُّودَا."], correctIndex: 2, skill: "Shopping agreement" },
            { prompt: "Choose the best question for a patient.", options: ["مِن إِمْتَى وَإِنْتَ تَعْبَان؟", "قَدِّيش سِعِر القَمِيص؟", "وِين بَدَّك تِنْزَل؟"], correctIndex: 0, skill: "Health questions" },
            { prompt: "Choose the command for one woman: Take one pill after food.", options: ["خُد حَبَّة بَعْد الأَكْل.", "خُدِي حَبَّة بَعْد الأَكْل.", "خُدُوا حَبَّة بَعْد الأَكْل."], correctIndex: 1, skill: "Health instruction" },
            { prompt: "Choose the clearest emergency request.", options: ["عِنْدِي مَوْعِد بُكْرَا.", "بَدِّي دَوَا بَعْدِين.", "بَدِّي دُكْتُور بِسُرْعَة؛ مَا بَقْدَر أَتْنَفَّس."], correctIndex: 2, skill: "Emergency" },
            { prompt: "Choose the clearest housing report.", options: ["فِي رُطُوبَة وَرَا الخِزَانَة.", "فِي مُشْكِلَة هُون.", "الإِشِي مِش مْنِيح."], correctIndex: 0, skill: "Housing location" },
            { prompt: "Make the sentence negative: السَّخَّان شَغَّال.", options: ["السَّخَّان مَا شَغَّل بُكْرَا.", "السَّخَّان مِش شَغَّال.", "السَّخَّان لَا شَغَّال."], correctIndex: 1, skill: "Result state" },
            { prompt: "Change the report to the past: العَامِل بِيصَلِّح البَاب.", options: ["العَامِل رَاح يْصَلِّح البَاب.", "العَامِل مِش بِيصَلِّح البَاب.", "العَامِل صَلَّح البَاب."], correctIndex: 2, skill: "Past report" },
        ],
    },
    "Review-Intermediate-Units11-15": {
        quiz: [
            q("ir_x1", "Choose the most polite partial disagreement.", ["إِنْتَ غَلَط.", "مَعَك حَقّ، بَس أَنَا شَايِف المَوْضُوع غِير هِيك.", "مَا بَدِّي أَسْمَع."], 1),
            q("ir_x2", "Choose the sentence that compares two options clearly.", ["التَّانِي أَرْخَص، بَس الأَوَّل أَرْيَح.", "الخِيَار أَرْخَص عَلَى.", "أَنَا خِيَار مْنِيح."], 0),
            q("ir_x3", "Change the report to “they”: هُوَّ وَعَدْنِي يْصَلِّح المُشْكِلَة.", ["هُمَّ وَعَدْتْهُم يْصَلِّحُوا.", "هُمَّ وَعَدُونِي يْصَلِّحُوا المُشْكِلَة.", "إِحْنَا وَعَدْنَا المُشْكِلَة."], 1),
            q("ir_x4", "Choose the sentence with a clear cause and result.", ["الخِدْمَة تْأَخَّرَت، عَشَان هِيك مَا لْحِقْنَا المَوْعِد.", "الخِدْمَة عَشَان المَوْعِد.", "مَا لْحِقْنَا لَأَنّ عَشَان هِيك."], 0),
            q("ir_x5", "Make the future sentence negative: هُمَّ رَاح يِسَافْرُوا بُكْرَا.", ["هُمَّ مَا سَافَرُوا بُكْرَا.", "هُمَّ مِش رَاح يِسَافْرُوا بُكْرَا.", "هُمَّ مِش بِيسَافْرُوا اِمْبَارِح."], 1),
            q("ir_x6", "Complete the backup plan: إِذَا المَكَان مَلْيَان، ___.", ["رُحْنَا عَلِيه اِمْبَارِح.", "مَا فِي مَكَان.", "بِنْرُوح عَلَى مَكَان تَانِي."], 2),
            q("ir_x7", "Choose the question that asks about duration: صَارْلِي سَنَتِين بَتْعَلَّم عَزْف.", ["مِن إِمْتَى وَإِنْتَ بِتْتَعَلَّم عَزْف؟", "وِين بِتْتَعَلَّم؟", "مِين عَلَّمَك اِمْبَارِح؟"], 0),
            q("ir_x8", "Choose the sentence that contrasts the past with the present.", ["بُكْرَا كُنْت أَلْعَب.", "كُنْت أَلْعَب كُرَة، بَس هَلْقِيت بِفَضِّل المَشْي.", "أَنَا كُرَة وَمَشْي."], 1),
            q("ir_x9", "Choose the most supportive response: أَنَا قَلْقَان مِن النَّتِيجَة.", ["مَا إِلَك حَقّ تِقْلَق.", "غَيِّر المَوْضُوع.", "بَفْهَم عَلَيْك؛ إِذَا بَدَّك، اِحْكِيلِي أَكْتَر."], 2),
            q("ir_x10", "Choose the sentence that shows an emotional change.", ["لَمَّا سَمِعْت الخَبَر، صِرْت أَهْدَى.", "أَنَا خَبَر أَهْدَى.", "بُكْرَا كُنْت أَهْدَى اِمْبَارِح."], 0),
        ],
        rolePlays: [
            "Compare two options and defend your choice while responding politely to a different opinion.",
            "Describe a complaint, explain what happened and how you felt, then give your future plan if it happens again.",
        ],
        sections: [
            {
                title: "Connected language review",
                fillInTheBlank: [
                    { prompt: "Complete the comparison: هَادَا أَرْيَح ___ الأَوَّل.", cueEn: "than", answer: "مِن" },
                    { prompt: "Complete: هُمَّ ___ يْصَلِّحُوا المُشْكِلَة.", cueEn: "promised me", answer: "وَعَدُونِي" },
                    { prompt: "Complete the negative future: أَنَا ___ أَتْأَخَّر.", cueEn: "will not", answer: "مِش رَاح" },
                    { prompt: "Complete the duration: ___ سَنَتِين بَتْعَلَّم عَزْف.", answer: "صَارْلِي" },
                    { prompt: "Complete the change: لَمَّا سَمِعْت الخَبَر، ___ أَهْدَى.", answer: "صِرْت" },
                ],
                correctTheMistake: [
                    { prompt: "Correct the comparison: هَادِي أَهْدَى عَلَى الأُولَى.", answer: "هَادِي أَهْدَى مِن الأُولَى." },
                    { prompt: "Correct the performer: هُمَّ حَكَيْنَا مَع المَسْؤُول.", answer: "هُمَّ حَكُوا مَع المَسْؤُول." },
                    { prompt: "Correct the future: بُكْرَا رُحْت عَالمَوْعِد.", answer: "بُكْرَا رَاح أَرُوح عَالمَوْعِد." },
                    { prompt: "Correct the timeline: صَارْلِي سَنَتِين تْعَلَّمْت عَزْف.", answer: "صَارْلِي سَنَتِين بَتْعَلَّم عَزْف." },
                    { prompt: "Correct the past state: اِمْبَارِح أَنَا مَضْغُوط.", answer: "اِمْبَارِح كُنْت مَضْغُوط." },
                ],
                reorderSentences: [
                    { prompt: "Build a balanced opinion.", words: ["مَعَك حَقّ،", "بَس", "رَأْيِي مُخْتَلِف."], answer: "مَعَك حَقّ، بَس رَأْيِي مُخْتَلِف." },
                    { prompt: "Build: They promised me they would solve it.", words: ["إِنَّهُم", "وَعَدُونِي", "رَاح يِحِلُّوهَا."], answer: "وَعَدُونِي إِنَّهُم رَاح يِحِلُّوهَا." },
                    { prompt: "Build: If the plan does not work, we will change it.", words: ["رَاح نْغَيِّرْهَا.", "إِذَا الخُطَّة مَا زَبَطَت،", "إِحْنَا"], answer: "إِذَا الخُطَّة مَا زَبَطَت، إِحْنَا رَاح نْغَيِّرْهَا." },
                    { prompt: "Build: I have been exercising for a year.", words: ["بَتْمَرَّن.", "صَارْلِي", "سَنَة"], answer: "صَارْلِي سَنَة بَتْمَرَّن." },
                    { prompt: "Build: I was worried, but I became calmer.", words: ["بَس", "كُنْت قَلْقَان،", "صِرْت أَهْدَى."], answer: "كُنْت قَلْقَان، بَس صِرْت أَهْدَى." },
                ],
            },
        ],
        translation: [
            t("ir_xt1", "enToAr", "I understand your opinion, but I prefer the second option.", "أَنَا فَاهِم رَأْيَك، بَس بِفَضِّل الخِيَار التَّانِي."),
            t("ir_xt2", "arToEn", "They promised me they would call, but nobody called.", "وَعَدُونِي يِتَّصِلُوا، بَس مَا حَدَا اِتَّصَل."),
            t("ir_xt3", "enToAr", "If the problem happens again, I will file a complaint.", "إِذَا المُشْكِلَة صَارَت كَمَان مَرَّة، رَاح أَقَدِّم شَكْوَى."),
            t("ir_xt4", "arToEn", "I used to play football, but now I prefer swimming.", "كُنْت أَلْعَب كُرَة، بَس هَلْقِيت بِفَضِّل السِّبَاحَة."),
            t("ir_xt5", "enToAr", "She has been learning oud for two years and still practices every day.", "صَارْلْهَا سَنَتِين بِتْتَعَلَّم عُود وَلِسَّهَا بِتْتَمَرَّن كُلّ يَوم."),
            t("ir_xt6", "arToEn", "I was waiting for the reply, and when they called me, I felt relieved.", "كُنْت عَم بَسْتَنَّى الرَّدّ، وَلَمَّا اِتَّصَلُوا فِيَّ اِرْتَحْت."),
            t("ir_xt7", "enToAr", "I was stressed, so I took a break and became calmer.", "كُنْت مَضْغُوط، عَشَان هِيك أَخَدْت اِسْتِرَاحَة وَصِرْت أَهْدَى."),
        ],
    },
    "Assessment-Intermediate-Final": {
        questions: [
            { prompt: "Choose the most polite partial disagreement.", options: ["إِنْتَ غَلَط.", "مَعَك حَقّ، بَس رَأْيِي مُخْتَلِف.", "مَا بَدِّي أَسْمَع."], correctIndex: 1, skill: "Opinion" },
            { prompt: "Choose the sentence that compares two options clearly.", options: ["التَّانِي أَرْخَص، بَس الأَوَّل أَرْيَح.", "الأَوَّل أَرْيَح عَلَى التَّانِي.", "الخِيَار أَرْخَص مِن."], correctIndex: 0, skill: "Comparison" },
            { prompt: "Choose the sentence that explains a reason.", options: ["تْأَخَّرْت عَشَان البَاص مَا إِجَا.", "تْأَخَّرْت عَشَان هِيك البَاص.", "البَاص تْأَخَّر بَعْدِين لَأَنّ."], correctIndex: 0, skill: "Reason" },
            { prompt: "Choose the clearest polite complaint.", options: ["إِنْتُو مَا بِتِفْهَمُوا.", "مَا بَدِّي أَحْكِي.", "الطَّلَب وِصِل نَاقِص وَبَدِّي نْلَاقِي حَلّ."], correctIndex: 2, skill: "Complaint" },
            { prompt: "Choose the meaning of: بَعَتْنَالْهُم الصُّوَر.", options: ["They sent us the photos.", "We sent them the photos.", "I sent her the photos."], correctIndex: 1, skill: "Object pronouns" },
            { prompt: "Change the report to “they”: هُوَّ وَعَدْنِي يِيجِي.", options: ["هُمَّ وَعَدُونِي يِيجُوا.", "هُمَّ وَعَدْتْهُم يِيجُوا.", "إِحْنَا وَعَدْنَا يِيجِي."], correctIndex: 0, skill: "Past plural" },
            { prompt: "Make the future sentence negative: أَنَا رَاح أَتْأَخَّر.", options: ["أَنَا مَا تْأَخَّرْت.", "أَنَا مِش مُتْأَخِّر.", "أَنَا مِش رَاح أَتْأَخَّر."], correctIndex: 2, skill: "Future negation" },
            { prompt: "Complete the condition: إِذَا الخُطَّة مَا زَبَطَت، ___.", options: ["رَاح نْغَيِّرْهَا.", "غَيَّرْنَاهَا اِمْبَارِح.", "الخُطَّة مِش رَاح."], correctIndex: 0, skill: "Condition" },
            { prompt: "Choose the sentence that gives a backup plan.", options: ["الخُطَّة التَّانْيَة اِمْبَارِح.", "إِذَا المَكَان مَلْيَان، بِنْرُوح عَلَى مَكَان تَانِي.", "مَا فِي خُطَّة عَشَان."], correctIndex: 1, skill: "Backup plan" },
            { prompt: "Choose the question that asks about duration: صَارْلِي سَنَتِين بَتْمَرَّن.", options: ["وِين بِتْتَمَرَّن؟", "مِين بِتْمَرَّن؟", "صَارْلَك قَدِّيش بِتْتَمَرَّن؟"], correctIndex: 2, skill: "Duration" },
            { prompt: "Choose the sentence that contrasts the past with the present.", options: ["كُنْت أَلْعَب كُرَة، بَس هَلْقِيت بِفَضِّل المَشْي.", "بُكْرَا كُنْت أَلْعَب.", "أَنَا كُرَة وَمَشْي."], correctIndex: 0, skill: "Past habit" },
            { prompt: "Choose the most supportive response: أَنَا مَضْغُوط كْتِير.", options: ["مَا إِلَك حَقّ.", "بَفْهَم عَلَيْك؛ بَدَّك تِحْكِي عَن المَوْضُوع؟", "خَلَاص، غَيِّر المَوْضُوع."], correctIndex: 1, skill: "Supportive language" },
            { prompt: "Choose the sentence that shows an emotional change.", options: ["أَنَا خَبَر أَهْدَى.", "بُكْرَا كُنْت قَلْقَان.", "لَمَّا سَمِعْت الخَبَر، صِرْت أَهْدَى."], correctIndex: 2, skill: "Emotional change" },
            { prompt: "Choose the sentence where a completed event interrupts an ongoing action.", options: ["كُنْت عَم بَسْتَنَّى لَمَّا اِتَّصَلُوا فِيَّ.", "كُلّ يَوم بَسْتَنَّى.", "بُكْرَا رَاح أَسْتَنَّى."], correctIndex: 0, skill: "Narrative sequence" },
            { prompt: "Choose the most logical connected narrative.", options: ["بُكْرَا اِمْبَارِح كُنْت.", "كُنْت قَلْقَان، وَلَمَّا حَكُوا إِنُّه المُشْكِلَة اِنْحَلَّت صِرْت أَهْدَى.", "عَشَان هِيك قَبْل مَا بَعْدِين."], correctIndex: 1, skill: "Connected narration" },
        ],
    },
};
