import { LESSON_ID_SHOPPING } from '../../constants.js';

export const lessonId = LESSON_ID_SHOPPING;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Shopping & Prices",
        lessonTitle: "Unit 8 - Shopping, Markets & Prices in Gaza Palestinian Arabic",
        contentVersion: 2026082001,
    },

    overview: {
        title: "Unit 8 - Shopping, Markets & Prices",
        description:
            "Students learn how to shop naturally in Gaza Palestinian Arabic: ask prices, compare quality, ask for size/color, bargain politely, buy by kilo or piece, and pay cash or card.",
        goals: [
            "Ask and answer about prices clearly.",
            "Use numbers, quantities, colors, size, and money in real shopping situations.",
            "Bargain politely without sounding rude.",
            "Say if something is expensive, cheap, suitable, or too much.",
            "Recycle previous units: greetings, weather, transport, food, family, work/study, time, and politeness.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can buy something from a shop or market.",
            "The student can ask for another size/color and compare prices.",
            "The student can bargain in a simple natural way and complete payment.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "dukkan",
                ar: "دُكّان",
                en: "corner shop / mini-market",
                enArabeezy: "dukkān / dukkan",
                hint: "Small neighbourhood shop for basic groceries and stuff.",
                exampleAr: "أَبُوي بَعَث أَخُوي عَالدُّكّان يِشْتِرِي زَيْت وَحْلِيب.",
                exampleArabeezy: "aboy ba3ath akhoy 3al-dukkan yishtiri zet w 7leeb.",
                exampleEn: "My father sent my brother to the corner shop to buy oil and milk.",
            },
            {
                id: "ma7al",
                ar: "مَحَلّ",
                en: "shop / store",
                enArabeezy: "ma7all / maḥall",
                hint: "General word for any shop. Plural: مَحَلّات.",
                exampleAr: "هُمَّ فَتَحُوا مَحَلّ أَوَاعِي جْدِيد بِالسُّوق.",
                exampleArabeezy: "humma fata7o ma7all awa3i jdeed bis-souq.",
                exampleEn: "They opened a new clothes shop in the market.",
            },
            {
                id: "souk",
                ar: "سُوق",
                en: "market",
                enArabeezy: "souq",
                hint: "Traditional market or shopping street. In Gaza, السوق is used for clothes, vegetables, and daily needs.",
                exampleAr: "إِحْنَا نَازْلِين عَالسُّوق نِشْتِرِي بندورة وَخَضْرَة.",
                exampleArabeezy: "i7na nazleen 3as-souq nishtiri banadoora w khaDra.",
                exampleEn: "We are going down to the market to buy tomatoes and vegetables.",
            },
            {
                id: "baddi_ashtiri",
                ar: "بَدّي أِشْتِري...",
                en: "I want to buy...",
                enArabeezy: "baddi ashtiri...",
                hint: "Good opener with the seller: بَدّي أِشْتِري بنْطَلُون / هَدِيّة...",
                exampleAr: "أَخُوي نَازِل عَالسُّوق عَالْشَان بِدُّو يِشْتِرِي كِيلُو مَوْز.",
                exampleArabeezy: "akhoy nazel 3as-souq 3alshan biddo yishtiri keelo mawz",
                exampleEn: "My brother is going down to the market because he wants to buy a kilo of bananas.",
            },

            {
                id: "se3er",
                ar: "سِعِر",
                en: "price",
                enArabeezy: "se3er",
                hint: "Common chunks: السِّعِر غَالِي، السِّعِر مْنِيح، آخِر سِعِر؟",
                exampleAr: "شَافُوا السِّعِر غَالِي كَثِير فِي المَحَلّ.",
                exampleArabeezy: "shafo es-se3er ghali katheer fil-ma7all.",
                exampleEn: "They saw the price was very expensive in the shop.",
            },
            {
                id: "mnasib",
                ar: "مْنَاسِب / مْنَاسْبَة",
                en: "suitable / fair",
                enArabeezy: "mnasib / mnasbe",
                hint: "Useful for price, size, color, and timing.",
                exampleAr: "إِذَا السِّعِر مْنَاسِب إِلِي، بَاخُدْه.",
                exampleArabeezy: "iza es-se3er mnasib ili, bakhodoh.",
                exampleEn: "If the price is suitable for me, I'll take it.",
            },
            {
                id: "tanzeelat",
                ar: "تَنْزِيلَات",
                en: "sales / discounts",
                enArabeezy: "tanzeelat",
                hint: "Common in shops. Also: خَصْم = discount.",
                exampleAr: "المَحَلّ عَامِل تَنْزِيلَات عَكُلّ المَلَابِس هَالأُسْبُوع.",
                exampleArabeezy: "el-ma7all 3amel tanzeelat 3a koll el-malabes hal-osboo3.",
                exampleEn: "The shop has sales on all clothes this week.",
            },
            {
                id: "khasm",
                ar: "خَصْم",
                en: "discount",
                enArabeezy: "khasm",
                hint: "Ask politely: فِي خَصْم؟ / فِي خَصْم لِلْطُلَّاب؟",
                exampleAr: "إِذَا بَاخُد قِطْعَتَيْن، فِيه خَصْم؟",
                exampleArabeezy: "iza bakhod qi6a3teen, feeh khasm?",
                exampleEn: "If I take two items, is there a discount?",
            },
            {
                id: "ra3eeni_shway",
                ar: "رَاعِينِي شُوَيّ",
                en: "Give me a discount / Be easy on the price",
                enArabeezy: "ra3eeni_shway",
                hint: "A very polite and natural way to bargain. It literally means 'be considerate of me a little'.",
                exampleAr: "السِّعِر أَعْلَى مِن مِيزَانِيَّتِي، رَاعِينِي شُوَيّ.",
                exampleArabeezy: "es-se3er a3la min mizaniyyti, ra3eeni shway.",
                exampleEn: "The price is higher than my budget, give me a little discount.",
            },
            {
                id: "min_el_akher",
                ar: "مِن الآخِر",
                en: "The final price / Bottom line",
                enArabeezy: "min_el_akher",
                hint: "Used by the buyer to ask for the absolute lowest price without playing the bargaining game.",
                exampleAr: "إِذَا بَدّي أَخُدْه هَلْقِيت، قَدِّيش حَقّه مِن الآخِر؟",
                exampleArabeezy: "iza baddi akhdo halla2, addeesh 7a22o min el-akher?",
                exampleEn: "If I'm going to take it now, what's the final price?",
            },
            {
                id: "ma_bitwaffi_ma3ay",
                ar: "مَا بِتْوَفّي مَعَاي",
                en: "It doesn't pay / It's not profitable for me",
                enArabeezy: "ma_bitwaffi_ma3ay",
                hint: "Sellers use this when a customer's offer is too low, meaning they would lose money on the sale.",
                exampleAr: "لَا، بِهَالسِّعِر مَا بِتْوَفّي مَعَاي، أَنَا شَارِي أَغْلَى مِن هَيْك.",
                exampleArabeezy: "la, b-hal-se3er ma bitwaffi ma3ay, ana shari aghla min heik.",
                exampleEn: "No, at that price it doesn't work for me; I bought it for more than that.",
            },
            {
                id: "khalleeha_3aleena",
                ar: "خَلِّيهَا عَلِينَا",
                en: "It's on us (It's free)",
                enArabeezy: "khalleeha_3aleena",
                hint: "A polite cultural gesture by the seller offering it for free. The buyer MUST politely refuse and insist on paying.",
                exampleAr: "خَلِّيهَا عَلِينَا، مَا بَدْنَا نَحْسِبْهَا مَعَ بَقِيّة الأَغْرَاض.",
                exampleArabeezy: "khalliha 3aleena, ma badna n7sebha ma3 ba2yet el-aghraD.",
                exampleEn: "It's on us; we won't charge you for it with the rest of the items.",
            },
            {
                id: "akher_si3ir",
                ar: "آخِر سِعِر",
                en: "Last price",
                enArabeezy: "akher_si3ir",
                hint: "Often used by the seller to tell the buyer that bargaining is over.",
                exampleAr: "صَاحِب المَحَلّ حَكَالْنَا: هَادَا آخِر سِعِر بَعْد الخَصْم.",
                exampleArabeezy: "Sa7ib el-ma7all 7akalna: hada akher si3ir ba3d el-khasm.",
                exampleEn: "The shop owner told us: This is the last price after the discount.",
            },
            {
                id: "masari",
                ar: "مَصَارِي",
                en: "Money",
                enArabeezy: "masari",
                hint: "The main Palestinian word for money. It is treated as plural in Arabic.",
                exampleAr: "مَعِي مَصَارِي كَاش، بَسّ مَا مَعِي فَكّة.",
                exampleArabeezy: "ma3i maSari cash, bas ma3iSh fakkeh.",
                exampleEn: "I have cash, but I don't have small change.",
            },

            {
                id: "fakkeh",
                ar: "فَكَّة",
                en: "Change (small bills or coins)",
                enArabeezy: "fakkeh",
                hint: "Used when you need to break a large bill or ask if the seller has smaller change.",
                exampleAr: "إِخْوَنّي سَأَلُوا فِي الدُّكّان: مَعَكُم فَكَّة خَمْسِين شِيكِل؟",
                exampleArabeezy: "ikhwan-ni sa'alo fid-dukkan: ma3akum fakkeh khamseen shekel?",
                exampleEn: "My brothers asked in the corner shop: Do you have change for a fifty-shekel bill?",
            },
            {
                id: "baqi",
                ar: "بَاقِي",
                en: "The rest (of the money) / change returned",
                enArabeezy: "baqi",
                hint: "Refers to the money the seller hands back to the customer after payment.",
                exampleAr: "أُخْتِي نِسْيَت تَاوْخُد البَاقِي مِن صَاحِب المَحَلّ.",
                exampleArabeezy: "okhti nesyat tawkhud el-baqi min Sa7ib el-ma7all.",
                exampleEn: "My sister forgot to take the change back from the shop owner.",
            },
            {
                id: "wasl",
                ar: "وَصْل ",
                en: "receipt",
                enArabeezy: "waṣl / bawn",
                hint: "Paper you get after paying. Useful if you want to return something.",
                exampleAr: "هُمَّ أَخَذُوا الوَصْل عَشَان يْرَجَّعُوا القِطْعَة إِذَا المَقَاس مِش مْنَاسِب.",
                exampleArabeezy: "humma akhado el-wasl 3ashan yrajje3o el-qiT3a iza el-ma2as mish mnasib.",
                exampleEn: "They took the receipt so they can return the item if the size isn't suitable.",
            },
            {
                id: "fatora_shop",
                ar: "فاتورَة",
                en: "invoice / bill",
                enArabeezy: "fātūra / fatora",
                hint: "More official than وَصْل, especially for big purchases or deliveries.",
                exampleAr: "أَبُوي طَلَب الفَاتُورَة بَعْد مَا شَتَرَى الأَوَاعِي.",
                exampleArabeezy: "aboy Talab el-fatora ba3d ma shtara el-awa3i.",
                exampleEn: "My father asked for the invoice after buying the clothes.",
            },
            {
                id: "7ajm",
                ar: "حَجِم / مَقاس",
                en: "size",
                enArabeezy: "7ajm / maqās",
                hint: "حَجِم for general size, مَقاس for clothes & shoes.",
                exampleAr: "صَاحْبِي بِدَّو مَقَاس أَكْبَر شُوَيّ مِن هَادَا البِنْطَلُون.",
                exampleArabeezy: "Sa7bi biddo ma2as akbar shway min hada el-binTaloon.",
                exampleEn: "My friend wants a slightly bigger size than these pants.",
            },
            {
                id: "lawn",
                ar: "لَوْن",
                en: "color",
                enArabeezy: "lawn",
                hint: "Plural: أَلْوان. Very common in clothes & shoes shopping.",
                exampleAr: "بِحِبّ هَادَا اللَّوْن، بَسّ عِنْدَك نَفْس القَمِيص بِلَوْن أَسْوَد؟",
                exampleArabeezy: "b7ebb hada el-lawn, bas 3andak nafs el-qamees b-lawn aswad?",
                exampleEn: "I like this color, but do you have the same shirt in black?",
            },
            {
                id: "no3",
                ar: "نَوْع",
                en: "type / kind",
                enArabeezy: "nawʿ / no3",
                hint: "What kind: نوع القَمِيص، نوع القَهْوِة، نوع القِماش.",
                exampleAr: "إِحْنَا بْنَدَوِّر عَ نَفْس النَّوْع هَادَا بِالسُّوق.",
                exampleArabeezy: "i7na bnndawwer 3a nafs en-no3 hada bis-souq.",
                exampleEn: "We are looking for this exact same type in the market.",
            },
            {
                id: "jawde",
                ar: "جَوْدَة",
                en: "quality",
                enArabeezy: "jawde",
                hint: "High quality = جَوْدَة عَالْيَة. Low quality = جَوْدَة عَادِيَّة.",
                exampleAr: "أُمّي حَكَت إِنّو الجَوْدَة كَثِير مْنِيحَة بِهَادَا المَحَلّ.",
                exampleArabeezy: "ummi 7akat inno el-jawde katheer mnee7a bi-hada el-ma7all.",
                exampleEn: "My mother said that the quality is very good in this shop.",
            },
            {
                id: "kilo",
                ar: "كِيلُو",
                en: "kilo",
                enArabeezy: "keelo",
                hint: "Used in food markets: fruits, vegetables, meat, cheese.",
                exampleAr: "أَخَذْنَا كِيلُو وَنُصّ بَنَادُورَة مِن السُّوق.",
                exampleArabeezy: "akhadna keelo w noSS banadoora min es-souq.",
                exampleEn: "We took a kilo and a half of tomatoes from the market.",
            },
            {
                id: "qiT3a",
                ar: "قِطْعَة",
                en: "piece / item",
                enArabeezy: "2iT3a",
                hint: "Plural: قِطَع. Used for clothes, sweets, cheese, and items.",
                exampleAr: "هُوَّ اختَار آخِر قِطْعَة فِي المَحَلّ.",
                exampleArabeezy: "huwwa ikhtar akher qiT3a fil-ma7all.",
                exampleEn: "He chose the last piece in the shop.",
            },
            {
                id: "kamm",
                ar: "كَمّ؟",
                en: "how many?",
                enArabeezy: "kam?",
                hint: "Use for quantity. Price question uses قَدِّيش؟",
                exampleAr: "سَأَلُوهَا: كَمّ كِيلُو بَدِّك تِشْتِرِي؟",
                exampleArabeezy: "sa'aloha: kam keelo baddek tishtiri?",
                exampleEn: "They asked her: How many kilos do you want to buy?",
            },
            {
                id: "3indak_tani",
                ar: "عِنْدَك إِشِي تَانِي؟",
                en: "Do you have something else?",
                enArabeezy: "3indak ishi tani?",
                hint: "Use for another model, size, color, or option.",
                exampleAr: "أُخْتِي سَأَلَت البَايِع: عِنْدَك إِشِي تَانِي لَوْنُه غِير؟",
                exampleArabeezy: "okhti sa'alat el-baye3: 3indak ishi tani lawno gheer?",
                exampleEn: "My sister asked the seller: Do you have something else in a different color?",
            },
            {
                id: "bas_batfarraj",
                ar: "أَنَا بَس بَتْفَرَّج",
                en: "I'm just looking",
                enArabeezy: "ana bas batfarraj",
                hint: "Polite phrase when seller approaches and you are not ready to buy.",
                exampleAr: "شُكْرًا، أَنَا بَس بَتْفَرَّج هَلْقِيت، إِذَا لَقِيت إِشِي مْنَاسِب بَسْأَلَك.",
                exampleArabeezy: "shokran, ana bas batfarraj halla2, iza la2eit ishi mnasib bas2alak.",
                exampleEn: "Thanks, I'm just looking for now. If I find something suitable, I'll ask you.",
            },
            {
                id: "khallih",
                ar: "خَلِّيه",
                en: "make it / let it be",
                enArabeezy: "khallih",
                hint: "Useful in bargaining: خَلِّيه بِخَمْسِين = make it fifty.",
                exampleAr: "حَكَيْنَا لِلْبَايِع: خَلِّيه بِعِشْرِين شِيكِل وَبْنَاخُدُه هَلْقِيت.",
                exampleArabeezy: "7akeena lil-baye3: khallih bi-3ishreen shekel w bnakholdo halqeet.",
                exampleEn: "We told the seller: Make it twenty shekels and we'll take it right now.",
            },

        ],
    },

    dialogue: {
        title: "Shopping, Markets & Prices - At the Market",
        setting: "Rami and Mona go shopping to buy a gift and then buy vegetables at the local market.",
        lines: [
            { speaker: "Rami", ar: "مُونَا، تَعَالِي هُون شُوَي.", arArabeezy: "mona, ta3ali hoon shway.", en: "Mona, come here for a second." },
            { speaker: "Mona", ar: "شُو لْقِيت؟", arArabeezy: "shoo l2eet?", en: "What did you find?" },
            { speaker: "Rami", ar: "بَدِّي أَجِيب هَدِيَّة لِأَخُوي، بَس مِش عَارِف شُو آخُد.", arArabeezy: "baddi ajeeb hadiyye la-akhuy, bas mish 3aref shoo akhod.", en: "I want to buy a gift for my brother, but I don't know what to get." },
            { speaker: "Mona", ar: "شُو نَاقْصُه؟", arArabeezy: "shoo na2So?", en: "What does he need?" },
            { speaker: "Rami", ar: "بِفَكِّر قَمِيص. بَسِيط وَحِلْو.", arArabeezy: "bfakkir qameeS. baseeT w 7ilw.", en: "I'm thinking of a shirt. Simple and nice." },
            { speaker: "Mona", ar: "طَيِّب خَلِّينَا نْفُوت هُون.", arArabeezy: "Tayyib khallina nfoot hoon.", en: "Okay, let's go in here." },

            { speaker: "Seller", ar: "أَهْلًا، تْفَضَّلُوا.", arArabeezy: "ahlan, tfaDDalu.", en: "Welcome, come in." },
            { speaker: "Rami", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
            { speaker: "Seller", ar: "الله يْعَافِيك. شُو بَدْكُم؟", arArabeezy: "allah y3afeek. shoo baddkom?", en: "You're welcome. What are you looking for?" },
            { speaker: "Rami", ar: "بَدِّي قَمِيص لِشَبّ عُمْرُه تَقْرِيبًا خَمْسَة وَعِشْرِين.", arArabeezy: "baddi qameeS la-shabb 3omro ta2reeban khamse w 3ishreen.", en: "I need a shirt for a guy who's about twenty-five years old." },
            { speaker: "Seller", ar: "كَاجُوَال وَلَّا رَسْمِي؟", arArabeezy: "casual wala rasmi?", en: "Casual or formal?" },
            { speaker: "Rami", ar: "كَاجُوَال.", arArabeezy: "casual.", en: "Casual." },
            { speaker: "Seller", ar: "شُو رَأْيَك بِهَاد؟", arArabeezy: "shoo ra2yak bihad?", en: "What do you think of this one?" },
            { speaker: "Rami", ar: "حِلْو... بَس عِنْدَك لَوْن تَانِي؟", arArabeezy: "7ilw... bas 3indak lawn tani?", en: "Nice... but do you have another color?" },
            { speaker: "Seller", ar: "آه، فِي كُحْلِي، وَأَسْوَد، وَرَصَاصِي.", arArabeezy: "ah, fi ko7li, w aswad, w raSaSi.", en: "Yes, there's navy, black, and gray." },
            { speaker: "Mona", ar: "أَنَا الكُحْلِي عَاجِبْنِي أَكْتَر.", arArabeezy: "ana el-ko7li 3ajebni aktar.", en: "I like the navy one more." },
            { speaker: "Rami", ar: "بَس أَخُوي بْحِبّ الأَلْوَان الهَادْيَة.", arArabeezy: "bas akhuy bi7ibb el-alwan el-hadye.", en: "But my brother likes calm colors." },
            { speaker: "Mona", ar: "الكُحْلِي هَادِي.", arArabeezy: "el-ko7li hadi.", en: "Navy is a calm color." },
            { speaker: "Rami", ar: "مَعِك حَقّ.", arArabeezy: "ma3ik 7a2.", en: "You're right." },
            { speaker: "Rami", ar: "قَدِّيش سِعْرُه؟", arArabeezy: "addeesh si3ro?", en: "How much is it?" },
            { speaker: "Seller", ar: "خَمْسَة وَسِتِّين.", arArabeezy: "khamse w sitteen.", en: "Sixty-five." },
            { speaker: "Rami", ar: "آخِر سِعْر؟", arArabeezy: "akher si3er?", en: "Final price?" },
            { speaker: "Seller", ar: "هَاي آخِرُه.", arArabeezy: "hay akhro.", en: "That's my final price." },
            { speaker: "Mona", ar: "يَا زَلَمَة... اِعْمِلْنَا سِعْر، إِحْنَا أَوَّل زَبُونَات اليَوْم. 😄", arArabeezy: "ya zalame... i3milna si3er, i7na awwal zaboonat el-yom.", en: "Come on... give us a better price, we're your first customers today." },
            { speaker: "Seller", ar: "ههههه... وَالله أَوَّل مَرَّة بِسْمَعْهَا اليَوْم.", arArabeezy: "hahaha... wallah awwal marra bisma3ha el-yom.", en: "Haha... that's the first time I've heard that today." },
            { speaker: "Rami", ar: "يَعْنِي بِزْبَط بِسِتِّين؟", arArabeezy: "ya3ni bizbaT bisitteen?", en: "So, can you make it sixty?" },
            { speaker: "Seller", ar: "خَلَص، عَشَانْكُم بِسِتِّين.", arArabeezy: "khalaS, 3ashankom bisitteen.", en: "Alright, for you, sixty." },
            { speaker: "Rami", ar: "المِقَاس هَاد وَسَط؟", arArabeezy: "el-me2as had wasaT?", en: "Is this a medium?" },
            { speaker: "Seller", ar: "لَا، هَاد كْبِير.", arArabeezy: "la, had kbeer.", en: "No, this one is large." },
            { speaker: "Rami", ar: "طَيِّب جِيبْلِي وَسَط.", arArabeezy: "Tayyib jeebli wasaT.", en: "Okay, bring me a medium." },
            { speaker: "Seller", ar: "لَحْظَة...", arArabeezy: "la7Za...", en: "One moment..." },
            { speaker: "Mona", ar: "هَيْك أَحْسَن.", arArabeezy: "hek a7san.", en: "That's better." },
            { speaker: "Rami", ar: "إِذَا مَا زَبَط، بَقْدَر أَبَدِّلُه؟", arArabeezy: "iza ma zabaT, ba2dar abaddlo?", en: "If it doesn't fit, can I exchange it?" },
            { speaker: "Seller", ar: "أَكِيد، بَس خَلِّي الوَصْل مَعَك.", arArabeezy: "akeed, bas khalli el-waSel ma3ak.", en: "Of course, just keep the receipt." },
            { speaker: "Rami", ar: "تَمَام.", arArabeezy: "tamam.", en: "Great." },
            { speaker: "Seller", ar: "كَاش وَلَّا بِطَاقَة؟", arArabeezy: "cash wala biTa2a?", en: "Cash or card?" },
            { speaker: "Rami", ar: "كَاش.", arArabeezy: "cash.", en: "Cash." },
            { speaker: "Seller", ar: "تْفَضَّل البَاقِي وَالوَصْل.", arArabeezy: "tfaDDal el-baqi w el-waSel.", en: "Here’s your change and the receipt." },
            { speaker: "Rami", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
            { speaker: "Seller", ar: "الله يْعَافِيكُم.", arArabeezy: "allah y3afeekom.", en: "You're welcome." },

            { speaker: "Mona", ar: "بِمَا إِنَّا هُون، بَدِّي أَجِيب شُوَيَّة خُضْرَة.", arArabeezy: "bima inna hoon, baddi ajeeb shwayyet khoDra.", en: "Since we're here, I want to buy some vegetables." },
            { speaker: "Rami", ar: "يَلَّا.", arArabeezy: "yalla.", en: "Let's go." },

            { speaker: "Vegetable Seller", ar: "تْفَضَّلُوا يَا جَمَاعَة.", arArabeezy: "tfaDDalu ya jama3a.", en: "Welcome, everyone." },
            { speaker: "Mona", ar: "قَدِّيش البَنْدُورَة اليَوْم؟", arArabeezy: "addeesh el-bandora el-yom?", en: "How much are the tomatoes today?" },
            { speaker: "Vegetable Seller", ar: "الكِيلُو بِعَشَرَة.", arArabeezy: "el-kilo bi3ashara.", en: "Ten per kilo." },
            { speaker: "Mona", ar: "إِمْبَارِح كَانِت بِثْمَانِيَة!", arArabeezy: "embare7 kanit bithmane.", en: "Yesterday they were eight!" },
            { speaker: "Vegetable Seller", ar: "وَالله اليَوْم البِضَاعَة أَقَلّ.", arArabeezy: "wallah el-yom el-biDa3a a2all.", en: "Today there’s less produce." },
            { speaker: "Rami", ar: "وَالخِيَار؟", arArabeezy: "w el-khyar?", en: "What about cucumbers?" },
            { speaker: "Vegetable Seller", ar: "بِسَبْعَة.", arArabeezy: "bisab3a.", en: "Seven." },
            { speaker: "Mona", ar: "طَيِّب... أَعْطِينِي نُصّ كِيلُو بَنْدُورَة، وَنُصّ كِيلُو خِيَار.", arArabeezy: "Tayyib... a3Teeni noSS kilo bandora, w noSS kilo khyar.", en: "Okay... give me half a kilo of tomatoes and half a kilo of cucumbers." },
            { speaker: "Vegetable Seller", ar: "غَيْر إِشِي؟", arArabeezy: "gheir ishi?", en: "Anything else?" },
            { speaker: "Mona", ar: "قَدِّيش البُرْتُقَال؟", arArabeezy: "addeesh el-borto2al?", en: "How much are the oranges?" },
            { speaker: "Vegetable Seller", ar: "بِخَمْسَة.", arArabeezy: "bikhamse.", en: "Five." },
            { speaker: "Mona", ar: "خَلَص، كِيلُو كَمَان.", arArabeezy: "khalaS, kilo kaman.", en: "Okay, one kilo too." },
            { speaker: "Vegetable Seller", ar: "هَيْك صَار سَبْعْتَعْش شِيكِل.", arArabeezy: "hek Sar sab3ta3ash shekel.", en: "That'll be seventeen shekels." },
            { speaker: "Mona", ar: "إِذَا أَخَدْت كِيلُوَيْن بَنْدُورَة، بْتِنْزِل شُوَي؟", arArabeezy: "iza akhadt kilowain bandora, btinzil shway?", en: "If I buy two kilos of tomatoes, can you lower the price a bit?" },
            { speaker: "Vegetable Seller", ar: "ههههه... لَا وَالله، اليَوْم مَا بَقْدَر.", arArabeezy: "hahaha... la wallah, el-yom ma ba2dar.", en: "Haha... honestly, I can't today." },
            { speaker: "Rami", ar: "جَرِّبِي مَعُه شُوَي.", arArabeezy: "jarribi ma3o shway.", en: "Try bargaining a little." },
            { speaker: "Mona", ar: "طَيِّب خَلِّيهُم خَمْسْتَعْش؟", arArabeezy: "Tayyib khallihom khamsta3ash?", en: "Okay, make it fifteen?" },
            { speaker: "Vegetable Seller", ar: "وَلَا يْهِمَّك، خَمْسْتَعْش.", arArabeezy: "wala yhimmak, khamsta3ash.", en: "No problem, fifteen." },
            { speaker: "Mona", ar: "الله يْرْزُقَك.", arArabeezy: "allah yirzo2ak.", en: "May God bless your livelihood." },
            { speaker: "Vegetable Seller", ar: "وَإِيَّاكُم.", arArabeezy: "w iyyakom.", en: "You too." },
            { speaker: "Mona", ar: "تْفَضَّل، هَاي عِشْرِين.", arArabeezy: "tfaDDal, hay 3ishreen.", en: "Here, twenty." },
            { speaker: "Vegetable Seller", ar: "وَهُون خَمْس شِيكِل البَاقِي.", arArabeezy: "w hoon khams shekel el-baqi.", en: "And here are your five shekels change." },
            { speaker: "Mona", ar: "يِسْلَمُوا.", arArabeezy: "yislamu.", en: "Thank you." },

            { speaker: "Rami", ar: "خَلَّصْنَا؟", arArabeezy: "khallaSna?", en: "Are we done?" },
            { speaker: "Mona", ar: "آه، الحَمْدُ لله.", arArabeezy: "ah, el-7amdullah.", en: "Yes, thank God." },
            { speaker: "Rami", ar: "يَلَّا نِطْلَع قَبْل مَا السُّوق يْزِيد زَحْمَة.", arArabeezy: "yalla niTla3 2abl ma es-soo2 yzeed za7me.", en: "Let's leave before the market gets more crowded." },
            { speaker: "Mona", ar: "آه وَالله، وَالدُّنْيَا شُوب كَمَان.", arArabeezy: "ah wallah, w ed-dinya shoob kaman.", en: "Yes, and it's hot too." },
            { speaker: "Rami", ar: "بَعْدِين بِنْمُرّ عَالكَافِيه؟", arArabeezy: "ba3dain binmor 3al-cafe?", en: "Shall we stop by the café afterward?" },
            { speaker: "Mona", ar: "إِذَا لَحِقْنَا... أَنَا جُعْت مِن اللَّفَّة كُلْهَا. 😂", arArabeezy: "iza la7i2na... ana jo3t min el-laffe kolha.", en: "If we have time... I got hungry from all this walking." },
            { speaker: "Rami", ar: "ههههه... وَأَنَا كَمَان.", arArabeezy: "hahaha... w ana kaman.", en: "Haha... me too." }
        ],

        questions: [
            { ar: "شُو كَان بَدُّه يِشْتَرِي رَامِي؟", en: "What did Rami want to buy?" },
            { ar: "لِمِين كَانِت الهَدِيَّة؟", en: "Who was the gift for?" },
            { ar: "أَي لَوْن اخْتَارُوا بِالنِّهَايَة؟", en: "Which color did they choose in the end?" },
            { ar: "قَدِّيش كَان السِّعْر أَوَّل إِشِي؟", en: "What was the original price?" },
            { ar: "قَدِّيش دَفَع بِالنِّهَايَة؟", en: "How much did he pay in the end?" },
            { ar: "شُو سَأَل رَامِي عَن المِقَاس؟", en: "What did Rami ask about the size?" },
            { ar: "شُو لَازِم يِحْتَفِظ فِيه إِذَا بَدُّه يِبَدِّل القَمِيص؟", en: "What does he need to keep if he wants to exchange the shirt?" },
            { ar: "كِيف دَفَع رَامِي؟", en: "How did Rami pay?" },
            { ar: "شُو اشْتَرَت مُونَا مِن بَائِع الخُضَار؟", en: "What did Mona buy from the vegetable seller?" },
            { ar: "لِيش سِعْر البَنْدُورَة ارْتَفَع؟", en: "Why did the tomato price increase?" },
            { ar: "هَل قَدِرِت مُونَا تْفَاصِل؟", en: "Was Mona able to bargain?" },
            { ar: "وِين كَانُوا رَايْحِين بَعْد السُّوق؟", en: "Where were they planning to go after the market?" }
        ],
    },

    grammar: [

        {
            title: "3. Broken plurals you need in the market",
            short: "سِعِر ← أَسْعَار — لَوْن ← أَلْوَان — قَمِيص ← قُمْصَان",
            description: "A broken plural changes the inside of the noun instead of relying only on a final ending. Shopping language contains many high-frequency broken plurals. They cannot be generated safely from one rule, so store each singular and plural as a pair and revisit them across prices, colours, sizes, and products.",
            table: {
                title: "Shopping singular–plural pairs",
                headers: ["Singular", "Plural", "Arabizi", "Meaning"],
                rows: [
                    ["سِعِر", "أَسْعَار", "as3ar", "price → prices"],
                    ["لَوْن", "أَلْوَان", "alwan", "colour → colours"],
                    ["قَمِيص", "قُمْصَان", "qumSan", "shirt → shirts"],
                    ["فُسْتَان", "فَسَاتِين", "fasateen", "dress → dresses"],
                    ["شِيكِل", "شَوَاكِل", "shawakel", "shekel → shekels"],
                    ["مَحَلّ", "مَحَلَّات", "ma7allat", "shop → shops (sound plural)"],
                    ["مَقَاس", "مَقَاسَات", "maqasat", "size → sizes (sound plural)"],
                ],
            },
            examples: [
                { ar: "الأَسْعَار فِي هَاد المَحَلّ أَرْخَص.", arabeezy: "el-as3ar fi had el-ma7all arkhaS.", en: "The prices in this shop are cheaper." },
                { ar: "عِنْدْكُم أَلْوَان تَانْيَة مِن هَاد القَمِيص؟", arabeezy: "3indkum alwan tanyeh min had el-qameeS?", en: "Do you have other colours of this shirt?" },
                { ar: "الفَسَاتِين الجْدِيدَة وَاصْلَة اليَوم.", arabeezy: "el-fasateen el-jdeedeh waSleh el-yom.", en: "The new dresses arrived today." },
            ],
            commonMistakes: [
                "Do not invent *سِعِرَات for أَسْعَار or *لَوْنَات for أَلْوَان as your default. Learn the established plural.",
                "Not every plural is broken. مَقَاسَات and مَحَلَّات use ـات, so classify by the real word rather than by meaning.",
                "A non-human broken plural often takes feminine-singular agreement: الأَسْعَار غَالْيَة, الأَلْوَان حِلْوَة.",
            ],
            exercises: [
                { prompt: "Choose the plural of سِعِر.", options: ["أَسْعَار", "سِعِرَات", "سُعُورِين"], correct: "أَسْعَار", explanation: "سِعِر → أَسْعَار is a high-frequency broken plural." },
                { prompt: "Which pair uses a sound ـات plural?", options: ["مَقَاس ← مَقَاسَات", "لَوْن ← أَلْوَان", "قَمِيص ← قُمْصَان"], correct: "مَقَاس ← مَقَاسَات", explanation: "مَقَاسَات adds the plural ending without an internal broken-plural pattern." },
                { prompt: "Complete: عِنْدْكُم ___ تَانْيَة؟ (other colours)", options: ["أَلْوَان", "لَوْن", "لَوْنَيْن فقط"], correct: "أَلْوَان", explanation: "أَلْوَان is the plural needed for multiple colours." },
            ],
        },
        {
            title: "4. Demonstratives, colours, and adjective agreement",
            short: "هَادَا القَمِيص الأَزْرَق — هَاي البْلُوزَة الزَّرْقَا — هَدُول القُمْصَان",
            description: "A shopping description must keep track of the item’s gender and number. Use هَادَا with a masculine singular item, هَاي with a feminine singular item, and هَدُول with plural items. Colours and ordinary adjectives normally follow the noun and agree with it. With non-human plurals, feminine-singular description is very common.",
            table: {
                title: "Pointing to and describing items",
                headers: ["Item", "Demonstrative phrase", "Colour phrase", "Meaning"],
                rows: [
                    ["قَمِيص (m.)", "هَادَا القَمِيص", "القَمِيص الأَزْرَق", "this blue shirt"],
                    ["بْلُوزَة (f.)", "هَاي البْلُوزَة", "البْلُوزَة الزَّرْقَا", "this blue blouse"],
                    ["قُمْصَان (pl.)", "هَدُول القُمْصَان", "القُمْصَان الجْدِيدَة", "these new shirts"],
                    ["فَسَاتِين (pl.)", "هَدُول الفَسَاتِين", "الفَسَاتِين غَالْيَة", "these dresses are expensive"],
                ],
            },
            examples: [
                { ar: "هَادَا القَمِيص الأَسْوَد مَقَاسُه أَكْبَر.", arabeezy: "hada el-qameeS el-aswad maqaso akbar.", en: "This black shirt is a larger size." },
                { ar: "هَاي البْلُوزَة الحَمْرَا حِلْوَة، بَس غَالْيَة.", arabeezy: "hay el-bloozeh el-7amra 7ilweh, bas ghalyeh.", en: "This red blouse is nice, but expensive." },
                { ar: "هَدُول الفَسَاتِين الجْدِيدَة عِنْدْكُم خَصْم عَلَيْهَا؟", arabeezy: "hadol el-fasateen el-jdeedeh 3indkum khaSm 3aleiha?", en: "Do you have a discount on these new dresses?" },
            ],
            commonMistakes: [
                "Do not use هَادَا with every item. A feminine singular item such as بْلُوزَة takes هَاي.",
                "The colour follows the noun: بْلُوزَة حَمْرَا, not حَمْرَا بْلُوزَة in a neutral description.",
                "Plural objects often take feminine-singular adjective/pronoun reference: الفَسَاتِين غَالْيَة; خَصْم عَلَيْهَا.",
            ],
            exercises: [
                { prompt: "Point to one feminine item: ‘this blouse’.", options: ["هَاي البْلُوزَة", "هَادَا البْلُوزَة", "هَدُول البْلُوزَة"], correct: "هَاي البْلُوزَة", explanation: "هَاي points to a feminine singular noun." },
                { prompt: "Choose the agreeing phrase: ‘the red shirt’.", options: ["القَمِيص الأَحْمَر", "القَمِيص الحَمْرَا", "البْلُوزَة الأَحْمَر"], correct: "القَمِيص الأَحْمَر", explanation: "قَمِيص is masculine singular, so the colour is أَحْمَر." },
                { prompt: "Complete: الفَسَاتِين ___. (expensive)", options: ["غَالْيَة", "غَالِي", "غَالْيِين للأشخاص"], correct: "غَالْيَة", explanation: "The non-human plural commonly takes feminine-singular agreement." },
            ],
        },
        {
            title: "5. Comparing and bargaining with a condition",
            short: "أَغْلَى مِن، أَرْخَص مِن، آخِر سِعِر؟ إِذَا... بَاخُدْهَا",
            description: "Natural bargaining combines evaluation, comparison, a polite request, and sometimes a condition. The shopper can say an item is expensive for them, ask whether the seller can lower it, and make a clear offer with إِذَا (‘if’). Object endings keep track of the item: بَاخُدُه for a masculine item, بَاخُدْهَا for a feminine item, and بَاخُدْهُم for plural items.",
            table: {
                title: "A respectful bargaining sequence",
                headers: ["Job", "Palestinian phrase", "Natural English"],
                rows: [
                    ["evaluate", "هَاد غَالِي عَلَيّ", "this is expensive for me"],
                    ["compare", "هَادَاك أَرْخَص مِن هَادَا", "that one is cheaper than this"],
                    ["request", "مُمْكِن تْنَزِّل شُوَيّ؟", "can you lower it a little?"],
                    ["ask final price", "آخِر سِعِر؟", "final price?"],
                    ["conditional offer", "إِذَا بِعَشَرِين بَاخُدْهَا", "if it is twenty, I’ll take it"],
                    ["accept", "مَاشِي، بَاخُدْهَا", "okay, I’ll take it (f.)"],
                ],
            },
            examples: [
                { ar: "هَادَا أَغْلَى مِن هَادَاك، بَس جَوْدِتُه أَحْسَن.", arabeezy: "hada aghla min hadak, bas jawdeto a7san.", en: "This one is more expensive than that one, but its quality is better." },
                { ar: "مَعَلِّش، السِّعِر غَالِي عَلَيّ. مُمْكِن تْنَزِّل شُوَيّ؟", arabeezy: "ma3allish, es-si3er ghali 3alay. mumkin tnazzel shway?", en: "Excuse me, the price is high for me. Could you lower it a little?" },
                { ar: "إِذَا بِخَمْسَة وَعِشْرِين بَاخُدْهَا هَلْقِيت.", arabeezy: "iza b-khamseh w 3ishreen bakhodha hal2eet.", en: "If it is twenty-five, I’ll take it now." },
            ],
            commonMistakes: [
                "Bargaining is not appropriate in every shop. It is natural in many markets and flexible-price settings, but not at a fixed supermarket checkout.",
                "Keep the item ending consistent: قَمِيص → بَاخُدُه; بْلُوزَة → بَاخُدْهَا; قُمْصَان → بَاخُدْهُم.",
                "A polite opening and calm tone matter. هَاد غَالِي عَلَيّ comments on your budget more softly than accusing the seller of cheating.",
            ],
            exercises: [
                { prompt: "You are buying a feminine item (بْلُوزَة). Choose: ‘I’ll take it.’", options: ["بَاخُدْهَا.", "بَاخُدُه.", "بَاخُدْهُم."], correct: "بَاخُدْهَا.", explanation: "The object ending ـهَا refers to a feminine singular item." },
                { prompt: "Choose the respectful request for a lower price.", options: ["مُمْكِن تْنَزِّل شُوَيّ؟", "نَزِّل السِّعِر هَلْقِيت!", "إِنْتَ سِعِرَك غَلَط."], correct: "مُمْكِن تْنَزِّل شُوَيّ؟", explanation: "مُمْكِن makes the request negotiable and polite." },
                { prompt: "Complete the offer: إِذَا بِعَشَرِين، ___.", options: ["بَاخُدْهَا", "أَغْلَى مِن", "قَدِّيش هَادَا"], correct: "بَاخُدْهَا", explanation: "The condition gives the acceptable price; the result states the purchase." },
            ],
        },
    ],

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "shopping_mc1",
                type: "choose",
                prompt: "Choose the Gaza Palestinian Arabic word for: market.",
                options: ["سُوق", "دُكَّان", "مَحَلّ", "بَشْتَرِي"],
                correct: "سُوق",
            },
            {
                id: "shopping_mc2",
                type: "choose",
                prompt: "Choose the polite Palestinian phrase for: Give me a discount / Be easy on the price.",
                options: ["رَاعِينِي شُوَيّ", "مِن الآخِر", "خَلِّيهَا عَلِينَا", "مَا بِتْوَفّي مَعَاي"],
                correct: "رَاعِينِي شُوَيّ",
            },
            {
                id: "shopping_mc3",
                type: "choose",
                prompt: "Choose the phrase used by the buyer to ask for the absolute lowest price:",
                options: ["قَدِيش حَقّه مِن الآخِر؟", "خَلِّيهَا عَلِينَا", "مَا بِتْوَفّي مَعَاي", "عِنْدَك إِشِي تَانِي؟"],
                correct: "قَدِيش حَقّه مِن الآخِر؟",
            },
            {
                id: "shopping_mc4",
                type: "complete",
                prompt: "Complete the Arabic sentence for: Here you go, this is the change returned.\nتْفَضَّل، هَادَا ___.",
                options: ["البَاقِي", "الحِسَاب", "المَشْرُوع", "الوَصْل"],
                correct: "البَاقِي",
            },
            {
                id: "shopping_mc5",
                type: "complete",
                prompt: "Complete the Arabic sentence for: The shoe size is a bit big on me.\n___ الجَزْمَة كْبِير عَلَيّ شْوَيّ.",
                options: ["مَقَاس", "لَوْن", "سِعِر", "نَوْع"],
                correct: "مَقَاس",
            },
            {
                "id": "shopping_mc6",
                "type": "reorder",
                "prompt": "Reorder the Arabic words to match: My mother said that the quality is very good in this place.",
                "options": [
                    "بِهَادَا",
                    "المَحَلّ.",
                    "أُمّي",
                    "حَكَت",
                    "إِنّو",
                    "الجَوْدَة",
                    "كَثِير",
                    "مْنِيحَة"
                ],
                "correct": [
                    "أُمّي",
                    "حَكَت",
                    "إِنّو",
                    "الجَوْدَة",
                    "كَثِير",
                    "مْنِيحَة",
                    "بِهَادَا",
                    "المَحَلّ."
                ]
            },
            
        ],
    },

    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        quiz: [
            {
                id: "shopping_q1",
                questionAr: "Choose when to use: «قَدِّيش هَادَا؟»",
                optionsEn: ["ask the price", "ask someone's age", "ask about weather"],
                correctIndex: 0,
            },
            {
                id: "shopping_q2",
                questionAr: "Choose a natural response when the price is high.",
                optionsEn: ["رَاعِينِي شُوَيّ", "كِيف الجَوّ عِنْدَك؟", "أَنَا بَس بَتْفَرَّج."],
                correctIndex: 0,
            },
            {
                id: "shopping_q3",
                questionAr: "Choose when a shopper says: «بَاخُدْهَا»",
                optionsEn: ["a feminine item", "a masculine item", "a group of people"],
                correctIndex: 0,
            },
            {
                id: "shopping_q4",
                questionAr: "Choose how to ask for another color.",
                optionsEn: ["عِنْدَك نَفْس المَقَاس بس لَوْن تَانِي؟", "قَدِّيش الأُجْرَة؟", "كِيف المُوَاصَلَات؟"],
                correctIndex: 0,
            },
            {
                id: "shopping_q5",
                questionAr: "Choose the English meaning of: «نُصّ كِيلُو»",
                optionsEn: ["half a kilo", "one kilo", "two kilos"],
                correctIndex: 0,
            },
            {
                id: "shopping_q6",
                questionAr: "Choose the situation where you use: «آخِر سِعِر؟»",
                optionsEn: ["bargaining", "greeting", "family description"],
                correctIndex: 0,
            },
            {
                id: "shopping_q7",
                questionAr: "Choose how to say that you want to pay cash.",
                optionsEn: ["بَدِّي أَدْفَع كَاش.", "بَدِّي أَشُوف المَقَاس.", "بَدِّي أَرْجَع بَدْرِي."],
                correctIndex: 0,
            },
            {
                id: "shopping_q8",
                questionAr: "Choose what the adjective «مْنَاسِب» can describe.",
                optionsEn: ["price, size, color, or time", "only weather", "only family"],
                correctIndex: 0,
            },
            {
                id: "shopping_q9",
                questionAr: "Choose why a shopper keeps the receipt.",
                optionsEn: ["for exchange or proof of payment", "to ask the weather", "to describe family"],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Shopping role-play: ask for an item, color, size and price; bargain once, choose a quantity, then decide how to pay.",
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "سِعِر", arabeezy: "si3er", en: "price" },
                    { ar: "خَصْم", arabeezy: "khaSm", en: "discount" },
                    { ar: "مَقَاس", arabeezy: "ma2as", en: "size" },
                    { ar: "لَوْن", arabeezy: "lawn", en: "color" },
                    { ar: "نُصّ كِيلُو", arabeezy: "noSS kilo", en: "half a kilo" },
                    { ar: "وَصْل", arabeezy: "waSl", en: "receipt" },
                ],
                multipleChoice: [
                    { prompt: "Choose the feminine form of غَالِي (ghali).", options: ["غَالْيَة (ghalyeh)", "غَالِيِين (ghalyeen)", "رْخِيصَة (rkheeSa)"], correct: "غَالْيَة (ghalyeh)" },
                    { prompt: "Choose the phrase used to ask a price.", options: ["قَدِّيش هَادَا؟ (addeesh hada?)", "كِيف الجَوّ؟ (keef el-jaww?)", "مَع مِين؟ (ma3 meen?)"], correct: "قَدِّيش هَادَا؟ (addeesh hada?)" },
                ],
            },
            {
                title: "B - Shopping grammar practice",
                fillInTheBlank: [
                    { prompt: "بَدِّي ___ مِن السُّوق.", arabeezy: "baddi ___ min es-souq.", cueEn: "buy", answer: "أَشْتِرِي" },
                    { prompt: "قَدِّيش ___ هَادَا؟", arabeezy: "addeesh ___ hada?", cueEn: "price of", answer: "سِعِر" },
                    { prompt: "بَدِّي نُصّ ___ بَنْدُورَة.", arabeezy: "baddi noSS ___ bandora.", cueEn: "kilo", answer: "كِيلُو" },
                    { prompt: "عِنْدَك نَفْس المَقَاس ___ تَانِي؟", arabeezy: "3indak nafs el-ma2as ___ tani?", cueEn: "in another color", answer: "بس لَوْن" },
                    { prompt: "هَادَا غَالِي؛  ___ ", arabeezy: "hada ghali; mumkin ___ shway?", cueEn: "Give me a discount", answer: "رَاعِينِي شُوَيّ" },
                    { prompt: "خَلِّيه خَمْسِين وَ___ كَاش.", arabeezy: "khallih khamseen w ___ cash.", cueEn: "I will take it", answer: "بَاخُدُه" },
                    { prompt: "Review: بَدِّي ___ كِيلُو بَنْدُورَة.", arabeezy: "baddi ___ kilo bandora.", cueEn: "I want", answer: "أَشْتِرِي" },
                    { prompt: "كَمّ ___ بَدَّك؟", arabeezy: "kam ___ baddak?", cueEn: "pieces", answer: "قِطْعَة" },
                    { prompt: "هَادِي غَالْيَة، بَدِّي إِشِي ___.", arabeezy: "hadi ghalyeh, baddi ishi ___.", cueEn: "cheaper", answer: "أَرْخَص" },
                    { prompt: "Review: اِمْبَارِح السِّعِر ___ أَرْخَص.", arabeezy: "imbari7 es-si3er ___ arkhaS.", cueEn: "was", answer: "كَان" },
                    { prompt: "Review: بُكْرَا ___ أَرُوح عَالسُّوق.", arabeezy: "bukra ___ aroo7 3as-soo2.", cueEn: "will", answer: "رَاح" },
                    { prompt: "Review: الجَوّ اليَوم أَحْسَن ___ اِمْبَارِح.", arabeezy: "el-jaww el-yom a7san ___ imbari7.", cueEn: "than", answer: "مِن" },
                ],
                correctTheMistake: [
                    { prompt: "Correct: هَادِي السِّعِر غَالْيَة.", arabeezy: "hadi es-se3er ghalyeh.", answer: "هَادَا السِّعِر غَالِي." },
                    { prompt: "Correct: هَادَا الجَوْدَة مْنِيح.", arabeezy: "hada el-jawde mnee7.", answer: "هَادِي الجَوْدَة مْنِيحَة." },
                    { prompt: "Correct: بَدِّي تَلَات كِيلُو بَنْدُورَة.", arabeezy: "baddi talat kilo bandora.", answer: "بَدِّي تَلَاتَة كِيلُو بَنْدُورَة." },
                    { prompt: "Review the future: بُكْرَا رُحْت عَالسُّوق.", arabeezy: "bukra ru7t 3as-soo2.", answer: "بُكْرَا رَاح أَرُوح عَالسُّوق." },
                    { prompt: "Correct the phrase: كَمّ كِيلُو بَدِّي؟", arabeezy: "kam kilo baddi?", answer: "كَمّ كِيلُو بَدَّك؟" },
                    { prompt: "Correct the adjective: هَادِي رْخِيص.", arabeezy: "hadi rkheeS.", answer: "هَادِي رْخِيصَة." },
                ],
                reorderSentences: [
                    { prompt: "Build: I want half a kilo of tomatoes.", arabeezy: "baddi noSS kilo bandora.", words: ["بَنْدُورَة.", "بَدِّي", "نُصّ كِيلُو",], answer: "بَدِّي نُصّ كِيلُو بَنْدُورَة." },
                    { prompt: "Build: Do you have another color?", arabeezy: "3indak lawn tani?", words: ["لَوْن", "عِنْدَك", "تَانِي؟"], answer: "عِنْدَك لَوْن تَانِي؟" },
                    { prompt: "Build: Yesterday the price was cheaper.", arabeezy: "imbari7 es-si3er kan arkhaS.", words: ["اِمْبَارِح", "كَان أَرْخَص.", "السِّعِر",], answer: "اِمْبَارِح السِّعِر كَان أَرْخَص." },
                    { prompt: "Review: Tomorrow I will go to the market.", arabeezy: "bukra ra7 aroo7 3as-soo2.", words: ["رَاح أَرُوح", "بُكْرَا", "عَالسُّوق."], answer: "بُكْرَا رَاح أَرُوح عَالسُّوق." },
                    { prompt: "Build: Can I pay by card?", arabeezy: "biseer adfa3 bil-card?", words: ["ممكن", "أَدْفَع", "بِالكَارْت؟"], answer: "ممكن أَدْفَع بِالكَارْت؟" },
                    { prompt: "Review: Today's weather is better than yesterday's.", arabeezy: "jaww el-yom a7san min imbari7.", words: ["أَحْسَن", "جَوّ اليَوم", "مِن اِمْبَارِح."], answer: "جَوّ اليَوم أَحْسَن مِن اِمْبَارِح." },
                ],
            },
        ],
        translation: [
            { id: "shopping_t1", type: "enToAr", textEn: "Good morning, I want to buy from the market.", textAr: "صَبَاح الخِير، بَدِّي أَشْتِرِي مِن السُّوق." },
            { id: "shopping_t2", type: "arToEn", textEn: "How much is this black one?", textAr: "قَدِّيش هَادَا الأَسْوَد؟" },
            { id: "shopping_t3", type: "enToAr", textEn: "This is a little expensive. Can you lower it a little?", textAr: "هَادَا غَالِي شُوَيّ. مُمْكِن تْنَزِّل شُوَيّ؟" },
            { id: "shopping_t4", type: "arToEn", textEn: "Do you have the same size in another color?", textAr: "عِنْدَك نَفْس المَقَاس بِلَوْن تَانِي؟" },
            { id: "shopping_t5", type: "enToAr", textEn: "My budget today is fifty shekels.", textAr: "مِيزَانِيَّتِي اليَوم خَمْسِين شِيكِل." },
            { id: "shopping_t6", type: "arToEn", textEn: "Make it fifty and I'll take it.", textAr: "خَلِّيه خَمْسِين وَبَاخُدُه." },
            { id: "shopping_t7", type: "enToAr", textEn: "Can I pay by card, or only cash?", textAr: "بِصِير أَدْفَع بِالكَارْت وَلَا بَس كَاش؟" },
            { id: "shopping_t8", type: "arToEn", textEn: "The receipt is with me.", textAr: "الوَصْل مَعِي." },
            { id: "shopping_t9", type: "enToAr", textEn: "I want half a kilo of tomatoes.", textAr: "بَدِّي نُصّ كِيلُو بَنْدُورَة." },
            { id: "shopping_t10", type: "arToEn", textEn: "Half a kilo is ten shekels.", textAr: "نُصّ كِيلُو بِعَشَرَة شَوَاكِل." },
            { id: "shopping_t11", type: "enToAr", textEn: "Yesterday the price was cheaper.", textAr: "اِمْبَارِح السِّعِر كَان أَرْخَص." },
            { id: "shopping_t12", type: "arToEn", textEn: "The price is suitable, but I want another kind.", textAr: "السِّعِر مْنَاسِب، بَس بَدِّي نَوْع تَانِي." },
            { id: "shopping_t13", type: "enToAr", textEn: "I'm just looking for now, thank you.", textAr: "أَنَا بَس بَتْفَرَّج هَلْقِيت، شُكْرًا." },
            { id: "shopping_t14", type: "arToEn", textEn: "Do you have something else in the same size?", textAr: "عِنْدَك إِشِي تَانِي نَفْس المَقَاس؟" },
            { id: "shopping_t15", type: "enToAr", textEn: "Let's go home after the market.", textAr: "يَلَّا نْرَوِّح بَعْد السُّوق." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 75-90 second shopping story in Gaza Palestinian Arabic. Include: where you went, what you wanted to buy, the price, color or size, whether it was expensive or suitable, how you bargained, how you paid, and whether you took a receipt. Reuse at least 8 words from this unit and 5 old words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Good morning, I want to buy from the market.
2. How much is this black one?
3. This is a little expensive. Can you lower it a little?
4. Do you have the same size in another color?
5. My budget today is fifty shekels.
6. Make it fifty and I'll take it.
7. Can I pay by card, or only cash?
8. The receipt is with me.
9. I want half a kilo of tomatoes.
10. Half a kilo is ten shekels.
11. Yesterday the price was cheaper.
12. The price is suitable, but I want another kind.
13. I'm just looking for now, thank you.
14. Do you have something else in the same size?
15. Let's go home after the market.`,
    },

    teacherNotes: {
        warmup: [
            "Start with a real question: شو آخر إشي اشتريته؟ قديش كان؟",
            "Recycle previous units immediately: greetings, weather, family gift, transport, and food market.",
            "This unit's hidden focus is numbers, colors, quantities, comparison, and polite bargaining.",
        ],
        vocabularySteps: [
            "Teach phrases as shopping chunks: قَدِّيش هَادَا؟ / غَالِي شُوَيّ / آخِر سِعِر؟ / بَاخُدُه.",
            "Use masculine/feminine through items: هَادَا القَمِيص / هَادِي الجَزْمَة / بَاخُدُه / بَاخُدْهَا.",
            "Keep numbers practical: 10, 12, 15, 50, 55, 60, 80, and prices by kilo.",
            "Use colors as needed in context, not as a separate color lesson.",
        ],
        dialogueSteps: [
            "Act the dialogue in two scenes: clothes shop, then vegetable stand.",
            "Ask the dialogue questions as speaking practice and require full sentence answers.",
            "Have the student replace the shirt with a real item they want to buy.",
        ],
        practiceTips: [
            "Push output: the student must ask price, bargain once, ask for size/color, and close the purchase.",
            "Use quick transformations: هَادَا غَالِي → هَادِي غَالْيَة; بَاخُدُه → بَاخُدْهَا.",
            "End with a 60-second role-play where the student buys something under a budget.",
        ],
        wrapup: [
            "Student buys one item in a role-play without reading.",
            "Student asks for another size/color.",
            "Student bargains politely and says how they will pay.",
        ],
        myNotes: "",
    },
};
