import { LESSON_ID_WEATHER } from '../../constants.js';

export const lessonId = LESSON_ID_WEATHER;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Weather & Small Talk",
        lessonTitle: "Unit 7 - Weather & Small Talk in Gaza Palestinian Arabic",
        contentVersion: 2026081501,
    },

    overview: {
        title: "Unit 7 - Weather & Small Talk",
        description:
            "Students learn how Gazans use weather to start real small talk: at the door, on the phone, before work, while waiting for transport, and when checking on family.",
        goals: [
            "Describe the weather naturally in Gaza Palestinian Arabic.",
            "Start and continue small talk using weather, feelings, and quick follow-up questions.",
            "Give simple advice based on the weather.",
            "Compare weather using today, yesterday, tomorrow, and next week inside examples and conversation.",
            "Recycle previous units: greetings, family, routine, food, transport, work/study, time, and politeness.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can give a 60-second weather update.",
            "The student can start a light conversation about weather and keep it going for 8-10 lines.",
            "The student can warn someone politely about rain, wind, heat, humidity, or dust.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "el_jaw",
                ar: "الجَوّ",
                en: "the weather",
                enArabeezy: "el-jaw",
                hint: "Main word for weather. Common chunks: الجَوّ حِلُو، الجَوّ مُتْعِب، كِيف الجَوّ عِنْدَك؟",
                exampleAr: "اليَوم الجَوّ حِلُو.",
                exampleArabeezy: "el-yom el-jaw 7ilu.",
                exampleEn: "The weather is nice today.",
            },
            {
                id: "keef_el_jaw",
                ar: "كِيف الجَوّ؟",
                en: "How is the weather?",
                enArabeezy: "keef el-jaw?",
                hint: "Natural small-talk question. Add place/person: كِيف الجَوّ عِنْدَك؟ / كِيف الجَوّ فِي غَزَّة؟",
                // Learned so far: el_jaw, keef_el_jaw
                exampleAr: "حَكَيْت مَعَ صاحْبِي فِي غَزَّة وَسَأَلْتُه: كِيف الجَوّ عِنْدَكُم؟",
                exampleArabeezy: "7akeet ma3 Sa7bi fi Ghazza w sa'altoh: keef el-jaw 3indakum?",
                exampleEn: "I spoke with my friend in Gaza and asked him: How is the weather at your place?",
            },

            {
                id: "shob",
                ar: "شُوب",
                en: "heat / hot weather",
                enArabeezy: "shoob",
                hint: "Very natural in Gaza for hot weather. Say: فِي شُوب / شُو هَالشُّوب! This is the main Gaza-style word for hot weather.",
                exampleAr: "أُخْتِي مَا بَتِسْتَحْمِل الشُّوب، كُلّ الصَّيْف بَتِقْعَد قُدَّام المَرْوَحَة.",
                exampleArabeezy: "okhti ma batesta7mel esh-shob, koll es-Sayf bate23ad 2eddam el-marwa7a.",
                exampleEn: "My sister can't stand the heat; all summer she sits in front of the fan.",
            },
            {
                id: "bard",
                ar: "بَرْد / سَقْعَة",
                en: "cold weather",
                enArabeezy: "bard / sa2'a",
                hint: "Say: فِي بَرْد / فِي سَقْعَة. For a person: بَرْدَان / بَرْدَانَة.",
                exampleAr: "هُمَّ بَرْدَانِين كْتِير لأَنّو فِي سَقْعَة بَاللَّيْل.",
                exampleArabeezy: "humma bardaneen kteer l'anno fi sa2'a bil-lel.",
                exampleEn: "They are very cold because it's freezing at night.",
            },
            {
                id: "dafi",
                ar: "دِفَا / دَافِي",
                en: "warmth / warm",
                enArabeezy: "difa / daafi",
                hint: "دِفَا = warmth. دَافِي / دَافْيَة = warm. Used for weather, clothes, drinks, and homes.",
                exampleAr: "أَبُوي حَكَى إِنّو الجَوّ دَافِي فِي الرَّبِيع وَأَحْسَن مِن الشِّتَا.",
                exampleArabeezy: "aboy 7aka inno el-jaw dafi fi er-rabee3 w a7san min esh-sheta.",
                exampleEn: "My father said that the weather is warm in spring and better than winter.",
            },
            {
                id: "rtoobe",
                ar: "رُطُوبَة",
                en: "humidity",
                enArabeezy: "rToobe",
                hint: "Very important for Gaza because it is by the sea. Use the clear chunk: فِي رُطُوبَة كْتِير.",
                exampleAr: "أَنَا طَلَعْت عَالْبَحَر بَسّ كَان فِي رُطُوبَة كْتِير مَعَ الشُّوب.",
                exampleArabeezy: "ana 6ala3t 3al-ba7ar bas kan fi rToobe kteer ma3 esh-shob.",
                exampleEn: "I went out to the beach but there was a lot of humidity along with the heat.",
            },

            {
                id: "hawa",
                ar: "هَوَا",
                en: "wind / air",
                enArabeezy: "hawa",
                hint: "Natural Gaza word. Strong wind = هَوَا قَوِي. A little wind = هَوَا خَفِيف.",
                exampleAr: "إِحْنَا قَعَدْنَا بِالضِّلّ عَشَان فِي هَوَا خَفِيف وَحِلُو.",
                exampleArabeezy: "i7na 2a3adna biD-Dill 3ashan fi hawa khafeef w 7ilu.",
                exampleEn: "We sat in the shade because there was a nice light breeze.",
            },
            {
                id: "matar",
                ar: "مَطَر / بِتْشَتِّي",
                en: "rain / it is raining",
                enArabeezy: "maTar / btshetti",
                hint: "'مَطَر' is rain (noun). 'بِتْشَتِّي' means it is raining (verb).",
                exampleAr: "أَخُوي أَخَذ الشَّمْسِيَّة مَعُه لأَنّو فِي مَطَر قَوِي عَالطَّرِيق.",
                exampleArabeezy: "akhoy akhad esh-shamsiyyeh ma3oh l'anno fi maTar 2awi 3aT-Tareeq.",
                exampleEn: "My brother took the umbrella with him because there's heavy rain on the road.",
            },
            {
                id: "shams",
                ar: "شَمْس",
                en: "sun",
                enArabeezy: "shams",
                hint: "Strong sun = الشَّمْس قَوِيَّة. Sunglasses = نَضَّارَة شَمْس.",
                exampleAr: "أُمّي حَكَتْلِي: قُوم اِقْعَد بِالشَّمْس عَشَان تِدْفَى شُوَيّ.",
                exampleArabeezy: "ummi 7akatli: 2oom i23ad bish-shams 3ashan tidfa shway.",
                exampleEn: "My mother told me: Get up and sit in the sun to warm up a bit.",
            },
            {
                id: "mshammes",
                ar: "مُشْمِس",
                en: "sunny",
                enArabeezy: "mishmis",
                hint: "For weather/day/sky.",
                exampleAr: "هُمَّ طَلَعُوا يِتْمَشَّوْا بِالسُّوق لِأَنُّه اليَوْم مُشْمِس وَدَافِي.",
                exampleArabeezy: "humma 6ala3o yitmashaw bis-souq l'anno el-yom mishmis w dafi",
                exampleEn: "They went out to walk around the market because today is sunny and warm",
            },

            {
                id: "ghayem",
                ar: "غَيْم",
                en: "clouds",
                enArabeezy: "ghayem",
                hint: "Natural chunk: فِي غَيْم كْتِير.",
                exampleAr: "أَنَا شُفْت غَيْم كْتِير فِي السَّمَا، بَيْنَهَا رَاح تِشْتِي.",
                exampleArabeezy: "ana shoft ghayem kteer fis-sama, baynha ra7 tishti.",
                exampleEn: "I saw a lot of clouds in the sky; it looks like it's going to rain.",
            },
            {
                id: "mghayyam",
                ar: "مْغَيَّم",
                en: "cloudy",
                enArabeezy: "mghayyam",
                hint: "Very natural spoken phrase.",
                exampleAr: "صَاحْبِي حَكَالِي إِنّو الجَوّ عِنْدُهُم مْغَيَّم مِن الصُّبْح.",
                exampleArabeezy: "Sa7bi 7akali inno el-jaw 3indahum mghayyam min eS-Sub7.",
                exampleEn: "My friend told me that the weather at their place has been cloudy since morning.",
            },
            {
                id: "saafi",
                ar: "صَافِي",
                en: "clear",
                enArabeezy: "Saafi",
                hint: "Used when the sky/weather is clear.",
                exampleAr: "السَّمَا اليَوم صَافْيَة وَمَا فِيش غَيْم بِالمَرَّة.",
                exampleArabeezy: "es-sama el-yom Sa3fyeh w ma feesh ghayem bil-marra.",
                exampleEn: "The sky today is clear and there are no clouds at all.",
            },
            {
                id: "ed_dunya",
                ar: "الدُّنْيَا",
                en: "the weather / outside conditions",
                enArabeezy: "ed-dunya",
                hint: "Very common in Gaza when talking about conditions outside: الدُّنْيَا شُوب، الجَوّ مْغَيَّم، الدُّنْيَا بِتْشَتِّي.",
                exampleAr: "إِحْنَا مَا طَلَعْنَاش مِن البَيْت لأَنّو الدُّنْيَا بِتْشَتِّي بَرَّا.",
                exampleArabeezy: "i7na ma 6ala3nash min el-bet l'anno ed-dunya btshetti barra.",
                exampleEn: "We didn't go out of the house because it's raining outside.",
            },
            {
                id: "ghobar",
                ar: "غَبَار",
                en: "dust",
                enArabeezy: "ghabar",
                hint: "Common with wind. Say: فِي غَبَار / الدُّنْيَا غَبَار.",
                exampleAr: "دِيرُوا بَالْكُم وَأَنْتُم طَالْعِين، فِي هَوَا وَغَبَار كْتِير بَرَّا.",
                exampleArabeezy: "deeroolkum w antum 6al3een, fi hawa w ghabar kteer barra.",
                exampleEn: "Be careful while going out; there is a lot of wind and dust outside.",
            },
            
            {
                id: "el_sayf",
                ar: "الصَّيْف",
                en: "summer",
                enArabeezy: "eS-Sayf",
                hint: "In Gaza, summer usually means شُوب + رُطُوبَة. Months can appear in examples: شَهْر سَبْعَة / شَهْر تَمَانِيَة.",
                exampleAr: "أَخُوي بِحِبِّش الصَّيْف فِي غَزَّة عَشَان الشُّوب وَالرُّطُوبَة.",
                exampleArabeezy: "akhoy b7ebbish es-Sayf fi Ghazza 3ashan esh-shob w er-rToobe.",
                exampleEn: "My brother doesn't like summer in Gaza because of the heat and humidity.",
            },
            {
                id: "esh_sheta",
                ar: "الشِّتَا",
                en: "winter / rain season",
                enArabeezy: "esh-sheta",
                hint: "In speech, الشِّتَا can mean winter and sometimes rainy weather.",
                exampleAr: "أَنَا وَعَيْلْتِي بْنِحِبّ الشِّتَا عَشَان بْنِقْعَد مَعَ بَعَض وَبْنِشْرَب شَاي.",
                exampleArabeezy: "ana w 3aylti bni7ebb esh-sheta 3ashan bni23ad ma3 ba3aD w bnishrab shay.",
                exampleEn: "My family and I love winter because we sit together and drink tea.",
            },
            {
                id: "er_rabee3",
                ar: "الرَّبِيع",
                en: "spring",
                enArabeezy: "er-rabee3",
                hint: "Usually good weather for walking and visiting family.",
                exampleAr: "هُمَّ بِسَافْرُوا كُلّ سَنَة فِي الرَّبِيع لأَنّو الجَوّ بِيْكُون دَافِي وَحِلُو.",
                exampleArabeezy: "humma bisafro koll sana fir-rabee3 l'anno el-jaw beekoon dafi w 7ilu.",
                exampleEn: "They travel every year in spring because the weather is warm and nice.",
            },
            {
                id: "el_khareef",
                ar: "الخَرِيف",
                en: "fall / autumn",
                enArabeezy: "el-khareef",
                hint: "Between summer and winter. Weather starts changing.",
                exampleAr: "فِي الخَرِيف بِيَبْدَأ الهَوَا يِبْرَد شُوَيّ بَاللَّيْل.",
                exampleArabeezy: "fil-khareef beyabda el-hawa yibrad shway bil-lel.",
                exampleEn: "In autumn, the air starts getting a bit colder at night.",
            },
            {
                id: "fasl",
                ar: "فَصِل",
                en: "season",
                enArabeezy: "faSl / faSel",
                hint: "Plural: فُصُول.",
                exampleAr: "إِحْنَا بْنِعْتَبِر الرَّبِيع أَحْلَى فَصِل فِي السَّنَة.",
                exampleArabeezy: "i7na bni3taber er-rabee3 a7la faSl fis-sana.",
                exampleEn: "We consider spring the best season of the year.",
            },
            {
                id: "a7san_min",
                ar: "أَحْسَن مِن",
                en: "better than",
                enArabeezy: "a7san min",
                hint: "Main comparison chunk. Other weather chunks in examples: أَبْرَد مِن، أَحَرّ مِن، أَلْطَف مِن.",
                exampleAr: "أُمّي حَكَت إِنّو الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح، المَطَر وَقَّف.",
                exampleArabeezy: "ummi 7akat inno el-jaw el-yom a7san min embare7, el-maTar wa22af.",
                exampleEn: "My mother said the weather today is better than yesterday; the rain stopped.",
            },
            {
                id: "darajet_el7arara",
                ar: "دَرَجَة الحَرَارَة",
                en: "temperature",
                enArabeezy: "darajet el-7arara",
                hint: "Useful when asking about numbers and weather. Example: قَدِّيش دَرَجَة الحَرَارَة؟",
                exampleAr: "سَأَلْنَا عَن دَرَجَة الحَرَارَة اليَوم، حَكُوا لْنَا إِنَّهَا خَمْسَة وَعِشْرِين.",
                exampleArabeezy: "sa'alna 3an darajet el-7arara el-yom, 7ako lna innaha khamsa w 3ishreen.",
                exampleEn: "We asked about the temperature today; they told us it is twenty-five.",
            },
            {
                id: "ma_basta7mel",
                ar: "مَا بَسْتَحْمِل",
                en: "I cannot stand",
                enArabeezy: "ma basta7mel",
                hint: "Strong opinion. Use with heat, humidity, cold, noise, or waiting.",
                exampleAr: "أَنَا مَا بَسْتَحْمِل السَّقْعَة الكْتِيرَة، بَلْبَس طَاقِيَّة صُوف وَجَاكِيت تَقِيل.",
                exampleArabeezy: "ana ma basta7mel es-sa2'a el-kteera, balbas ta2iyyet soof w jacket ta2eel.",
                exampleEn: "I can't stand extreme cold; I wear a beanie and a heavy jacket.",
            },
            {
                id: "ed_dill",
                ar: "الضِّلّ",
                en: "the shade",
                enArabeezy: "eD-Dill",
                hint: "Useful in hot Gaza weather. Common advice: اِقْعَد بِالضِّلّ.",
                exampleAr: "صَاحْبِي قَعَد بِالضِّلّ عَشَان الشَّمْس كَانَت قَوِيَّة كْتِير.",
                exampleArabeezy: "Sa7bi 2a3ad biD-Dill 3ashan esh-shams kanat 2awiyeh kteer.",
                exampleEn: "My friend sat in the shade because the sun was very strong.",
            },
            {
                id: "ra3d_barq",
                ar: "رَعْد وَبَرْق",
                en: "thunder and lightning",
                enArabeezy: "ra3d w barq",
                hint: "Useful recognition weather phrase. Keep it light for this unit; students do not need storm vocabulary yet.",
                exampleAr: "إِحْنَا سِمِعْنَا رَعْد وَشُفْنَا بَرْق كْتِير بَاللَّيْل لَمَّا كَانَت بِتْشَتِّي.",
                exampleArabeezy: "i7na semi3na ra3d w shufna barq kteer bil-lel lamma kanat btshetti.",
                exampleEn: "We heard thunder and saw a lot of lightning at night when it was raining.",
            },
            {
                id: "talj",
                ar: "تَلْج",
                en: "snow",
                enArabeezy: "talj",
                hint: "Recognition word. Snow is not common in Gaza, but students hear it when talking about other cities/countries.",
                exampleAr: "أَخُوي شَاف التَّلْج لأَوَّل مَرَّة لَمَّا سَافَر عَالْقُدْس بِالشِّتَا.",
                exampleArabeezy: "akhoy shaf et-talj l-awwal marra lamma safar 3al-2uds bish-sheta.",
                exampleEn: "My brother saw snow for the first time when he traveled to Jerusalem in winter.",
            },
            {
                id: "dabab",
                ar: "ضَبَاب",
                en: "fog",
                enArabeezy: "dabab",
                hint: "Use with roads and visibility: فِي ضَبَاب عَالطَّرِيق.",
                exampleAr: "هُمَّ مِشْيُوا بِشْوِيشْ بالْسَّيَّارَة لأَنُّو كَان فِيه ضَبَاب كْتِير الصُّبْح.",
                exampleArabeezy: "humma mishyu b-shweesh bis-sayyara l'anno kan feeh dabab kteer eS-Sub7.",
                exampleEn: "They drove slowly in the car because there was a lot of fog in the morning."
            },
            {
                id: "asfeh",
                ar: "عَاصْفَة",
                en: "storm",
                enArabeezy: "3aSfeh",
                hint: "Useful but less frequent than rain/wind. Do not overload students with rare storm types in this unit.",
                exampleAr: "الأَخْبَار فِي التِّلْفِزْيُون حَكَت إِنُّو فِي عَاصِفَة رَاح تِيجِي باللَّيْل.",
                exampleArabeezy: "el-akhbar fit-tilfizyon 7akat inno fi 3aSfeh ra7 teeji bil-lel.",
                exampleEn: "The news on TV said there is a storm coming tonight.",
            },


        ],
    },

    dialogue: {
        title: "Weather & Transportation - Waiting for the Bus",
        setting: "Rami and Noor are waiting for the bus on a windy, cloudy day. They talk about weather, transportation, family advice, and favorite seasons.",
        lines: [
            { speaker: "Rami", ar: "يَا سَاتِر... شُو هَالهَوَا!", arArabeezy: "ya sater... shoo hal-hawa!", en: "Oh wow... what wind!" },
            { speaker: "Noor", ar: "ههههه قُلْتِلَك خُد جَاكِيت.", arArabeezy: "hahaha oltillak khod jacket.", en: "Haha, I told you to take a jacket." },
            { speaker: "Rami", ar: "وَالله الصُّبُح كَان الجَوّ مْنِيح، مَا تَوَقَّعْت يِقْلِب هَيْك.", arArabeezy: "wallah eS-Sobo7 kan el-jaw mnee7, ma tawaqqa3t yi2lib hek.", en: "The weather was good in the morning. I didn’t expect it to change like this." },
            { speaker: "Noor", ar: "هَالأَيَّام مَا بْتِعْرَف عَلَى الجَوّ. الصُّبُح بَرْد، الضُّهُر شُوب، وَبِاللَّيْل بَرْد مِن جَدِيد.", arArabeezy: "hal-ayam ma bti3raf 3ala el-jaw. eS-Sobo7 bard, eD-Duher shoob, w bil-leil bard min jadeed.", en: "These days you can’t understand the weather. Morning is cold, noon is hot, and at night it gets cold again." },
            { speaker: "Rami", ar: "شَكْلْهَا بَدْهَا تِشْتِي.", arArabeezy: "shakilha baddha tishti.", en: "Looks like it’s going to rain." },
            { speaker: "Noor", ar: "مِيَّة بِالمِيَّة. شُوف الغَيْم كِيف صَار.", arArabeezy: "meyye bil-meyye. shoof el-gheim keef Sar.", en: "Definitely. Look at how the clouds are now." },
            { speaker: "Rami", ar: "بَس نَاقِص البَاص يِتْأَخَّر.", arArabeezy: "bas na2iS el-baS yit2akhkhar.", en: "All we need now is for the bus to be late." },
            { speaker: "Noor", ar: "لَا تِحْكِي هَيْك، أَنَا إِذَا اتْأَخَّرْت كَمَان خَمْس دَقَايِق الأُسْتَاذ بِسَكِّر البَاب.", arArabeezy: "la ti7ki hek, ana iza it2akhkhart kaman khams da2aye2 el-ustaz bisakkir el-bab.", en: "Don’t say that. If I’m five more minutes late, the professor will close the door." },
            { speaker: "Rami", ar: "لِسَّه مَا إِجَاش؟", arArabeezy: "lissa ma ijash?", en: "It still hasn’t come?" },
            { speaker: "Noor", ar: "صَارْلِي رُبُع سَاعَة بَسْتَنَّاه.", arArabeezy: "Sarli rob3 sa3a bastannah.", en: "I’ve been waiting for it for fifteen minutes." },
            { speaker: "Rami", ar: "يَا زَلَمَة... لَمَّا الدُّنْيَا تْغَيِّم هَيْك، المُوَاصَلَات بْتِتْأَخَّر.", arArabeezy: "ya zalame... lamma ed-dinya tghayyim hek, el-mowaSalat btit2akhkhar.", en: "Man... when it gets cloudy like this, transportation gets delayed." },
            { speaker: "Noor", ar: "آه، وَالنَّاس كُلْهَا بْتِطْلَع بِنَفْس الوَقْت.", arArabeezy: "ah, w en-nas kolha btiTla3 binafs el-wa2t.", en: "Yes, and everyone goes out at the same time." },
            { speaker: "Rami", ar: "أَنَا إِمْبَارِح رِجِعْت مَشِي نُصّ الطَّرِيق.", arArabeezy: "ana embare7 riji3t mashi noSS eT-Taree2.", en: "Yesterday I walked half the way back." },
            { speaker: "Noor", ar: "لِيش؟", arArabeezy: "leesh?", en: "Why?" },
            { speaker: "Rami", ar: "مَا لْقِيت وَلَا تَاكْسِي فَاضِي.", arArabeezy: "ma l2eet wala taxi faDi.", en: "I couldn’t find a single empty taxi." },
            { speaker: "Noor", ar: "الحَمْدُ لله إِنِّي رِجِعْت بَدْرِي.", arArabeezy: "el-7amdullah inni riji3t badri.", en: "Thank God I came back early." },
            { speaker: "Rami", ar: "أَهْلِك كِيف؟ الجَوّ أَثَّر عَلَيْهِم؟", arArabeezy: "ahlik keef? el-jaw aththar 3aleihom?", en: "How’s your family? Did the weather affect them?" },
            { speaker: "Noor", ar: "إِمِّي مِن الصُّبُح بْتِحْكِيلِي: لَا تِنْسِي الجَاكِيت، وَلَا تِطْلَعِي بَدُون شَمْسِيَّة.", arArabeezy: "immi min eS-Sobo7 bti7keeli: la tinsi el-jacket, w la tiTla3i bidoon shamsiyye.", en: "My mom has been telling me since the morning: don’t forget the jacket, and don’t go out without an umbrella." },
            { speaker: "Rami", ar: "ههههه... الأُمَّهَات كُلْهُم نَفْس الحَكِي.", arArabeezy: "hahaha... el-ommahat kolhom nafs el-7aki.", en: "Haha... all mothers say the same things." },
            { speaker: "Noor", ar: "وَإِنْت؟", arArabeezy: "w inta?", en: "And you?" },
            { speaker: "Rami", ar: "أَبُوي مِن إِمْبَارِح بْيِقُولِّي: الدُّنْيَا بَدْهَا تِشْتِي، لَا تِغْسِل السَّيَّارَة. 😂", arArabeezy: "aboy min embare7 bi2olli: ed-dinya baddha tishti, la tighsil es-sayyara.", en: "My dad has been telling me since yesterday: it’s going to rain, don’t wash the car." },
            { speaker: "Noor", ar: "هههههه... شَكْلُه كَان عِنْدُه حَقّ.", arArabeezy: "hahaha... shaklo kan 3indo 7a2.", en: "Haha... looks like he was right." },
            { speaker: "Rami", ar: "أَكِيد.", arArabeezy: "akeed.", en: "Of course." },
            { speaker: "Noor", ar: "أَنَا أَكْتَر إِشِي بَكْرَهُه بِالرُّطُوبَة.", arArabeezy: "ana aktar ishi bakraho bir-rToobe.", en: "The thing I hate most is humidity." },
            { speaker: "Rami", ar: "آه وَالله... بْتِحِسّ البَيْت مَخْنُوق.", arArabeezy: "ah wallah... bti7iss el-beit makhnoo2.", en: "Yes, really... it makes the house feel stuffy." },
            { speaker: "Noor", ar: "خُصُوصًا بِاللَّيْل.", arArabeezy: "khuSooSan bil-leil.", en: "Especially at night." },
            { speaker: "Rami", ar: "بَس مَع هَيْك، أَنَا بَحِبّ الشِّتَا أَكْتَر مِن الصَّيْف.", arArabeezy: "bas ma3 hek, ana ba7ibb esh-sheta aktar min eS-Seif.", en: "But even so, I like winter more than summer." },
            { speaker: "Noor", ar: "أَنَا العَكْس.", arArabeezy: "ana el-3aks.", en: "I’m the opposite." },
            { speaker: "Rami", ar: "لِيش؟", arArabeezy: "leesh?", en: "Why?" },
            { speaker: "Noor", ar: "الصَّيْف أَسْهَل بِالنِّسْبَة إِلِي. بَتْحَرَّك أَكْتَر، وَبَحِبّ أَقْعُد عَالبَحْر.", arArabeezy: "eS-Seif ashal bin-nisbe ili. bat7arrak aktar, w ba7ibb a2od 3al-ba7er.", en: "Summer is easier for me. I move around more, and I like sitting by the sea." },
            { speaker: "Rami", ar: "أَمَّا أَنَا أَوَّل مَا يِيجِي الصَّيْف بَزْهَق مِن الشُّوب.", arArabeezy: "amma ana awwal ma yeeji eS-Seif bazha2 min esh-shoob.", en: "As for me, as soon as summer comes, I get tired of the heat." },
            { speaker: "Noor", ar: "الرَّبِيع أَحْسَن إِشِي.", arArabeezy: "er-rabee3 a7san ishi.", en: "Spring is the best." },
            { speaker: "Rami", ar: "هَاي أَوَّل مَرَّة نِتَّفِق اليَوْم. 😂", arArabeezy: "hay awwal marra nittafi2 el-yom.", en: "This is the first time we agree today." },
            { speaker: "Noor", ar: "ههههه... عَنْجَد.", arArabeezy: "hahaha... 3anjad.", en: "Haha... seriously." },
            { speaker: "Rami", ar: "شُفْتِي التَّطْبِيق؟", arArabeezy: "shofti et-taTbee2?", en: "Did you check the app?" },
            { speaker: "Noor", ar: "لَا، شُو بِيحْكِي؟", arArabeezy: "la, shoo bi7ki?", en: "No, what does it say?" },
            { speaker: "Rami", ar: "بِيْقُول بُكْرَة الجَوّ أَلْطَف، وَمَا فِي مَطَر.", arArabeezy: "bi2ool bokra el-jaw alTaf, w ma fi maTar.", en: "It says tomorrow the weather will be nicer, and there’s no rain." },
            { speaker: "Noor", ar: "الحَمْدُ لله، بُكْرَة عِنْدِي مِشْوَار طَوِيل.", arArabeezy: "el-7amdullah, bokra 3indi mishwar Taweel.", en: "Thank God. Tomorrow I have a long errand." },
            { speaker: "Rami", ar: "وِين رَايْحَة؟", arArabeezy: "wayn ray7a?", en: "Where are you going?" },
            { speaker: "Noor", ar: "عِنْدِي مَوْعِد وَبَعْدَهَا بَدِّي أَمُرّ عَسِتِّي.", arArabeezy: "3indi maw3id w ba3dha baddi amorr 3a-sitti.", en: "I have an appointment, and after that I want to stop by my grandmother’s." },
            { speaker: "Rami", ar: "الله يْخَلِّيلِك إِيَّاهَا.", arArabeezy: "allah ykhaleelik iyyaha.", en: "May God keep her for you." },
            { speaker: "Noor", ar: "آمِين.", arArabeezy: "ameen.", en: "Amen." },
            { speaker: "Rami", ar: "آه... إِجَا البَاص أَخِيرًا.", arArabeezy: "ah... ija el-baS akheeran.", en: "Ah... the bus finally came." },
            { speaker: "Noor", ar: "يَلَّا الحَمْدُ لله.", arArabeezy: "yalla el-7amdullah.", en: "Finally, thank God." },
            { speaker: "Rami", ar: "دِيرِي بَالِك عَحَالِك.", arArabeezy: "deeri balik 3a7alik.", en: "Take care of yourself." },
            { speaker: "Noor", ar: "وَإِنْت كَمَان.", arArabeezy: "w inta kaman.", en: "You too." }
        ],

        questions: [
            { ar: "وِين كَان رَامِي وَنُور؟", en: "Where were Rami and Noor?" },
            { ar: "لِيش كَانُوا مُسْتَنِّيِين؟", en: "Why were they waiting?" },
            { ar: "كِيف كَان الجَوّ؟", en: "How was the weather?" },
            { ar: "لِيش نُور كَانِت خَايْفَة تِتْأَخَّر؟", en: "Why was Noor afraid of being late?" },
            { ar: "شُو صَار مَع رَامِي إِمْبَارِح؟", en: "What happened with Rami yesterday?" },
            { ar: "شُو كَانِت تِنْصَح أُمّ نُور؟", en: "What did Noor’s mother advise her?" },
            { ar: "شُو قَال أَبُو رَامِي عَن السَّيَّارَة؟", en: "What did Rami’s father say about the car?" },
            { ar: "مِين بْحِبّ الشِّتَا؟", en: "Who likes winter?" },
            { ar: "مِين بْحِبّ الصَّيْف؟", en: "Who likes summer?" },
            { ar: "أَي فَصْل اتَّفَقُوا إِنُّه أَلْطَف؟", en: "Which season did they agree was the nicest?" },
            { ar: "شُو كَان تَوَقُّع الطَّقْس لِبُكْرَة؟", en: "What was the weather forecast for tomorrow?" },
            { ar: "وِين كَانِت رَايْحَة نُور بُكْرَة؟", en: "Where was Noor going tomorrow?" }
        ],
    },

    grammar: [

        {
            title: "3. People versus non-human plurals",
            short: "الطُّلَّاب تَعْبَانِين — الشَّوَارِع فَاضْيَة",
            description: "Human plural groups normally take plural descriptions in Palestinian Arabic. Non-human plural nouns—streets, cars, days, clouds—very often take a feminine-singular description, especially as a collective scene. Everyday speech allows some plural agreement too, but the feminine-singular pattern is essential for understanding natural Arabic.",
            table: {
                title: "Agreement by meaning",
                headers: ["Subject type", "Subject", "Description", "Meaning"],
                rows: [
                    ["human plural", "النَّاس", "مِزْعُوجِين", "the people are bothered"],
                    ["human plural", "الطُّلَّاب", "بَرْدَانِين", "the students feel cold"],
                    ["non-human plural", "الشَّوَارِع", "مَبْلُولَة", "the streets are wet"],
                    ["non-human plural", "السَّيَّارَات", "وَاقْفَة", "the cars are stopped"],
                    ["non-human plural", "الغْيُوم", "تْقِيلَة", "the clouds are heavy"],
                ],
            },
            examples: [
                { ar: "النَّاس تَعْبَانِين مِن الحَرّ وَالرُّطُوبَة.", arabeezy: "en-nas ta3baneen min el-7arr wir-ruTooba.", en: "People are tired from the heat and humidity." },
                { ar: "الشَّوَارِع مَبْلُولَة عَشَان المَطَر.", arabeezy: "esh-shaware3 mablooleh 3ashan el-maTar.", en: "The streets are wet because of the rain." },
                { ar: "السَّيَّارَات وَاقْفَة وَالطَّرِيق زَحْمَة.", arabeezy: "es-sayyarat waqfeh wiT-Tareeq za7meh.", en: "The cars are stopped and the road is congested." },
            ],
            commonMistakes: [
                "Do not copy human plural agreement onto every object. الشَّوَارِع مَبْلُولَة is a core natural pattern.",
                "النَّاس is grammatically a collective word but refers to people, so plural human agreement such as تَعْبَانِين is natural.",
                "You may hear non-human plural adjectives in some dialectal contexts. Learn the feminine-singular pattern first, then notice real variation rather than treating it as an error everywhere.",
            ],
            exercises: [
                { prompt: "Choose the natural core agreement: ‘The streets are empty.’", options: ["الشَّوَارِع فَاضْيَة.", "الشَّوَارِع فَاضْيِين.", "الشَّوَارِع فَاضِي."], correct: "الشَّوَارِع فَاضْيَة.", explanation: "A non-human plural commonly takes a feminine-singular description." },
                { prompt: "Complete the human description: الطُّلَّاب ___. (tired)", options: ["تَعْبَانِين", "تَعْبَانَة", "تَعْبَان"], correct: "تَعْبَانِين", explanation: "A human plural group takes plural agreement." },
                { prompt: "Why is وَاقْفَة singular in السَّيَّارَات وَاقْفَة?", options: ["Non-human plurals often take feminine-singular agreement.", "سيارات means one car.", "The sentence is past tense."], correct: "Non-human plurals often take feminine-singular agreement.", explanation: "The cars form a non-human plural scene, triggering common feminine-singular agreement." },
            ],
        },

    ],

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "weather_mc1",
                type: "choose",
                prompt: "Choose the Gaza Palestinian Arabic word for: the weather.",
                options: ["الجَوّ", "الشُّغُل", "العِيلَة", "الأُجْرَة"],
                correct: "الجَوّ",
            },
            {
                id: "weather_mc2",
                type: "complete",
                prompt: "Complete the Arabic sentence for: It is raining heavily now.\nهَلْقِيت ___ كْتِير.",
                options: ["بِتْشَتِّي", "رُطُوبَة", "هَوَا", "دِفَا"],
                correct: "بِتْشَتِّي",
            },
            {
                id: "weather_mc3",
                type: "complete",
                prompt: "Complete the Arabic sentence for: The weather is cloudy today.\nالجَوّ اليَوم ___.",
                options: ["مْغَيَّم", "شَمْس", "غَيْم", "صَافِي"],
                correct: "مْغَيَّم",
            },
            {
                id: "weather_mc4",
                type: "choose",
                prompt: "Choose the Gaza Palestinian Arabic word for: winter.",
                options: ["الشِّتَا", "الصَّيْف", "الرَّبِيع", "الخَرِيف"],
                correct: "الشِّتَا",
            },
            {
                "id": "weather_mc5",
                "type": "reorder",
                "prompt": "Reorder the Arabic words to match: In autumn, the weather starts to get a bit cold at night.",
                "options": [
                    "فِي",
                    "بَاللَّيْل.",
                    "الخَرِيف",
                    "شُوَيّ",
                    "الهَوَا",
                    "بِيَبْدَأ",
                    "يِبْرَد"
                ],
                "correct": [
                    "فِي",
                    "الخَرِيف",
                    "بِيَبْدَأ",
                    "الهَوَا",
                    "يِبْرَد",
                    "شُوَيّ",
                    "بَاللَّيْل."
                ]
            },
            {
                id: "weather_mc5",
                type: "complete",
                prompt: "Complete the Arabic sentence for: The weather is better in the shade.\nبِالضِّلّ الجَوّ ___.",
                options: ["أَحْسَن", "رَعْد", "بَرْق", "حَرَارَة"],
                correct: "أَحْسَن",
            },
            { id: "weather_mc6", type: "choose", prompt: "Choose the Gaza Palestinian Arabic phrase for: take with you.", options: ["خُد مَعَك", "دِير بَالَك", "مَا بَسْتَحْمِل", "أَحْسَن مِن"], correct: "خُد مَعَك" },
        ],
    },

    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        quiz: [
            {
                id: "weather_q1",
                questionAr: "Choose the English meaning of: «كِيف الجَوّ عِنْدَك؟»",
                optionsEn: ["How is the weather where you are?", "Where do you live?", "What is your name?"],
                correctIndex: 0,
            },
            {
                id: "weather_q2",
                questionAr: "Choose the natural advice when it is raining on the road.",
                optionsEn: ["دِير بَالَك عَالطَّرِيق.", "شُو اِسْمَك؟", "أَنَا عِنْدِي أَخ."],
                correctIndex: 0,
            },
            {
                id: "weather_q3",
                questionAr: "Who does the feminine word «بَرْدَانَة» describe?",
                optionsEn: ["to/about a woman feeling cold", "to/about a man feeling hot", "about rain"],
                correctIndex: 0,
            },
            {
                id: "weather_q4",
                questionAr: "Choose how to say: “I cannot stand the heat.”",
                optionsEn: ["مَا بَسْتَحْمِل الشُّوب.", "بَحِبّ الشِّتَا.", "الجَوّ مْغَيَّم."],
                correctIndex: 0,
            },
            {
                id: "weather_q5",
                questionAr: "Choose who the instruction «دِيرِي بَالِك» addresses.",
                optionsEn: ["to a woman", "to a man", "to a group"],
                correctIndex: 0,
            },
            {
                id: "weather_q6",
                questionAr: "Choose the sentence that contains a comparison.",
                optionsEn: ["الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح.", "مَرْحَبَا، كِيفَك؟", "اِسْمِي نُور."],
                correctIndex: 0,
            },
            {
                id: "weather_q7",
                questionAr: "Choose the situation where you often hear: «فِي رُطُوبَة كْتِير»",
                optionsEn: ["Gaza/coastal weather", "family introductions", "asking for a name"],
                correctIndex: 0,
            },
            {
                id: "weather_q8",
                questionAr: "Choose the phrase that naturally starts weather small talk.",
                optionsEn: ["وَالله الجَوّ اليَوم حِلُو.", "بَدِّي حِسَاب البَنْك.", "عِنْدِي اِمْتِحَان رِيَاضِيَّات."],
                correctIndex: 0,
            },
            {
                id: "weather_q9",
                questionAr: "Choose the English meaning of: «الجَوّ مْغَيَّم»",
                optionsEn: ["It is cloudy outside.", "It is very sunny.", "It is my first day."],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Give a weather update: describe yesterday, today, and tomorrow; make one comparison and give one piece of advice.",
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "شُوب", arabeezy: "shoob", en: "hot weather / heat" },
                    { ar: "بَرْد", arabeezy: "bard", en: "cold weather" },
                    { ar: "رُطُوبَة", arabeezy: "rToobeh", en: "humidity" },
                    { ar: "مَطَر", arabeezy: "maTar", en: "rain" },
                    { ar: "مْغَيَّم", arabeezy: "mghayyam", en: "cloudy" },
                    { ar: "أَحْسَن مِن", arabeezy: "a7san min", en: "better than" },
                ],
                multipleChoice: [
                    { prompt: "Choose the feminine form of بَرْدَان (bardan).", options: ["بَرْدَانَة (bardaneh)", "بَرْد (bard)", "دَافِيَة (dafiyeh)"], correct: "بَرْدَانَة (bardaneh)" },
                    { prompt: "Choose the sentence that compares two days.", options: ["الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح.", "اليَوم فِي هَوَا.", "خُد مَعَك مَيّ."], correct: "الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح." },
                ],
            },
            {
                title: "B - Weather grammar practice",
                fillInTheBlank: [
                    { prompt: "الجَوّ اليَوم أَحْسَن ___ اِمْبَارِح.", arabeezy: "el-jaww el-yom a7san ___ imbari7.", cueEn: "than", answer: "مِن" },
                    { prompt: "اِمْبَارِح ___ الجَوّ حَارّ.", arabeezy: "imbari7 ___ el-jaww 7arr.", cueEn: "was", answer: "كَان" },
                    { prompt: "بُكْرَا الجَوّ ___ يِكُون أَلْطَف.", arabeezy: "bukra el-jaww ___ ykoon alTaf.", cueEn: "will", answer: "رَاح" },
                    { prompt: "الجَوّ مْغَيَّم وَ___ هَوَا.", arabeezy: "el-jaw mghayyam w ___ hawa.", cueEn: "there is", answer: "فِي" },
                    { prompt: "هِيَّ ___ عَشَان الجَوّ بَارِد.", arabeezy: "hiyyeh ___ 3ashan el-jaww bared.", cueEn: "cold (feminine)", answer: "بَرْدَانَة" },
                    { prompt: "هُوَّ مَا ___ الشُّوب مَع الرُّطُوبَة.", arabeezy: "huwwe ma ___ esh-shoob ma3 er-ruToobeh.", cueEn: "can stand", answer: "بِسْتَحْمِل" },
                    { prompt: "لَمَّا الدُّنْيَا شُوب، ___ مَعَك مَيّ.", arabeezy: "lamma ed-dinya shob, ___ ma3ak may.", cueEn: "take (command, masculine)", answer: "خُد" },
                    { prompt: "فِي مَطَر عَالطَّرِيق؛ ___ بَالَك.", arabeezy: "fi maTar 3aT-Tareeq; ___ balak.", cueEn: "take care (command, masculine)", answer: "دِير" },
                    { prompt: "الصَّيف فِي غَزَّة ___ مِن الشِّتَا.", arabeezy: "eS-Seif fi ghazzeh ___ min esh-shita.", cueEn: "hotter", answer: "أَحَرّ" },
                    { prompt: "Review: بَرُوح عَالشُّغُل ___ البَاص.", arabeezy: "baroo7 3ash-shughul ___ el-bas.", cueEn: "by", answer: "بِـ" },
                    { prompt: "Review: هُمَّ ___ فِي المَكْتَب اليَوم.", arabeezy: "humme ___ fil-maktab el-yom.", cueEn: "work (they)", answer: "بِشْتِغْلُوا" },
                    { prompt: "Review: اِتْأَخَّرْت ___ الزَّحْمَة.", arabeezy: "it2akhkhart ___ ez-za7meh.", cueEn: "because of", answer: "عَشَان" },
                ],
                correctTheMistake: [
                    { prompt: "Correct the word order: مْغَيَّم الجَوّ.", arabeezy: "mghayyam el-jaw.", answer: "الجَوّ مْغَيَّم." },
                    { prompt: "Correct: هِيَّ بَرْدَان.", arabeezy: "hiyyeh bardan.", answer: "هِيَّ بَرْدَانَة." },
                    { prompt: "Correct the past: اِمْبَارِح الجَوّ يِكُون حَارّ.", arabeezy: "imbari7 el-jaww ykoon 7arr.", answer: "اِمْبَارِح كَان الجَوّ حَارّ." },
                    { prompt: "Correct the future: بُكْرَا الجَوّ كَان أَحْسَن.", arabeezy: "bukra el-jaww kan a7san.", answer: "بُكْرَا الجَوّ رَاح يِكُون أَحْسَن." },
                    { prompt: "Correct the comparison: اليَوم أَحْسَن عَن اِمْبَارِح.", arabeezy: "el-yom a7san 3an imbari7.", answer: "اليَوم أَحْسَن مِن اِمْبَارِح." },
                    { prompt: "Correct the command to a woman: خُد مَعَك مَيّ.", arabeezy: "khod ma3ik may.", answer: "خُدِي مَعِك مَيّ." },
                ],
                reorderSentences: [
                    { prompt: "Build: Yesterday was hotter than today.", arabeezy: "imbari7 kan a7arr min el-yom.", words: ["كَان أشوب","اِمْبَارِح",  "مِن اليَوم."], answer: "اِمْبَارِح كَان أَحَرّ مِن اليَوم." },
                    { prompt: "Build: Tomorrow will be better.", arabeezy: "bukra ra7 ykoon a7san.", words: [ "رَاح يِكُون","بُكْرَا", "أَحْسَن."], answer: "بُكْرَا رَاح يِكُون أَحْسَن." },
                    { prompt: "Build: Take water with you.", arabeezy: "khod ma3ak may.", words: ["خُد مَعَك", "مَيّ."], answer: "خُد مَعَك مَيّ." },
                    { prompt: "Review: There is traffic on the road.", arabeezy: "fi za7meh 3aT-Taree2.", words: ["فِي زَحْمَة", "عَالطَّرِيق."], answer: "فِي زَحْمَة عَالطَّرِيق." },
                    { prompt: "Build: Summer in Gaza is hotter than winter.", arabeezy: "eS-Seif fi ghazzeh a7arr min esh-shita.", words: ["أشوب","الصَّيف فِي غَزَّة",  "مِن الشِّتَا."], answer: "الصَّيف فِي غَزَّة أَحَرّ مِن الشِّتَا." },
                    { prompt: "Review: They work in the office today.", arabeezy: "humme bishtighlu fil-maktab el-yom.", words: ["بِشْتِغْلُوا", "هُمَّ","فِي المَكْتَب",  "اليَوم."], answer: "هُمَّ بِشْتِغْلُوا فِي المَكْتَب اليَوم." },
                ],
            },
        ],
        translation: [
            { id: "weather_t1", type: "enToAr", textEn: "Hi, how are you? How is the weather where you are?", textAr: "مَرْحَبَا، كِيفَك؟ كِيف الجَوّ عِنْدَك؟" },
            { id: "weather_t2", type: "arToEn", textEn: "Today the weather is nice, but there is wind.", textAr: "اليَوم الجَوّ حِلُو، بَس فِي هَوَا." },
            { id: "weather_t3", type: "enToAr", textEn: "There is a lot of heat and humidity today.", textAr: "فِي شُوب وَرُطُوبَة كْتِير اليَوم." },
            { id: "weather_t4", type: "arToEn", textEn: "It is raining outside; be careful on the road.", textAr: "بَرَّه بِتْشَتِّي، دِير بَالَك عَالطَّرِيق." },
            { id: "weather_t5", type: "enToAr", textEn: "It is hot today; take water with you.", textAr: "اليَوم شُوب، خُد مَعَك مَيّ." },
            { id: "weather_t6", type: "arToEn", textEn: "Yesterday the weather was hotter than today.", textAr: "اِمْبَارِح كَان الجَوّ أَحَرّ مِن اليَوم." },
            { id: "weather_t7", type: "enToAr", textEn: "Tomorrow the weather will be better than today.", textAr: "بُكْرَا الجَوّ رَاح يِكُون أَحْسَن مِن اليَوم." },
            { id: "weather_t8", type: "arToEn", textEn: "I cannot stand heat with humidity.", textAr: "مَا بَسْتَحْمِل الشُّوب مَع الرُّطُوبَة." },
            { id: "weather_t9", type: "enToAr", textEn: "I like winter because of the rain and hot tea.", textAr: "بَحِبّ الشِّتَا عَشَان المَطَر وَالشَّاي السَّاخِن." },
            { id: "weather_t10", type: "arToEn", textEn: "In summer, there is a lot of humidity in Gaza.", textAr: "فِي الصَّيْف فِي رُطُوبَة كْتِير فِي غَزَّة." },
            { id: "weather_t11", type: "enToAr", textEn: "There is dust on the road; be careful.", textAr: "فِي غَبَار عَالطَّرِيق، دِير بَالَك." },
            { id: "weather_t12", type: "arToEn", textEn: "If the weather is sunny on Friday, we will visit my grandmother.", textAr: "إِذَا الجَوّ مُشْمِس يَوم الجُمْعَة، رَاح نْرُوح عِنْد سِتِّي." },
            { id: "weather_t13", type: "enToAr", textEn: "I have university today, but the weather is windy and cloudy.", textAr: "عِنْدِي جَامْعَة اليَوم، بَس الجَوّ مْغَيَّم وَفِي هَوَا." },
            { id: "weather_t14", type: "arToEn", textEn: "Really? It rained yesterday?", textAr: "عَنْ جَدّ؟ اِمْبَارِح مَطَّرَت؟" },
            { id: "weather_t15", type: "enToAr", textEn: "God be with you, and tell me when you arrive.", textAr: "الله مَعَك، وَطَمِّنِّي بَس تُوصَل." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 60-90 second weather small-talk story in Gaza Palestinian Arabic. Include: a greeting, how you feel today, the weather where you are, how the weather was yesterday, what you expect tomorrow or Friday, one comparison, one opinion, and one advice sentence. Reuse at least 8 words from this unit and 5 old words from earlier units.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you? How is the weather where you are?
2. Today the weather is nice, but there is wind.
3. It is raining outside; be careful on the road.
4. There is a lot of heat and humidity today.
5. Yesterday the weather was hotter than today.
6. Tomorrow the weather will be better than today.
7. I like winter because of the rain and hot tea.
8. I cannot stand heat with humidity.
9. There is dust on the road, so be careful.
10. If the weather is sunny on Friday, we will visit my grandmother.
11. I have university today, but it is windy and cloudy outside.
12. There is a lot of humidity today.
13. In spring the weather is nicer than summer.
14. Really? It rained yesterday?
15. God be with you, and tell me when you arrive.`,
    },

    teacherNotes: {
        warmup: [
            "Start with real small talk: مَرْحَبَا، كِيفَك؟ كِيف الجَوّ عِنْدَك؟",
            "This unit's hidden focus is time and comparison: اليَوم، اِمْبَارِح، بُكْرَا، يَوم الجُمْعَة، أَحْسَن مِن، أَحَرّ مِن، أَلْطَف مِن.",
            "Keep the lesson conversational; avoid listing time words as separate vocabulary unless the student needs them.",
        ],
        vocabularySteps: [
            "Teach vocabulary as chunks: فِي شُوب، فِي بَرْد، فِي رُطُوبَة، بِتْشَتِّي، خُد مَعَك...",
            "Use example words like taxi, fare, university, grandmother, water, and tea as recycling, not new vocabulary targets.",
            "Show masculine/feminine through quick substitutions: بَرْدَان / بَرْدَانَة, دِير بَالَك / دِيرِي بَالِك.",
        ],
        dialogueSteps: [
            "Act the dialogue naturally, then have the student change the destination, weather, and advice.",
            "Ask the dialogue questions as spoken output. Push full answers, not one-word answers.",
            "After the dialogue, ask the student to make their own door/building small-talk scene.",
        ],
        practiceTips: [
            "Push student output: one weather sentence, one comparison, one opinion, and one advice sentence.",
            "Recycle transport and time: قَدِّيش الأُجْرَة؟ / عَالوَقْت / قَبْل مَا تْشَتِّي.",
            "Have the student start the next three lessons with a 30-second weather update.",
        ],
        wrapup: [
            "Student gives a 60-second weather update without reading.",
            "Student asks the teacher two weather questions.",
            "Student gives one advice sentence based on the weather.",
        ],
        myNotes: "",
    },
};
